### ISSUE TITLE
Enable ChatGPT / Bing Support

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#101]
# ChatGPT

Here's another probot app and looks like the logic is extremely simple. Can you take the code and replicate the features? Check their README for more details on what the features do exactly but:

- `/review` 
- `/refactor`

As a separate bounty for improving refactor, we can consider opening a PR from the bot and actually commit the change, then we can automatically run CI and verify if the refactor is useful for not.

https://github.com/oceanlvr/ChatGPT-ProBot/blob/main/src/client.js
```javascript
const { ChatGPTAPI } = require('@oceanlvr/chatgpt')
// const { ChatGPTAPI } = require('chatgpt')

const client = new ChatGPTAPI({ sessionToken: process.env.SESSION_TOKEN })

async function search(searchPrompt) {
  await client.ensureAuth()
  const reponse = await client.sendMessage(searchPrompt)
  return reponse
}

async function refactor({ code, lang, prompt }) {
  await client.ensureAuth()

  const searchPrompt = `Refactor folloing ${lang} code. Do not include example usage. ${prompt}.
  ${code}
`
  const reponse = await client.sendMessage(searchPrompt)
  return reponse
}

async function review({ code, lang, prompt }) {
  await client.ensureAuth()

  const searchPrompt = `Review folloing ${lang} code. ${prompt}.
  ${code}
`
  const reponse = await client.sendMessage(searchPrompt)
  return reponse
}

module.exports = {
  search,
  review,
  refactor,
}

```

# Bing

I hear from Twitter that Bing is supposed to be more powerful than ChatGPT (Microsoft owns OpenAI) this could yield better performance for our AI related operations but I'm still waiting for access.

https://github.com/transitive-bullshit/bing-chat

**Comment by pavlovcik** [comment]
Also looks like you broke the UbiquiBot authentication because now I see the pricing done by `github-actions`

**Comment by Steveantor** [comment]
a PR might contain a few hundred file changes, what's the approach?
(cause we may quickly hit the rate limit)

**Comment by pavlovcik** [comment]
I'm not sure I think we will need to experiment on strategies. At a high level, I'm hoping that it can parse CI logs and find where it crashed/had an error. Then we can pass the source code of the file and say, here is the error on this line, please refactor etc.

**Comment by pavlovcik** [comment]
Looks like Bing is not the future.
