### ISSUE TITLE
"whatthediff analyze" API fallback

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#123]
I just thought of this now, but from what I understand this is supposed to be an internal API and is subject to change at any time. Perhaps we should have some type of warning/error/fallback message if this fails?

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/pull/105#discussion_r1106576464_

**Comment by pavlovcik** [comment]
@Steveantor any ideas off hand?

**Comment by Steveantor** [comment]
> @Steveantor any ideas off hand?

the bot could send an internal message on telegram if the API fails,
we might also ask wtd if they're willing to provide us with a more stable API.

**Comment by pavlovcik** [comment]
I'm sure they will want to charge us for it. I think that makes sense as a fallback, where instead of the bot posting the weekly update to the channel, it will actually post the thrown error and ask for developer assistance.

**Comment by Steveantor** [comment]
> I'm sure they will want to charge us for it. I think that makes sense as a fallback, where instead of the bot posting the weekly update to the channel, it will actually post the thrown error and ask for developer assistance.

I'm thinking about two channels, one for public and the other for internal errors 
(so that other adapters/functions could utilize those for errors instead of console)

**Comment by pavlovcik** [comment]
I wonder if it makes sense to start thinking about centralizing our analytics for everything onto Supabase. For example, we have a global errors table. That way, we have a common place to dump every error across every instance of our bot.

**Comment by pavlovcik** [comment]
@Steveantor I was doing some research to see if we can read the diffs from PRs on GitHub's API.

There is an interesting `patch` property that could be useful to pass along to ChatGPT to describe the changes. We could probably fairly easily recreate this feature. Let's consider it a low priority item, but it should be technically quite possible.

```json
[
  {
    "sha": "bbcd538c8e72b8c175046e27cc8f907076331401",
    "filename": "file1.txt",
    "status": "added",
    "additions": 103,
    "deletions": 21,
    "changes": 124,
    "blob_url": "https://github.com/octocat/Hello-World/blob/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "raw_url": "https://github.com/octocat/Hello-World/raw/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "contents_url": "https://api.github.com/repos/octocat/Hello-World/contents/file1.txt?ref=6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "patch": "@@ -132,7 +132,7 @@ module Test @@ -1000,7 +1000,7 @@ module Test"
  }
]
```
from https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files

**Comment by Steveantor** [comment]
> @Steveantor I was doing some research to see if we can read the diffs from PRs on GitHub's API.
> 
> There is an interesting `patch` property that could be useful to pass along to ChatGPT to describe the changes. We could probably fairly easily recreate this feature. Let's consider it a low priority item, but it should be technically quite possible.
> 
> ```json
> [
>   {
>     "sha": "bbcd538c8e72b8c175046e27cc8f907076331401",
>     "filename": "file1.txt",
>     "status": "added",
>     "additions": 103,
>     "deletions": 21,
>     "changes": 124,
>     "blob_url": "https://github.com/octocat/Hello-World/blob/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
>     "raw_url": "https://github.com/octocat/Hello-World/raw/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
>     "contents_url": "https://api.github.com/repos/octocat/Hello-World/contents/file1.txt?ref=6dcb09b5b57875f334f61aebed695e2e4193db5e",
>     "patch": "@@ -132,7 +132,7 @@ module Test @@ -1000,7 +1000,7 @@ module Test"
>   }
> ]
> ```
> 
> from https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files

this needs to be researched

**Comment by Keyrxng** [comment]
@pavlovcik considering it's age, how relevant is this mate?

If it's still relevant, what is the current output and would an in-house version be just as good?

To me reading the site it just looks like it summarizes a PR diff and I know I could craft a better diff summarizer :))
