### ISSUE TITLE
Enhancement: Price Override

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#128]
As [I was cleaning up](https://github.com/ubiquity/ubiquity-dollar/issues/225#issuecomment-1432554966) the deprecated labels on the ubiquity-dollar repo, I realized that it would be nice for the bot to not fight me if I assign a `Price: ` label.

The bot should understand that if I set a Price label, to not wipe it. This also allows maintainers to make custom (financial) deals with bounty hunters as well if needed.

**Comment by me505** [comment]
@rndquu can you give me a idea on how to solve this

**Comment by rndquu** [comment]
> @rndquu can you give me a idea on how to solve this

We have the "assistive pricing" feature. When time and priority labels are set on the issue then the price label is automatically calculated and added. As far as I understand, as a part of this issue we should allow anyone with the "price label" [permission](https://github.com/ubiquity/ubiquibot/blob/c6ceb6c69c33be9bc0b9f3cdb8d334fb329ac859/src/handlers/pricing/action.ts#L26) to override the price label manually.

**Comment by me505** [comment]
Wouldn't the bot just update it back

**Comment by me505** [comment]
Wouldn't the bot just update it back

**Comment by me505** [comment]
in api.github.com/repos/{owner}/{repo}/issues/events
if the latest "labeled" event is done by actor of type user we can assume the price is added by a user and skip relabelling the price right?

**Comment by me505** [comment]
of course assuming the label.name contains Price

**Comment by pavlovcik** [comment]
They also need access control permissions from our database with the `/allow` command. 

Lastly, make sure that the bounty payment will actually use the price label and not try to recalculate based on the priority and time labels.

**Comment by me505** [comment]
I don't think it will recalculate it, can someone qa this

**Comment by Draeieg** [comment]
isn't this conflicting with the scope of #774? @pavlovcik

**Comment by pavlovcik** [comment]
> isn't this conflicting with the scope of #774? @pavlovcik

Yes it is. Given that this implementation is almost completed, we can refactor it as part of #774.

**Comment by BeanieMen** [comment]
@pavlovcik it didn't generate the rewards

**Comment by BeanieMen** [comment]
@0xcodercrane any idea why the bot didnt generate the permit?

**Comment by me505** [comment]
Uhhh

**Comment by cuddle-dev** [comment]
oh @rndquu our temporary solution seems not working for all the cases.

**Comment by cuddle-dev** [comment]
[Deleted]
This is the permit URL for you @me505

**Comment by BeanieMen** [comment]
@0xcodercrane man i am mega sorry about something, i dont have access to that address now, i thought you guy didnt generate the permit so i registered a new address

**Comment by rndquu** [comment]
> oh @rndquu our temporary solution seems not working for all the cases.

Yes, the bot still fails to generate an assignee permit for some of the issues, not sure what it is the root cause of it

**Comment by cuddle-dev** [comment]
> @0xcodercrane man i am mega sorry about something, i dont have access to that address now, i thought you guy didnt generate the permit so i registered a new address

No problem.

**Comment by cuddle-dev** [comment]
The address `0x5387a...` was used 15 days ago for the last time. If you can make sure the account owner `0x5387a...`  doesn't know the claim url I posted earlier[deleted right now], we can regenerate the url for your new address. @me505

**Comment by BeanieMen** [comment]
I am sure

**Comment by BeanieMen** [comment]
@0xcodercrane

**Comment by cuddle-dev** [comment]
@me505
