### ISSUE TITLE
Remove (No Wallet Registered But Bounty Completed) Message

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#234]
With #230, I proposed that the bot should confirm or request the wallet address as soon as the bounty is assigned. 

The following message should be removed entirely and replaced with no action once that other bounty is implemented.

---

              @devpanther would you please post your wallet address here?

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/ubq.fi/issues/6#issuecomment-1499160428_

**Comment by me505** [comment]
so the bot should not post any comment if the user doesnt have a wallet address set?

**Comment by me505** [comment]
@pavlovcik can you assign me?

**Comment by me505** [comment]
why does it say 37.5 and say 56.25 in two different places?
