### ISSUE TITLE
`assign` Response Format

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#252]
GMT should be changed to UTC (GMT is referring to Greenwich in the United Kingdom, UTC is borderless. Because we are a DAO, localizing the time to the United Kingdom doesn't make sense.)

The updated format should look as follows:

---

@0xcodercrane the time limit for this bounty is on Wed, 12 Apr 2023 03:10:59 UTC

Your payment address is `0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46`
Please use `/wallet <WALLET_ADDRESS | ENS_NAME>` to register a new address.

---

              @0xcodercrane The time limit for this bounty is on Wed, 12 Apr 2023 03:10:59 GMT

Your currently set address is:
0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46
please use `/wallet 0x4FDE...BA18` if you want to update it.

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/bounty-bot/issues/240#issuecomment-1502626858_

**Comment by pavlovcik** [comment]
It would be nice to design some type of standardized ascii art "user interface" in the bot comments.

**Comment by pavlovcik** [comment]
Both pull requests don't fulfill the specification. Please review the updated message format carefully.

**Comment by 0xcodercrane** [comment]
ok lets revert it. I think @omraval18 is the original PR owner. would you be assigning yourself?
