### ISSUE TITLE
Disable Bounties for "Parent Issues"

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#268]
### Context

It's fast and easy to write todo lists in the original comment of a GitHub issue, and then immediately convert them to "child issues" directly from the GitHub user interface.

The problem I am seeing is that the bounty system breaks down where contributors can "double dip" on rewards easily by claiming bounties for the actual bounties (child issues) and then the "meta" or "parent" issue.

The argument possibly could be made for project management. However in the future all of the **issue creators**, and **commenters** (both are how the project manager would "manage") are to receive compensation for their contributions upon the completion of the bounty.

### Proposal

- When changing a label, the bot should check if there are linked issues in the original comment and disable setting a price (and most importantly, as a consequence, payment permit generation.)

- The bot should comment explaining why it refuses to set a price.

---

              Parent issues should not have bounties. Instead, the child issues should have bounties.

_Originally posted by @pavlovcik in https://github.com/ubiquity/grants/issues/5#issuecomment-1519067539_

**Comment by Steveantor** [comment]
what are the criteria for a parent issue vs an issue with tasks?

**Comment by pavlovcik** [comment]
> what are the criteria for a parent issue vs an issue with tasks?

I don't understand your question. Parent (meta) issues should have linked child issues, in the form of todo lists with issue links.

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

there's a PR

**Comment by pavlovcik** [comment]
> > Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`
> 
> there's a PR

There is no linked pull request, please link it.

**Comment by Steveantor** [comment]
It can be closed now

**Comment by Draeieg** [comment]
@Steveantor  this seems broken in staging https://github.com/ubiquibot/staging/issues/17

**Comment by wannacfuture** [comment]
@pavlovcik , how can we identify the issue as parent or meta issue? 

I took a look at the previous PR.
Just see if the original comment has ("#XXXX") substring or issue title has "meta" substring?
Or.. Is there other way to identify this?

**Comment by wannacfuture** [comment]
What about this Issue? Seems the previous PR didn't work. Can I assign to this issue? If so, this issue is needed to be unassigned.

**Comment by pavlovcik** [comment]
Hey @wannacfuture just so that you are aware, a payment permit can only be generated once per issue. So generally when an issue is re-opened, that means the previous bounty hunter is obligated to fix it without additional compensation (i.e. do a "hotfix")

> @pavlovcik , how can we identify the issue as parent or meta issue?

Basically we're calling issues-of-issues "meta issues" 

https://github.com/ubiquity/ubiquibot/issues/322 is an example of a meta issue. You can see that it has "2 tasks"

<img width="304" alt="image" src="https://github.com/ubiquity/ubiquibot/assets/4975670/7a1f477c-a49f-42c7-ac4e-1b15f5dbddfb">

The way that they are created is by creating a checklist in the original issue comment. A user can mouse-over each list item and immediately convert them into a new issue, which is associated with the meta issue.

**Comment by pavlovcik** [comment]
Hey @Steveantor, just following up on your availability!

**Comment by b4s36t4** [comment]
Is this up for grabs?! Would love to take a look at it.

**Comment by b4s36t4** [comment]
@Draeieg can you help me with the steps you followed? What's the initial body you added?

**Comment by Draeieg** [comment]
> @Draeieg can you help me with the steps you followed? What's the initial body you added?

https://github.com/ubiquibot/staging/issues/17 just opened this issue in our staging environment, left some without links on purpose and the bot still added price tags

**Comment by pavlovcik** [comment]
@wannacfuture if you want to work on it I can send a manual payment for it after it passes QA.

**Comment by wannacfuture** [comment]
Sooo, @pavlovcik , To identify if the issue is parent issue, we need to investigate the original body of the issue and check just if it has checklist?

**Comment by Steveantor** [comment]
It looks like https://github.com/ubiquibot/staging/issues/17 didn't qualify as a Meta issue
(rather an issue with todo)
![image](https://github.com/ubiquity/ubiquibot/assets/109317559/769a3890-a402-4c53-bf44-235f96e75007)

**Comment by pavlovcik** [comment]
> Sooo, @pavlovcik , To identify if the issue is parent issue, we need to investigate the original body of the issue and check just if it has checklist?
> 
> ?

Check the screenshot in this comment. That "tasks" UI element is very applicable for this. 

https://github.com/ubiquity/ubiquibot/issues/268#issuecomment-1585532148

**Comment by wannacfuture** [comment]
> @wannacfuture if you want to work on it I can send a manual payment for it after it passes QA.

@pavlovcik  I think the hotfix has passed the QA. 😏

**Comment by pavlovcik** [comment]
https://gnosisscan.io/tx/0xa27fe5d0d3a1d8db5467005fd6ad47dd4eab63dbb52bb9ff9149d1021018cb6c
