### ISSUE TITLE
Access Control Manager

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#288]
Working alongside the "roles" idea (`billing_manager`, `member`, `admin`, `recruiting_manager` etc) we should be able to configure specific permissions on the user level for bot interactions and persist those to our database. To clarify, because "roles" are built into GitHub, those are useful for controlling GUI capabilities. The following refers to our custom capabilities via the bot.
- We need to intercept the "change label" event and check WHICH user is setting WHICH label in order to enforce this permissions system.

```
Roles
    Labels
        set priority
        set time
        set price
    Commands
        set payment multiplier
```

For each user we should be able to mark each list item prefixed with "set" as a boolean (true or false.) PER repository. Organization admins should automatically get full access control.

---

The purpose of this is to enable levels of delegation (and controlling funding from permits) within the organization, per repository. 
- It makes sense for technical talent to be able to review and edit bounties to provide a time estimate. 
- It makes sense for project managers to be able to assign a priority level.
- We don't have the #128 feature implemented yet, but my vision is to allow for direct price setting as well, which should have its own access control.
- #221 for context on the payment multiplier.

**Comment by devpanther** [comment]
I assume they won't be able to set labels directly, we'd need a slash command to set the labels, bounty multiplier already works by checking permission

**Comment by devpanther** [comment]
So we'd have to list out the new slash commands and roles that can access them in the yml file @pavlovcik?

**Comment by devpanther** [comment]
And also, the price override should be a quick fix but i don't want to get stuck with its PR for long

**Comment by pavlovcik** [comment]
I didn't think of that. Off hand maybe something like `/access priority username`

/access time username

/access multiplier username

**Comment by devpanther** [comment]
> I didn't think of that. Off hand maybe something like 

That's most likely a table on the database `access`, which would contain repo it was set, username and what it has access to call

**Comment by devpanther** [comment]
So something like the bountyMultiplier will allow admin, treasurer and if not both of em.. it checks the DB for access

**Comment by pavlovcik** [comment]
Note to future self: I guess we should consider renaming it to `multiplier` to make the name succinct. 

Anyways it seems like you have an understanding of the objective. Let me know if you have any other questions or please assign yourself if you are interested.

**Comment by devpanther** [comment]
> Note to future self: I guess we should consider renaming it to `multiplier` to make the name succinct.
> 
> Anyways it seems like you have an understanding of the objective. Let me know if you have any other questions or please assign yourself if you are interested.

Since I am going to be editing that file as well, it would make sense to make the renaming edit as well

**Comment by pavlovcik** [comment]
> > Note to future self: I guess we should consider renaming it to `multiplier` to make the name succinct.
> 
> > 
> 
> > Anyways it seems like you have an understanding of the objective. Let me know if you have any other questions or please assign yourself if you are interested.
> 
> 
> 
> Since I am going to be editing that file as well, it would make sense to make the renaming edit as well

I think that kebab case is cleaner than camel case for the "command line interface" style

**Comment by devpanther** [comment]
> Do you have any updates @devpanther? If you would like to release the bounty back to the DevPool, please comment `/unassign`

Not time to ask yet, still kinda blocked by the comment handler.. Don't want merge conflicts cause I'm working with commands handler that's changing

**Comment by devpanther** [comment]
@pavlovcik We have the `setting access done`, the contributors can't manually alter the labels on the repo so we using commands to handle that.

Ex: `/set-time <1 Week` 

Make sense?

**Comment by pavlovcik** [comment]
It's better to allow contributors to continue to change labels using the GitHub UI.

**Comment by devpanther** [comment]
> It's better to allow contributors to continue to change labels using the GitHub UI.

Unfortunately, they cannot. Github only ever allow members to edit issue labels, contributors can't and there's no tweak to make that work right now

**Comment by devpanther** [comment]
except we start adding everyone contributor as members

**Comment by pavlovcik** [comment]
Public bounty hunters should not have the ability to directly change labels. Only core team.

**Comment by devpanther** [comment]
Except this feature is just for members

**Comment by devpanther** [comment]
Except this feature is just for members @pavlovcik

**Comment by pavlovcik** [comment]
Bounty hunters should not change labels. Only authorized team members with delegated authority can change specific labels, using the GitHub UI.

**Comment by devpanther** [comment]
Okay, i get it now

But looking at the bounty description, you wanted technical talents who are most likely just contributors to be able to edit label and that can be done using the bot command

> It makes sense for technical talent to be able to review and edit bounties to provide a time estimate.


If you say its just for authorized team members, then it means just members with write access would be able to edit label.. all I am doing is intercepting it and checking their access level before actually changing it

**Comment by pavlovcik** [comment]
Seems like you understand the ask. Thanks for clarifying. 

For whatever it's worth, in a future version of the DevPool, @Draeieg and I envision a "betting market" where bounty hunters can get paid to provide time estimates down to the day (e.g. this bounty should take 3 days) and then those who answered the median will get paid from the losers. 

The objective is to incentivize more accurate time estimates for every task. This can be very useful for project managers who are not technical architects to create bounties and set priorities (and let the community figure out the timing)

**Comment by devpanther** [comment]
> Do you have any updates @devpanther? If you would like to release the bounty back to the DevPool, please comment `/unassign`

On it

**Comment by devpanther** [comment]
> Looks like there's something missing from the implementation when compared to the spec https://github.com/ubiquity/ubiquibot/pull/297#issuecomment-1547397332

Yea, the event interception is not there yet.. I don't know why it was closed but I'm pushing it to the PR anyway..

It should open it

**Comment by rndquu** [comment]
> ### [ **[ CLAIM 600 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiNjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNjAyMDgwNjQ1MDgyMjQ5NTA4Nzc5ODkxMjE5Nzk1OTA4NTE3NzMwNjA1MzU2NzgwOTY5OTY2NTIxMzg5OTQxMjA4NjU4Mzc5MDE4NDUiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweGY3NkYxQUNCNjYwMjBmODkzYzk1MzcxZjc0MDU0OUYzMTJERUEzZjEiLCJyZXF1ZXN0ZWRBbW91bnQiOiI2MDAwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDA4ZTViYWYyNmU4Yzc4MzNmYThlMGYyNDI4YjBmZTI1ZTNmYjY1N2UwMjMzODgxZDU3ZjdkODQwYzkyNWM3MTUxY2YxODRhNzY0ZGM0MmRmNDI2ODIxNDU2NzRhZWM4NTU2MDc1MWIzMzdmZmY3ZDhjODlkMGI2NzJmYTgxYjIwMWMifQ==)
> `0xf76F1AC...12DEA3f1`

@pavlovcik should we remove the claim and invalidate the nonce or let it be here?

**Comment by pavlovcik** [comment]
> > ### [ **[ CLAIM 600 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiNjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNjAyMDgwNjQ1MDgyMjQ5NTA4Nzc5ODkxMjE5Nzk1OTA4NTE3NzMwNjA1MzU2NzgwOTY5OTY2NTIxMzg5OTQxMjA4NjU4Mzc5MDE4NDUiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweGY3NkYxQUNCNjYwMjBmODkzYzk1MzcxZjc0MDU0OUYzMTJERUEzZjEiLCJyZXF1ZXN0ZWRBbW91bnQiOiI2MDAwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDA4ZTViYWYyNmU4Yzc4MzNmYThlMGYyNDI4YjBmZTI1ZTNmYjY1N2UwMjMzODgxZDU3ZjdkODQwYzkyNWM3MTUxY2YxODRhNzY0ZGM0MmRmNDI2ODIxNDU2NzRhZWM4NTU2MDc1MWIzMzdmZmY3ZDhjODlkMGI2NzJmYTgxYjIwMWMifQ==)
> 
> > `0xf76F1AC...12DEA3f1`
> 
> 
> 
> @pavlovcik should we remove the claim and invalidate the nonce or let it be here?

Yeah we can invalidate if it hasn't already been claimed. I presume that you have access to the private jet

**Comment by rndquu** [comment]
> > > ### [ **[ CLAIM 600 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiNjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNjAyMDgwNjQ1MDgyMjQ5NTA4Nzc5ODkxMjE5Nzk1OTA4NTE3NzMwNjA1MzU2NzgwOTY5OTY2NTIxMzg5OTQxMjA4NjU4Mzc5MDE4NDUiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweGY3NkYxQUNCNjYwMjBmODkzYzk1MzcxZjc0MDU0OUYzMTJERUEzZjEiLCJyZXF1ZXN0ZWRBbW91bnQiOiI2MDAwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDA4ZTViYWYyNmU4Yzc4MzNmYThlMGYyNDI4YjBmZTI1ZTNmYjY1N2UwMjMzODgxZDU3ZjdkODQwYzkyNWM3MTUxY2YxODRhNzY0ZGM0MmRmNDI2ODIxNDU2NzRhZWM4NTU2MDc1MWIzMzdmZmY3ZDhjODlkMGI2NzJmYTgxYjIwMWMifQ==)
> > 
> > 
> > > `0xf76F1AC...12DEA3f1`
> > 
> > 
> > @pavlovcik should we remove the claim and invalidate the nonce or let it be here?
> 
> Yeah we can invalidate if it hasn't already been claimed. I presume that you have access to the private key

I don't have access to the bot's private key because it is hidden in github secrets.

**Comment by devpanther** [comment]
I'd claim it when I'm done, if there is a way to make it sure it doesn't regenerate

**Comment by 0xcodercrane** [comment]
> Looks like there's something missing from the implementation when compared to the spec [#297 (comment)](https://github.com/ubiquity/ubiquibot/pull/297#issuecomment-1547397332)

I guess we might need to have a way to link the QA issue and generate permit url after its completed.

**Comment by pavlovcik** [comment]
> > Looks like there's something missing from the implementation when compared to the spec [#297 (comment)](https://github.com/ubiquity/ubiquibot/pull/297#issuecomment-1547397332)
> 
> I guess we might need to have a way to link the QA issue and generate permit url after its completed.

We should strive to implement automated testing instead. Our human QA is a temporary workaround.

**Comment by devpanther** [comment]
Why'd it regenerate, i saw a line stating if the paid label is available.. It should skip generation

**Comment by pavlovcik** [comment]
> Why'd it regenerate, i saw a line stating if the paid label is available.. It should skip generation

@0xcodercrane
