### ISSUE TITLE
Migrate to kebab case config

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#299]
This [PR](https://github.com/ubiquity/bounty-bot/pull/282) introduced a kebab case config so we should gradually migrate to maintain backwards compatibility with existing configs

What should be done:
- [x] Update [config generation page](https://pay.ubq.fi/secret) so that it generated kebab base params
- [x] Make sure an **org wide config** is generated for all our [partners](https://github.com/ubiquity/devpool-directory/blob/development/projects.json) (need to generate an org wide config for https://github.com/Alpha-Labs-Global)
- [x] Deploy the latest bot version (which includes https://github.com/ubiquity/bounty-bot/pull/282)
- [x] Update **repository wide** config files of our partners to use kebab case configs
    - https://github.com/Alpha-Labs-Global/blockalizer/pull/70
    - https://github.com/ubiquity/ubiquity-dollar/pull/662
    - https://github.com/ubiquity/.github/pull/71

**Comment by pavlovcik** [comment]
> Make sure an org wide config is generated for all our [partners](https://github.com/ubiquity/devpool-directory/blob/development/projects.json)

Can you elaborate on this? Perhaps you can break these apart into separate bounties (this is easy to do in the GitHub UI when you mouseover, in case you haven't seen this feature.)

**Comment by rndquu** [comment]
> > Make sure an org wide config is generated for all our [partners](https://github.com/ubiquity/devpool-directory/blob/development/projects.json)
> 
> Can you elaborate on this? Perhaps you can break these apart into separate bounties with more detailed specifications (this is easy to do in the GitHub UI when you mouseover, in case you haven't seen this feature.)

We need to:
1. Use https://pay.ubq.fi/secret to generate an organisation wide config (which uses kebab case params proposed here https://github.com/ubiquity/pay.ubq.fi/pull/61)
2. Ask https://github.com/Alpha-Labs-Global to also generate an organisation wide config using https://pay.ubq.fi/secret

This way we would have global kebab cased config for all partners. Then when we update the bot to the latest version repository wide configs should be broken (because they use camel case params) but thanks to the repository wide config  (which is using the updated kebab case params) the bot will still be working.

**Comment by pavlovcik** [comment]
I think we're further along on this. It appears that our `ubiquibot-config.yml` is in kebab case. Can you provide an update @rndquu? 

Also why hasn't the bot seemed updates on this? @0xcodercrane

**Comment by rndquu** [comment]
> I think we're further along on this. It appears that our `ubiquibot-config.yml` is in kebab case. Can you provide an update @rndquu?
> 
> Also why hasn't the bot requested updates on this? @0xcodercrane

Did you [generate](https://pay.ubq.fi/secret) an org wide config for https://github.com/Alpha-Labs-Global ?

**Comment by 0xcodercrane** [comment]
> > I think we're further along on this. It appears that our `ubiquibot-config.yml` is in kebab case. Can you provide an update @rndquu?
> > Also why hasn't the bot requested updates on this? @0xcodercrane
> 
> Did you [generate](https://pay.ubq.fi/secret) an org wide config for https://github.com/Alpha-Labs-Global ?

Nope. I think we couldn't do it because we don't have a private key of alpha-labs-global

**Comment by 0xcodercrane** [comment]
> > 
> 
> @0xcodercrane and I have admin access on their organization so we have the authority to make changes on their behalf!

No ser. I am only a collaborator. clarified about that several days ago

**Comment by rndquu** [comment]
> > > I think we're further along on this. It appears that our `ubiquibot-config.yml` is in kebab case. Can you provide an update @rndquu?
> > > Also why hasn't the bot requested updates on this? @0xcodercrane
> > 
> > 
> > Did you [generate](https://pay.ubq.fi/secret) an org wide config for https://github.com/Alpha-Labs-Global ?
> 
> Nope. I think we couldn't do it because we don't have a private key of alpha-labs-global

@pavlovcik said that he would generate an org wide config for https://github.com/Alpha-Labs-Global

So if the config is generated then we can update all repository wide configs from camel case to kebab case

**Comment by pavlovcik** [comment]
> Nope. I think we couldn't do it because we don't have a private key of alpha-labs-global

They never set up a wallet so it would be from scratch. To clarify, I'm using this as a training exercise because they haven't used the system correctly (they don't use GitHub issue tracking or write specifications for their tasks, so it seems that they might not be the ideal partner for beta etc.)

**Comment by rndquu** [comment]
> > Nope. I think we couldn't do it because we don't have a private key of alpha-labs-global
> 
> They never set up a wallet so it would be from scratch. To clarify, I'm using this as a training exercise because they haven't used the system correctly (they don't use GitHub issue tracking or write specifications for their tasks, so it seems that they might not be the ideal partner for beta etc.)
> 
> I have never generated a config before. Could you provide me a checklist of instructions to follow for now and future reference?

> They never set up a wallet

Yes, so I'm wrong saying that https://github.com/Alpha-Labs-Global don't need an org wide config. They need one to store a wallet's private key there because private key can only be stored in an org wide config.

> Could you provide me a checklist of instructions to follow

We already have it described in [partner integration docs](https://dao.ubq.fi/ubiquibot-setup)

**Comment by pavlovcik** [comment]
Looks like the wizard halfway worked:

https://github.com/Alpha-Labs-Global/ubiquibot-config

Was created but there was an error presumably committing the config.

<img width="1859" alt="image" src="https://github.com/ubiquity/ubiquibot/assets/4975670/25681703-bc6a-4708-a0b8-89e3185a307f">

**Comment by pavlovcik** [comment]
I manually created the config file.
