### ISSUE TITLE
"Please Leave a Review"

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#307]
Upon payment permit generation the bot should say something like "If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!"

**Comment by pavlovcik** [comment]
Perhaps we can do a lottery to give people a reason to press the buttons.

**Comment by wannacfuture** [comment]
so, just quick question. should I add "If you enjoy the ...." label before the "Permitted" label is added?

**Comment by pavlovcik** [comment]
> @pavlovcik! so, just quick question. should I add "If you enjoy the ...." comment before the "Permitted" label is added to that issue and the issue closed?

I would put it at the very end, so after the `Permitted` label is added!

**Comment by wannacfuture** [comment]
yeah, seems I did it right.
