### ISSUE TITLE
Contributor Comment Financial Incentives - On Pull Request

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#311]
Related #272

- Continue support for totaling contributions on the linked/merged pull request. 
- This will enable support for compensating pull request reviewers and synchronizing the calculation and permit generation once the bounty is completed.
- Be sure to cap the rewards PER contributor to the bounty price. 
  - If the bounty price is $100, and if a contributor earned $100 of comment rewards, the bot should immediately leave a warning comment letting them know that their contribution rewards are capped at the $100. 
  - This should disincentivize core team from "tutoring" low performing bounty hunters. 

---

The last part of this puzzle to solve is to allow reviewers to drop the bounty in a way that 1. is in line with the bounty hunter expectations and 2. doesn't make the bounty hunter feel bad/discouraged.

Reviewers take a risk for a bounty not being completed by a low performing hunter. Technically they could push it over the finish line by producing the last of the code and closing the pull request (I've done this before) in order to collect their comment incentives. If the bounty is not completed, nobody should receive their incentives.

**Comment by 0xcodercrane** [comment]
> /assign

I am just curious if the spec is clear to you or @pavlovcik chatted with you in dm. Just check in whether everything is clear before getting started

**Comment by pavlovcik** [comment]
> I am just curious if the spec is clear to you or @pavlovcik chatted with you in dm. Just check in whether everything is clear before getting started

No, I don't talk about bounties in private messages for this reason.

**Comment by visitskyworld** [comment]
@pavlovcik how can I DM you?

**Comment by pavlovcik** [comment]
All communication on here

**Comment by visitskyworld** [comment]
@pavlovcik I can't run the project on local. I have commonjs related error. Can you tell me how to fix it?

**Comment by pavlovcik** [comment]
- https://github.com/ubiquity/ubiquibot/blob/development/README.md
- https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/build.yml
- @0xcodercrane

**Comment by rndquu** [comment]
> > @pavlovcik I can't run the project on local. I have commonjs related error. Can you tell me how to fix it?
> 
> This would probably be a `mdast` npm error. any updates for this @rndquu ?

https://github.com/ubiquity/ubiquibot/pull/377

**Comment by 0xcodercrane** [comment]
@visitskyworld we've fixed this issue. please merge `development` branch into your branch and try it out!

**Comment by wannacfuture** [comment]
@pavlovcik , To make a long story short, so, do we need to give reward to the PR reviewers when the PR is merged?
And the reward must not exceed than the bounty of issue, right?

How can we calculate the reward? Could you give me more detail?

**Comment by pavlovcik** [comment]
When the issue is closed as complete. The calculation is in #272

**Comment by wannacfuture** [comment]
@pavlovcik , Lets assume that the bounty for the issue is $100, and we calculated the reward for the PR reviewer as 80$,
Then should we give the hunter $20, and $80 to reviewer?

And also, what about this situation?
There are several PR reviewers and we need to give them each $50, $50, $50.
What should we do?

**Comment by pavlovcik** [comment]
It's not zero sum so the bounty price should go entirely to the bounty hunter and then the reviewer incentive should be added independently.

**Comment by wannacfuture** [comment]
working on it. @Mr.Bot 😀

**Comment by wannacfuture** [comment]
waiting for https://github.com/ubiquity/ubiquibot/pull/545

**Comment by wannacfuture** [comment]
Waiting for https://github.com/ubiquity/ubiquibot/pull/545

**Comment by wannacfuture** [comment]
'll finish today.
