### ISSUE TITLE
Limit Permit Generation

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#313]
The bot should parse through the conversation history for any links posted, and parse the encoded payment permit in order to verify that a payment permit has been generated. We can probably fork the logic in the audit dApp, as I believe it is already doing this. 

Please remove the non-functional code referenced here https://github.com/ubiquity/ubiquibot/issues/288#issuecomment-1551899645 

---

              ### [ **[ CLAIM 600 DAI ]** ](https://pay.ubq.fi)
```0xf76F1AC...12DEA3f1```

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/ubiquibot/issues/288#issuecomment-1551881478_

**Comment by rndquu** [comment]
> In the future we should set the nonce to be related to the issue ID

Yes, we could use smth like `nonce = keccak256(issueNodeId)` (keeping in mind that issue's node id is unique)

**Comment by pavlovcik** [comment]
Can we do this with our current setup or are there blockers? I prefer that as the bounty as it is a more robust solution.

**Comment by rndquu** [comment]
> Can we do this with our current setup or are there blockers? I prefer that as the bounty as it is a more robust solution.

We already `issue.node_id` as a `nonce`: https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/payout/index.ts#L69

So each issue has a unique nonce and a single permit can not be claimed twice

**Comment by pavlovcik** [comment]
Okay so then this bounty will be just so that the bot doesn't issue a new permit comment.

**Comment by rndquu** [comment]
> What is different about what we are doing currently and your comment?

I thought we don't have this feature (because I don't remember the corresponding task) but then I checked the codebase and this feature was implemented as a part of [other issue](https://github.com/ubiquity/ubiquibot/pull/226)

**Comment by pavlovcik** [comment]
> ### [**[ CLAIM 56.25 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiNTYyNTAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIxMTM1NDg2NjkxNjg2MzIwMjg1MjQ5NTkzMDY3NDY4NTAyMjExNDY2NzY0NzI1MzcxOTYwNjA5ODMwMjkzNDY0OTk1OTYzMDgyMDIxMSIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MDA4NjhCQjNCQTJCMzYzMTZjMmZjNDJFNGFGQjZENDI0NmI3N0U0NiIsInJlcXVlc3RlZEFtb3VudCI6IjU2MjUwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHgxYjg0MzU3MmVmMDBiMDlmNzQyYjA5OWNiOGU3NmExYmUxZWE1Yzc1ZWYwYWI1ZTI5Njc2ODQ1ZmMxNzU5MmViMmQ5NTk2OWFmZDUwNWYzZDVmNmE5NDc1MDNmZmJjNTc5NWJiMjUxYzQ1ZDQzMDhkMDRjZTg3OGU5MzRiYWQ2NzFiIn0=)
> `0x00868BB3...246b77E46`

Looking forward to #341
