### ISSUE TITLE
Bot shouldn't re-send the claim message after the issues are closed and opened again 

### ISSUE THREAD

**Issue by Draeieg** [ubiquity/ubiquibot#321]
![doubletext](https://github.com/ubiquity/ubiquibot/assets/88983138/ea00fe18-a017-47ab-a0b2-89864dcb6f42)
If an issue is successfully closed, opened and closed again the bot will send that claim message again.

There is no Risk of a double payout since the nonce of the tx is tied to the issue, however it would be nicer if the bout sent out a message pointing out there is already a claim message, in line with  #192

**Comment by pavlovcik** [comment]
Duplicate https://github.com/ubiquity/ubiquibot/issues/313

**Comment by pavlovcik** [comment]
@0xcodercrane permit generation should only occur on "closed on completed" 

It looks like you might have reverted another feature.

**Comment by 0xcodercrane** [comment]
> @0xcodercrane permit generation should only occur on "closed on completed"
> 
> It looks like you might have reverted another feature.

No I didn't revert any feature but i think there's sort of order problem in sanity checks. I will wrap up the hotfix either

**Comment by pavlovcik** [comment]
I assume that it needs to check if the issue was "closed as completed" first, and then throw a comment saying 

"Permit generation skipped because the issue was not closed as completed."
