### ISSUE TITLE
Disable the bot follow up on the GitHub issue if there are any pending reviews.

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#323]
Context https://github.com/ubiquity/ubiquibot/issues/322

**Comment by EtherealGlow** [comment]
what would happen if there are multiple  open pull requests

**Comment by EtherealGlow** [comment]
for now  i am gonna assume if any opened pull request has some pending reviews then to disable it

**Comment by EtherealGlow** [comment]
@pavlovcik can you please assign me

**Comment by EtherealGlow** [comment]
i forgot i already did 2

**Comment by EtherealGlow** [comment]
man

**Comment by EtherealGlow** [comment]
Mr bot?

**Comment by pavlovcik** [comment]
@0xcodercrane Another thing broken
