### ISSUE TITLE
Permit Generation Sanity Check Ordering

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#340]
1. There is no private key/linked permit wallet from the project.
2. There is not enough allowance in the wallet
3. There is not enough funding (DAI) in the wallet

Open to feedback and input on this because I'm sure I did not think of every edge case.

              I assume that it needs to check if the issue was "closed as completed" first, and then throw a comment saying 

"Permit generation skipped because the issue was not closed as completed."

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/321#issuecomment-1566995703_

**Comment by 0xcodercrane** [comment]
Its done
