### ISSUE TITLE
Repository Price Labels Should Update When `base-rate` Updated

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#341]
It has caused confusion where the `Price` label does not match the generated permit claim amount. This is because the bot currently does not monitor changes to the `base-rate` and then check the `Price` labels to see if they are accurate. People are sensitive about money so it is worth putting extra attention to detail on this one. 

I'm not sure of the exact best approach here (ideally this logic runs if the `ubiquibot-config.yml` was detected to have been updated.)

I believe this is the most efficient approach from a API rate limit perspective: 

1. Start when the `ubiquibot-config.yml` has been updated
2. Take note of the old base rate
3. Take note of the new base rate
4. Query the repositories labels API for a list of all of the labels
5. Directly edit the `Price` labels noting the difference between the old and new base rates.

Context: https://github.com/ubiquity/ubiquibot/issues/329#issuecomment-1565436831

**Comment by devpanther** [comment]
@pavlovcik should it compare base with previous file content or the default we have saved

because for a current repo that has their base altered, the bot won't know about this and only increase comparing with the base it met

**Comment by pavlovcik** [comment]
Perhaps a bit more of research is needed, and perhaps it's my fault for not confirming this before authorizing this to be a bounty. However IF this is the best approach, then I assume you could check the file history of `ubiquibot-config.yml` with a GitHub API. After all, git is designed for version control.

**Comment by rndquu** [comment]
@devpanther perhaps we could:
1. Catch the [push event](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#push)
2. Check that `commits.modified` has the config file
3. If the config is updated then get the previous config version
4. If `base-multiplier` was updated then update labels accordingly

Also notice that `base-multiplier` might exist in 2 places:
1. Repository wide config, example: https://github.com/ubiquity/ubiquibot/blob/development/.github/ubiquibot-config.yml
2. Organisation wide config, example: https://github.com/rndquu-org/ubiquibot-config/blob/main/.github/ubiquibot-config.yml

P.S. there is also a `payload.compare` URL with changes in the push event, perhaps we could utilize it

**Comment by devpanther** [comment]
@rndquu i already have 1 - 4 and it works

**Comment by devpanther** [comment]
The only problem is, base rate multiplier that has been changed before won't be accounted for..

It only gets difference between last object and the new

**Comment by devpanther** [comment]
So what are you saying we compare with, should it just be the default(1000) so no matter what it meets, it only calculates it by the difference between 1000 and the new multiplier

**Comment by rndquu** [comment]
> So what are you saying we compare with, should it just be the default(1000) so no matter what it meets, it only calculates it by the difference between 1000 and the new multiplier

I don't really get the issue described here, need to see the code :)

**Comment by Draeieg** [comment]
@devpanther  I haven't been able to replicate this working properly on staging https://github.com/ubiquibot/staging/issues/23

do you have an inteded workflow to share?

**Comment by pavlovcik** [comment]
Should @0xcodercrane revert this?

**Comment by devpanther** [comment]
@0xcodercrane, I'd need more details on how it broke the bot.. This isn't my first time working with event handlers on this repo and I don't see any way I broke the bot

It works for me as I test all of my issues, I need more context

**Comment by 0xcodercrane** [comment]
I've added @devpanther as a member of the ubiquibot organization. After you accept the invite, please take a look at [the relevant QA](https://github.com/ubiquibot/staging/issues/23). This is getting managed by @Draeieg. so you guys can communicate there

**Comment by pavlovcik** [comment]
> we can ask him a hotfix pr and block him to take other bounties until it gets fixed

We can also re-open this issue because they are still assigned. It should work just as well. 

Perhaps this is another reason why the default amount of assigned issues should be 1 so that none of these pending hotfixes slip through the cracks.

**Comment by pavlovcik** [comment]
@0xcodercrane

**Comment by 0xcodercrane** [comment]
1/ `Can we access the logs (output from the ingestion key - logger) for staging?` --- as of now, no. By the way, when you use the github action to link a proof of work, you can update logdna key by creating a new one. It has free version so you can easily get it and replace it [here](https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/bot.yml#L78)

2/ In terms of permission upgrade,  I guess you can get clear requests to us if you try a QA.
