### ISSUE TITLE
Add `/chain` command

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#347]
We should add the ability for a bounty hunter to set a chain for payouts (right now we support ethereum mainnet and gnosis chain)

What should be done:
1. Add a new `/chain` command which bounty hunter would use for setting payouts. Examples: `/chain 1` => sets chain to ethereum mainnet, `/chain 100` sets chain to gnosis
2. Preferred bounty hunter chain id should be saved in DB (supabase in our case)
3. If bounty hunter tries to set a chain that the bot [doesn't support](https://github.com/ubiquity/ubiquibot/blob/development/src/helpers/payout.ts#L20) it should print an error message
4. If chain id is saved the bot should print a success message
5. [Here](https://github.com/ubiquity/ubiquibot/blob/development/src/bindings/config.ts#L26) we should get chain id from bounty hunter's preferences (DB). Hierarchy is the following (the latter overwrites the former):
    a) organisation wide config
    b) repository wide config
    c) bounty hunter preferred chain id
6. In `/help` command output for the `/chain` command state that default chain for payouts is ethereum mainnet
7. Add preferred chain to this [helper text](https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/comment/handlers/assign.ts#L108) (response for the `/assign` command)
8. Add preferred chain to the [permit comment](https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/payout/index.ts#L74)

**Comment by rndquu** [comment]
@pavlovcik pls check the description

**Comment by pavlovcik** [comment]
-- 1. `/network` might be better because rollups are not technically considered as "chains"
-- 3. Perhaps we should track a list of supported networks based on their [official deployments](https://docs.uniswap.org/contracts/v3/reference/deployments) and log a warning if the chain ID is not one of those documented supported networks, basically adding to your point.
-- 6. Is it too burdensome to dynamically modify the help message based on the org/repo/hunter preferred network ID?
-- 7. Nice attention to detail
-- 8. Definitely

We could also enhance the usability by checking the permit validity on all of the supported networks simultaneously on pay.ubq.fi right? Then the dApp can suggest to automatically change to the correct network.

**Comment by rndquu** [comment]
> /network might be better because rollups are not technically considered as "chains"

We already have `chain-id` in the config along with the `chainId` in the bot's codebase. I think the `/network` command will add more confusion to the codebase compared with the `/chain` one.

> Perhaps we should track a list of supported networks based on their [official deployments](https://docs.uniswap.org/contracts/v3/reference/deployments) and log a warning if the chain ID is not one of those documented supported networks

Gelato network (used for gnosis safe transactions) might to support all of the networks [here](https://docs.uniswap.org/contracts/v3/reference/deployments). So we'd better maintain a list of supported chains ourselves for now.

> Is it too burdensome to dynamically modify the help message based on the org/repo/hunter preferred network ID?

I actually thought it to be static (always ethereum mainnet) to eliminate confusion on the default payout chain used. In the end a bounty hunter will be able to see a payout chain in a permit URL bot's message.

> We could also enhance the usability by checking the permit validity on all of the supported networks simultaneously on pay.ubq.fi right? 

yes

**Comment by pavlovcik** [comment]
> We already have chain-id in the config along with the chainId in the bot's codebase. I think the /network command will add more confusion to the codebase compared with the /chain one.

Perhaps refactoring all to `network`? I just think that using the word "chain" in this context is antiquated from a time before rollups. This reminds me a lot of when people say "impermanent loss" in the context of being a liquidity provider. The correct term is "divergence loss" and I'm deliberate about using that terminology regardless of what memes related to "impermanent loss" caught on in the industry. 

> Gelato network (used for gnosis safe transactions) might to support all of the networks [here](https://docs.uniswap.org/contracts/v3/reference/deployments). So we'd better maintain a list of supported chains ourselves for now.

I didn't understand your first sentence. We can maintain our own list, sure.

**Comment by rndquu** [comment]
> I didn't understand your first sentence. We can maintain our own list, sure.

Mistype, Gelato network (used for gnosis safe transactions) might **not** support all of the networks [here](https://docs.uniswap.org/contracts/v3/reference/deployments). So we should support networks that:
1. have permit2 deployed
2. gelato supports

> Perhaps refactoring all to network?

There is too much unnecessary refactoring. We can create a task with low priority though.

**Comment by pavlovcik** [comment]
> We can create a task with low priority though.

Please create the specification as I fear that mine would not be as accurate as yours (I am not intimately familiar with this codebase.)

**Comment by EtherealGlow** [comment]
Is there a priority for this

**Comment by EtherealGlow** [comment]
@pavlovcik why did you remove the price labels for some issues and not other?

**Comment by pavlovcik** [comment]
I ran a script to remove labels on the wrong repo. I'll regenerate the price labels soon.

**Comment by rndquu** [comment]
Closing this one in favor of a [singe UI for payouts](https://github.com/ubiquity/ubiquibot/issues/589#issuecomment-1676486284)
