### ISSUE TITLE
Remove `time-labels.target` from partner configs

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#349]
This [PR](https://github.com/ubiquity/ubiquibot/pull/348) removes price range label so we don't need the `time-labels.target` bot config

When this [PR](https://github.com/ubiquity/ubiquibot/pull/348) is deployed to production (i.e. bot version should be > 0.1.2) we should remove the `time-labels.target` from our [partner projects](https://github.com/ubiquity/devpool-directory/blob/development/projects.json)

**Comment by pavlovcik** [comment]
Looks like pricing is broken.

**Comment by pavlovcik** [comment]
I'm not sure why the bot seems to be ignoring this issue.

**Comment by 0xcodercrane** [comment]
ok it is related to range labels

**Comment by baibhavKumar1** [comment]
@pavlovcik @rndquu  To resolve this issue, this [line](https://github.com/ubiquity/pay.ubq.fi/blob/development/static/scripts/onboarding/onboarding.ts#L104) from this org and other similar org should be removed ,right?

**Comment by rndquu** [comment]
> @pavlovcik @rndquu To resolve this issue, this [line](https://github.com/ubiquity/pay.ubq.fi/blob/development/static/scripts/onboarding/onboarding.ts#L104) from this org and other similar org should be removed ,right?

No, `time-labels.target` should be removed. I've checked all of the configs and the `time-labels.target` property is already removed from all of the configs so the current issue is no longer relevant.
