### ISSUE TITLE
`/wallet` Parser

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#351]
1. `/wallet` should parse strictly when its the first word in the comment body. 
   1. It should only pass if it parses exactly as `/wallet` 
2. It should also only accept the following word as input for the address.
   1. It should only work if it passes an Ethereum wallet regex.

Pseudo regex (untested)

`^\/wallet\s0x[a-fA-F0-9]{40}$`

**Comment by 0xcodercrane** [comment]
> Bot wants to pay my wallet instead of @0xcodercrane's
> 
> > @0xcodercrane The time limit for this bounty is on Thu, 01 Jun 2023 08:53:02 GMT
> 
> > Your currently set address is:
> > 0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d
> > please use `/wallet 0x4FDE...BA18` if you want to update it.
> 
> _Originally posted by @ubiquibot-dev[bot] in [ubiquibot/staging#15 (comment)](https://github.com/ubiquibot/staging/issues/15#issuecomment-1569774132)_

Its not an issue. I was just updating wallet address on staging with yours lol

**Comment by pavlovcik** [comment]
> Updated the wallet address for @0xcodercrane successfully! Your new address: `0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d`

Well, that looks like an issue!

**Comment by 0xcodercrane** [comment]
> > Updated the wallet address for @0xcodercrane successfully! Your new address: `0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d`
> 
> Well, that looks like an issue!

yeah this is definitely an issue

**Comment by 0xcodercrane** [comment]
but the spec needs to be changed

**Comment by Draeieg** [comment]
does it makes sense to allow various users to cash out using the same address?, cuz now that I look at it that seems wrong lol

**Comment by pavlovcik** [comment]
Consolidated into #477
