### ISSUE TITLE
Adjust payouts in comment incentives

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#355]
We have recently implemented the ["comment incentives" feature](https://github.com/ubiquity/ubiquibot/issues/272) which adds payouts for issue comment contributions

We should:
1. make incentives for an original issue description greater than for a regular comment.
2. adjust payout amounts according to a currently set bot's param `base-multiplier`.

Original proposals:
```
Double the credit in the original post (e.g. the bounty specification should receive double credits like $0.2/word etc. to try and compensate for the time to think of the bounty in the first place.)
```

```
Read repository BASE_RATE from the ubiquibot-config.yml and multiply the output
```

What should be done:
1. Create a new bot's config param (smth like `issue-creator-multiplier`)
2. On comment incentive payout generation multiply pricing for original post (i.e. issue description) by the newly created config param from step 1
3. On comment incentive payout generation multiply total incentive reward by the `base-multiplier` bot's config param

**Comment by pavlovcik** [comment]
How about `issue-creator-multiplier`?

**Comment by rndquu** [comment]
> How about `issue-creator-multiplier`?

seems fine, updated the description

**Comment by wannacfuture** [comment]
Hi, @rndquu and @pavlovcik,

Could you please verify if my understanding is accurate? Let's assume that there are two multipliers: issue-creator-multiplier and issue-base-multiplier. When a comment is added to a specific issue, does the issue price increase by a factor of the issue-creator-multiplier, and do the comment incentives increase by a factor of the issue-base-multiplier?

Additionally, has the "comment incentives feature" been implemented?
