### ISSUE TITLE
Add sync workflow for config param names

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#357]
Depends on https://github.com/ubiquity/ubiquibot/issues/327

We are in the process of an active development so we refactor the bot's [config](https://github.com/ubiquity/ubiquibot/blob/development/.github/ubiquibot-config.yml) param names occasionally.

The latest refactors (both implemented and planned):
- move from camel case to kebab case (implemented)
- refactor `chainId` to `networkId` (planned)

Updating config param names for all our [partners](https://github.com/ubiquity/devpool-directory/blob/development/projects.json) is tedious. We should automate this process.

What should be done:
- When https://github.com/ubiquity/ubiquibot/issues/327 is implemented create a github workflow with manual dispatch that takes the default yml config (from https://github.com/ubiquity/ubiquibot/issues/327) and creates PRs with updated config param names for [partner projects](https://github.com/ubiquity/devpool-directory/blob/development/projects.json)

So in the end the workflow should be able to create config update PRs which:
1. Add newly added bot's config params
2. Rename config params (example: `chain-id => evm-network-id`)

**Comment by pavlovcik** [comment]
Another idea for a simple solution (probably too late to pitch this though) the bot should reply to closed as completed issues in the payout comment with an error message saying that the config didn't parse correctly and that it's using the organization defaults.  

I feel like this is the most confusing time for contributors.

**Comment by rndquu** [comment]
> Another idea for a simple solution (probably too late to pitch this though) the bot should reply to closed as completed issues in the payout comment with an error message saying that the config didn't parse correctly and that it's using the organization defaults.
> 
> I feel like this is the most confusing time for contributors.

Perhaps when https://github.com/ubiquity/ubiquibot/pull/383 is finally merged we could create a task like "The bot should comment with an error message if it finds an unrecognized config param name (i.e. unrecognized config param name doesn't exist in the default config)"

**Comment by pavlovcik** [comment]
Do you think you could take over my attempt at fixing the default config in my pr if you have time this upcoming couple of days?

https://github.com/Venoox/ubiquibot/pull/18

The part I got hung up on was the default configs. I have more comments on it in my pr.

**Comment by rndquu** [comment]
> Do you think you could take over my attempt at fixing the default config in my pr if you have time this upcoming couple of days?
> 
> [Venoox#18](https://github.com/Venoox/ubiquibot/pull/18)
> 
> The part I got hung up on was the default configs. I have more comments on it in my pr [here](https://github.com/Venoox/ubiquibot/pull/18#pullrequestreview-1550716443).
> 
> I think I resolved the merge conflicts well but I'm quite confused around the defaults and am not confident on how to proceed.

I'll check it

**Comment by pavlovcik** [comment]
It might be wise to diff my pull request against upstream (@ubiquity/ubiquibot) development head

**Comment by AnakinSkywalkeer** [comment]
@rndquu seems like the person assigned to this issue kinda confused also it passed the deadline i was before working on this but due to some thing couldn't come online if they continue to be confused can i be assigned again if u guys don't mind

**Comment by EtherealGlow** [comment]
only like making the pr is left, it did update the file in the logs

**Comment by EtherealGlow** [comment]
/wallet 0xa611a37657A76583305F557D63B94834a35C7bF4 
0x411cb85ee378f7411e93b3cfb0dbe4f50740de241052793abb2f6796b1862af21a04468b8d734f3a93e84480bed5aae3e09c71cec374bf2f3906ca6ceb16a7971c

**Comment by EtherealGlow** [comment]
man why you gotta do me like that
