### ISSUE TITLE
Refactor `chain` to `network`

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#358]
Depends on https://github.com/ubiquity/ubiquibot/issues/357

Original [comment](https://github.com/ubiquity/ubiquibot/issues/347#issuecomment-1570085105)

What should be refactored:
- variables and constants (`chainId` => `networkId`, etc...)
- function names (`getChainId` => `getNetworkId`, etc...)
- bot config param (`chain-id` => `network-id`)

P.S. This is a low priority issue

**Comment by starlitnightsky** [comment]
I have a question. Should I wait for until #357 is finished?

**Comment by rndquu** [comment]
> I have a question. Should I wait for until #357 is finished?

yes
