### ISSUE TITLE
Permit Generation Vulnerability

### ISSUE THREAD

**Issue by seprintour** [ubiquity/ubiquibot#361]
I had the ubiquibot installed alongside the local bot i was using to test.

Here's how the issue was produced.

- I disabled autoPay locally so the ubiquibot is now in charge of generation (https://github.com/seprintour/betterbuy/issues/1#issuecomment-1573720014)
- Ubiquibot only listened to the issue closed as completed event, never really checked who closed and which org/repo has the PK it was using to sign (https://github.com/seprintour/betterbuy/issues/1#issuecomment-1573720069).. It just signed it

I am still trying to look into the permit generation file but this is basically everything.. I have no yml file on my repo or secret pk

Here is the txn from this vulnerability: https://etherscan.io/tx/0xd04515123dbf61d1f52e263f9618ceb1e69ce19a942ac581b813a201097b4368

![Screenshot 2023-06-02](https://github.com/ubiquity/ubiquibot/assets/51956013/f53ff9f1-70ec-4f13-b009-d43d50fd128f)

**Comment by pavlovcik** [comment]
Thank you. Would you also be able to propose a solution?

@rndquu @0xcodercrane @Steveantor any comments or proposed solutions on this?

**Comment by rndquu** [comment]
What happened:
1. A few months ago we moved from github action to github app
2. Moving to github app we noticed that we can not longer read partner wallets' private key from their env variables so we moved to org/repo wide configs
3. For backwards compatibility we still had `UBIQUITY_BOT_EVM_PRIVATE_KEY` in our environment
4. Recently we moved to org/repo wide configs
5. Yesterday we removed the deprecated `UBIQUITY_BOT_EVM_PRIVATE_KEY` https://github.com/ubiquity/ubiquibot/commit/9d5015e6bd43b8b19b2fa02f225acafcebe0c691 to eliminate such cases

TLDR; @0xcodercrane pls remove `UBIQUITY_BOT_EVM_PRIVATE_KEY ` from netlify env variables (both prod and dev)

@seprintour thank you for filing an issue

**Comment by 0xcodercrane** [comment]
Removed it from both env

**Comment by seprintour** [comment]
Okay, looks like it worked

It replied with my repo status: https://github.com/seprintour/betterbuy/issues/35#issuecomment-1573838307

**Comment by seprintour** [comment]
Revoke this as well: https://github.com/seprintour/betterbuy/issues/35#issuecomment-1573838307

**Comment by rndquu** [comment]
Yes, now `UBIQUITY_BOT_EVM_PRIVATE_KEY` is empty so [here](https://github.com/ubiquity/ubiquibot/blob/development/src/bindings/config.ts#L65) the `autoPayMode` is set to `false`

**Comment by seprintour** [comment]
> Revoke this as well: [seprintour/betterbuy#29 (comment)](https://github.com/seprintour/betterbuy/issues/29#issuecomment-1573794038)

This is a 2000USD permit

**Comment by rndquu** [comment]
This is definitely a security issue because we should have removed `UBIQUITY_BOT_EVM_PRIVATE_KEY` env variable first and then proceed with the bot's release 0.1.2. I don't know the bug bounty policy so it's up to @pavlovcik to decide

**Comment by pavlovcik** [comment]
Ensure the allowance and balance ([140.75](https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f?a=0xf87ca4583C792212e52720d127E7E0A38B818aD1)) can support the permit claim. Please generate a permit for less than that amount and try again to confirm that this was fixed.

**Comment by rndquu** [comment]
> > Revoke this as well: [seprintour/betterbuy#29 (comment)](https://github.com/seprintour/betterbuy/issues/29#issuecomment-1573794038)
> 
> This is a 2000USD permit

We will have to invalidate those nonces, nothing personal :)

**Comment by seprintour** [comment]
> > > Revoke this as well: [seprintour/betterbuy#29 (comment)](https://github.com/seprintour/betterbuy/issues/29#issuecomment-1573794038)
> > 
> > 
> > This is a 2000USD permit
> 
> We will have to invalidate those nonces, nothing personal :)

Of course, that's why i said it should be revoked

**Comment by seprintour** [comment]
> Ensure the allowance and balance ([140.75](https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f?a=0xf87ca4583C792212e52720d127E7E0A38B818aD1)) can support the permit claim. Please generate a permit for less than that amount and try again to confirm that this was fixed.

It no longer generates a permit

**Comment by pavlovcik** [comment]
Okay. Please send back 900 DAI and we can close this issue. Thank you!

**Comment by seprintour** [comment]
I think its fixed now

**Comment by pavlovcik** [comment]
Thanks for that. 

https://etherscan.io/tx/0xb85517d1a2ed4c9584577be7a6e35999e4dd62aaa4e86c883a1a017375683ac5

I can also send the difference shortly.

**Comment by pavlovcik** [comment]
I sent an extra 50 DAI tip to cover the difference as well as all the gas fees incurred in this deliverable. Thank you again for your report @seprintour 

https://etherscan.io/tx/0x9e20f6503f9fa9d731f8c2d86be930b55d75451babbd7434dd8ae37e2d06d567

**Comment by seprintour** [comment]
> I sent an extra 50 DAI tip to cover the difference as well as all the gas fees incurred in this deliverable. Thank you again for your report @seprintour
>

Thanks for the tip, appreciate it.. :)

**Comment by pavlovcik** [comment]
> We will have to invalidate those nonces, nothing personal :) 

@rndquu can you invalidate those nonces?

**Comment by rndquu** [comment]
> > We will have to invalidate those nonces, nothing personal :)
> 
> @rndquu can you invalidate those nonces?

No, I don't have the bot's PK, https://github.com/ubiquity/ubiquibot/issues/362

**Comment by rndquu** [comment]
@pavlovcik overall funds at risk were ~4k USD (keeping in mind funds in gnosis chain) so perhaps 10% should be calculated from the total amount

**Comment by pavlovcik** [comment]
Yes @rndquu and I discussed this in private messages and technically the Gnosis Chain permit generation was activated about an hour before the vulnerability was reported so we can honor that. Here's an extra 256.25 DAI

https://etherscan.io/tx/0x9c2392f6e10ffac458777fb5ac901a904993bfe2c09d44e4dc4a459f71a6caa4

**Comment by seprintour** [comment]
Oh, thanks a lot @pavlovcik @rndquu.. appreciate it :)
