### ISSUE TITLE
Invalidate nonces

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#362]
https://github.com/ubiquity/ubiquibot/issues/361

Invalidate nonces for:
1. https://pay.ubq.fi/?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI4NTAwNTQ4OTczOTU0MzQxNDE0NTc2NTgyMjk3NTUwMjU1MTI3OTQ4MzA1NjEyMTE0NjI2ODY5MzkxODM1OTU3ODIwMzQxODQ4OTc5IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgzNjIzMzM4MDQ2YjEwMWVjRWM3NDFEZTlDMzU5NENDMjE3NmYzOUU1IiwicmVxdWVzdGVkQW1vdW50IjoiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZjllNzNlMmM1ZWE2Y2QzOGNlOGQ2MWJkZmFjNDQ1MmI2ZmNjYjRiNDYxOWIzOTMwYmUyMzc0ZmYyZmVkNmI5MjQ2MjlhYTVmY2VlNjgwYWZmM2QzYTc3MmEyYzYzYjY0ZWM3ZmJjNmVmZGVmMWM1MzQ4NDk2OWI0Yjg3YTZlYTQxYyJ9
2. https://pay.ubq.fi/?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjczODc5MDgxMjk1OTc1MTMxMjkyMDEyNTc0NzY2NzkzMDg1MDUwODYzODMxNDI4ODA0MzI4MDYwNDUyNDUwNTM4NDQ4NTExMDgzNTMxIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgzNjIzMzM4MDQ2YjEwMWVjRWM3NDFEZTlDMzU5NENDMjE3NmYzOUU1IiwicmVxdWVzdGVkQW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZDZhNjY5MTY3MjY4NDc2MmY3NTFlMjlmYmE5NmRhNDJlMDk0NGM0ODZjOGFjYTdlMjE0M2I2YmYyY2Q3ZjAyNTJiZGIxZWE2ZTg3MzhiM2U0ZDdmZGY3ZWZkMDU1ODJhZjhkZDY5ZWQxNDVkZWZmZTRhNjk3NGU1ZDJiYWQzOWMxYyJ9

**Comment by pavlovcik** [comment]
We should consider logging every permit generated to the database so that we can catch every unauthorized permit.

**Comment by pavlovcik** [comment]
Which method should I call on the Permit contract? @rndquu 

https://etherscan.io/address/0x000000000022d473030f116ddee9f6b43ac78ba3#writeContract

**Comment by rndquu** [comment]
> Which method should I call on the Permit contract? @rndquu
> 
> https://etherscan.io/address/0x000000000022d473030f116ddee9f6b43ac78ba3#writeContract
> 
> The 2000 DAI permit nonce is `73879081295975131292012574766793085050863831428804328060452450538448511083531` according to the pay.ubq.fi interface.
> 
> But I don't understand what parameters to pass in.

Under the bot's account:
1. Open https://etherscan.io/address/0x000000000022D473030F116dDEE9F6B43aC78BA3#writeContract
2. Find `invalidateUnorderedNonces `
3. Use the following params to execute a tx:
```
wordPos: 288590161312402856609424120182785488479936841518766906486142384915814496420
mask: 2048
```

When you're done pls let me know

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x1e285cd893f8aab74384ed1e16b326cfd8bb4c9a48ec96d6d737e77a7baeb62b

**Comment by rndquu** [comment]
> https://etherscan.io/tx/0x1e285cd893f8aab74384ed1e16b326cfd8bb4c9a48ec96d6d737e77a7baeb62b

Both nonces are invalidated right now
