### ISSUE TITLE
Multi Permit Comment Design

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#375]
- Requires the following to be completed 
   - #272
   - #311
- Same as the `/start` bot comment, "multiplier" related rows should only be displayed if they have been changed from the default.
- Sort in order of payment amount. 
## Rendered

<details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 535 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@0xcodercrane</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>10</td>
          </tr>
          <tr>
            <td></td>
            <td>Assignee</td>
            <td>500</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>25</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 157.5 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@pavlovcik</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
          <tr>
            <td></td>
            <td>Creation</td>
            <td>55</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>55</td>
          </tr>
          <tr>
            <td></td>
            <td>Reviewer</td>
            <td>85</td>
          </tr>
          <tr>
            <td>Multiplier</td>
            <td>Amount</td>
            <td>0.75</td>
          </tr>
          <tr>
            <td></td>
            <td>Reason</td>
            <td>A special reason</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 115 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@rndquu</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>65</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
          <tr>
            <td></td>
            <td>Reviewer</td>
            <td>35</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 40 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@Keyrxng</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>25</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 20 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@seprintour</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>5</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  

## Source HTML

```html
<details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 535 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@0xcodercrane</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>10</td>
          </tr>
          <tr>
            <td></td>
            <td>Assignee</td>
            <td>500</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>25</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 157.5 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@pavlovcik</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
          <tr>
            <td></td>
            <td>Creation</td>
            <td>55</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>55</td>
          </tr>
          <tr>
            <td></td>
            <td>Reviewer</td>
            <td>85</td>
          </tr>
          <tr>
            <td>Multiplier</td>
            <td>Amount</td>
            <td>0.75</td>
          </tr>
          <tr>
            <td></td>
            <td>Reason</td>
            <td>A special reason</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 115 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@rndquu</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>65</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
          <tr>
            <td></td>
            <td>Reviewer</td>
            <td>35</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 40 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@Keyrxng</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>25</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyMzM2NjMxMDE0NzI1NTk4MjA0NzQ5MjAwNDE3Mjg0Njc0NjU4NjQ4MzkzMzE3MzUwMDYzOTIyNTI1OTMwODcxODk2OTg1NzM3NjMyOCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ODk1NGM5NDE3OTI5MTQ2MjczMzUxMDVkOGQyNGRhNGUwYzViNzM0NjM4ZGU1NTM2MTM4N2U0NTgyNjk1YTc1MGVjNWVmMmNiNDYxNDlkNDliZjI5YjE5YzZhNGJjNDRhY2RhOTlhODViZDdhM2MyMTI2YTQzZjk2MjdjNzg5MDFjIn0=&network=100"
          >
            [ 20 WXDAI ]</a
          >
        </h3>
        <h6>&nbsp;@seprintour</h6></b
      >
    </summary>
    <code
      ><table>
        <tbody>
          <tr>
            <td>Issue</td>
            <td>Comments</td>
            <td>15</td>
          </tr>
          <tr>
            <td>Review</td>
            <td>Comments</td>
            <td>5</td>
          </tr>
        </tbody>
      </table></code
    >
  </details>
  
```

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquibot/production/issues/6#issuecomment-1577916486_

**Comment by me505** [comment]
@pavlovcik can you elaborate on this issue a little more, i would love to work on this

**Comment by pavlovcik** [comment]
> @pavlovcik can you elaborate on this issue a little more, i would love to work on this

What is unclear? It just needs to list everybody's payment links. 

This depends on contributor comment incentives to be enabled though, or else only the assignee will be able to get a payout.

**Comment by me505** [comment]
@pavlovcik isnt multiplier reason already saved in the database [here](https://github.com/me505/ubiquibot/blob/dev-5/src/adapters/supabase/helpers/client.ts#L185)

**Comment by pavlovcik** [comment]
Yes, but I don't understand why you're asking that question.

**Comment by 0xcodercrane** [comment]
> > @pavlovcik can you elaborate on this issue a little more, i would love to work on this
> 
> What is unclear? It just needs to list everybody's payment links. I included the source HTML in the spec now.
> 
> This depends on contributor comment incentives #272 to be implemented though, or else only the assignee will be able to get a payout. Apparently the issue is closed as completed but I've never seen that capability enabled yet. @0xcodercrane what's the status on it?

Its still in QA but stuck because of function timeout problem on netlify. 

1/ cloudflare migration -- needs to be done within 2 days
2/ Incentive based on comments for issues
3/ Incentive based on comments for pull requests

**Comment by me505** [comment]
thank you mr 0xcodercrane

**Comment by me505** [comment]
.

**Comment by Keyrxng** [comment]
So is this like the pseudo leaderboard or something? How can I be fourth already I think this feature is broke

**Comment by pavlovcik** [comment]
> So is this like the pseudo leaderboard or something? How can I be fourth already I think this feature is broke

Its an example for when an issue is completed. In this example scenario, you received comment incentives on the issue and review. You can click to expand the details.

**Comment by Keyrxng** [comment]
I was joking... after I realised 🤣 for a sec I thought it was legit standings but this will be a cool feature, a leaderboard like this would be class imo

**Comment by pavlovcik** [comment]
> I was joking... after I realised 🤣 for a sec I thought it was legit standings but this will be a cool feature, a leaderboard like this would be class imo

We will eventually roll out a proper leaderboard once the XP system is implemented. Basically the vision is to have a repo/org/global XP ranking. The more tasks completed, the higher the XP goes. Then we can introduce gating, where, for example, an organization can gate off high priority items to bounty hunters with a rank of 100 or more.

**Comment by devpanther** [comment]
> Do you have any updates @devpanther? If you would like to release the bounty back to the DevPool, please comment `/stop` 
> Last activity time: Thu Sep 14 2023 01:52:22 GMT+0000 (Coordinated Universal Time)

Waiting for #704 to get merged
