### ISSUE TITLE
Close Pull Request When `Unassigned`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#379]
In order to keep our pull requests neat and tidy, the bot should automatically close them out when the bounty hunter is disqualified for inactivity on the bounty. Technically we can inject this behavior on top of the `/unassign` command I believe, that way it will happen both during the disqualification, or if the bounty hunter gives up the bounty by invoking the command.

> I think that makes sense to close the pull requests when unassigned. Perhaps we should also have the bot do that.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/634#issuecomment-1575532629_

**Comment by rndquu** [comment]
@0xcodercrane do you understand why the claim URL is 18.75 WXDAI while the price label is 25 USD? I'm expecting the payout to be 25 WXDAI if @wannacfuture has a default bounty modifier

**Comment by pavlovcik** [comment]
I feel like we have two layers of complexity regarding this problem of unexpected payout amounts.

1. we don't have the labels automatically updating when the `base-rate` is updated
2. multipliers 

Because money is generally a sensitive topic, we should figure out a solution to clearly express what the payout amount will be. Perhaps in the bot's response for a bounty being assigned, it should clarify what the total bounty compensation will be for the assignee, which will re-check the `base-rate` AND the current multiplier for the bounty hunter.
