### ISSUE TITLE
Max bounty hunter issues improvement - Configurable Time

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#388]
As an extension of #298 I realized that we should make the time configurable. Please add the config property so our partners can customize this behavior. If you need a default setting, we can make it 24 hours. 

Lastly, we should be able to disable this feature as well. I'm unsure how this will be implemented, perhaps if the config property is not found, or the value is not parseable/valid it can disable. 

> Code looks good. You achieved the specification, thanks for that, but I think I will like to create a new bounty to make the 24 hour period configurable (this also means we need to add a new config property.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/387#pullrequestreview-1473321237_

**Comment by pavlovcik** [comment]
@wannacfuture this one is for you! Thanks.

**Comment by wannacfuture** [comment]
I've done this. But the previous PR should be merged. @0xcodercrane , Could you review the PR #387 ???

**Comment by 0xcodercrane** [comment]
> Thanks, @pavlovcik . I've done this. But the previous PR needs be merged. @0xcodercrane , Could you review the PR #387 ???

Please allow us for a few hours
