### ISSUE TITLE
Ensure Awaits

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#390]
> I made a mistake and realized that it is a different function with a similar name that I fixed in https://github.com/ubiquity/ubiquibot/pull/352#discussion_r1216587731.

> Can you go through the codebase and make sure that we are `await`ing every async function like these?

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/389#discussion_r1226217798_

**Comment by 0xcodercrane** [comment]
> Do you have any updates @0xcodercrane? If you would like to release the bounty back to the DevPool, please comment `/unassign`

Yes, spending my time on other stuff.

**Comment by pavlovcik** [comment]
I think you should assign yourself only on things you're actively working on. I understand that you have dynamic priorities but maybe it's best to unassign yourself before assigning to the latest most urgent task?

**Comment by 0xcodercrane** [comment]
> Do you have any updates @0xcodercrane? If you would like to release the bounty back to the DevPool, please comment `/unassign`

I am fixing the warnings that `yarn lint` caught up

**Comment by pavlovcik** [comment]
Can you finish this bounty this week?
