### ISSUE TITLE
Update readme.md 

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/ubiquibot#391]
The [readme.md](https://github.com/ubiquity/ubiquibot/blob/development/README.md) doesn't have a section on how to create a QA.

Here's the quick instruction for it.
1/ Fork the ubiquibot repo and install the [ubiquibot-qa app](https://github.com/apps/ubiquibot-qa) on the forked repository.
2/ Enable github action running on the forked repo and allow `issues` on the settings tab.
3/ Create a proof of work and describe the steps taken to get it working.
4/ Link that QA issue to the pull request before requesting a review

**Comment by pavlovcik** [comment]
> 1/ Fork the ubiquibot repo and install the [ubiquibot-qa app](https://github.com/apps/ubiquibot-qa) on the forked repository.

Are you sure that they need to install the app on the forked repository? I thought that if we hard coded its credentials in the `.yml` file then it should work.

**Comment by 0xcodercrane** [comment]
Yeah I am sure, even if we hardcode the keys, it couldn't get the installation_token without installing.

**Comment by rndquu** [comment]
@Draeieg perhaps we should also add that bounty hunters should create a QA issue in the [pull request template](https://github.com/ubiquity/ubiquibot/blob/development/.github/pull_request_template.md?plain=1) (or insert a URL to QA readme docs)

**Comment by pavlovcik** [comment]
@0xcodercrane why is the permit for twice the label amount?
