### ISSUE TITLE
Make stricter regex for the multiplier command

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#395]
The bot tried to execute the `/multiplier` command for this [comment](https://github.com/ubiquity/ubiquibot/pull/384#issuecomment-1588471981) although that is a simple comment. 

We should make a stricter regex for the `/multiplier` command.

**Comment by pavlovcik** [comment]
Perhaps we should convert this bounty to identify the root issue. I've only noticed a couple of times in the past couple of months where the bot seems to write a comment seemingly in the wrong conversation. It happened more than once but seems quite rare. 

I think there is a possibility that there is some type of event handler pollution where the bot will be invoked by one issue, and then finish its execution inside of another issue somehow.

**Comment by rndquu** [comment]
> Perhaps we should convert this bounty to identify the root issue. I've only noticed a couple of times in the past couple of months where the bot seems to write a comment as a response seemingly in the wrong conversation. It happened more than once but seems quite rare.
> 
> I think there is a possibility that there is some type of event handler pollution where the bot will be invoked by one issue, and then finish its execution inside of another issue somehow.

It's hard to describe a bug if you can't reproduce it, let's wait if some more cases happen
