### ISSUE TITLE
Disable repo feature

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#396]
Original [discussion](https://github.com/ubiquity/devpool-directory-bounties/issues/6)

We've got a repo which accumulates all [bounties](https://github.com/ubiquity/devpool-directory) from partner projects. There are [cases](https://github.com/ubiquity/devpool-directory/issues/603#issuecomment-1551474188) when bounty hunters try to assign issues directly in that "bounty accumulation" repo although they should self assign directly in the partners' repos.

We should have the ability to disable the bot (i.e. disable reacting to commands) for certain repos.

What should be done:
1. Add a blacklist feature which disables bot commands for certain repos (i.e. on any command check that a parther's repo is not blacklisted)
2. If partner repo is blacklisted then on any command the bot should return an error. This error should be configurable (i.e. add a new bot's param like `blacklist-msg` which will hold the error text)

**Comment by pavlovcik** [comment]
> I thought it should be stored in a plain json file

Is this json file hardcoded inside of the bot source code or in the repo? I think it could be cleaner in the repo.

**Comment by rndquu** [comment]
> > I thought it should be stored in a plain json file
> 
> Is this json file hardcoded inside of the bot source code or in the repo? I think it could be cleaner in the repo.

I meant it to be hardcoded in the bot's code

**Comment by pavlovcik** [comment]
> You mean in the bot's config yml?

Yes I think that we should have configs that allow us to precisely disable certain features.

In this instance we could make: 

```
assistive-pricing: false // reads the `priority` and `time` labels to set a price
auto-payouts: false
```

**Comment by rndquu** [comment]
> > You mean in the bot's config yml?
> 
> Yes I think that we should have configs that allow us to precisely disable certain features.
> 
> In this instance we could make:
> 
> ```
> assistive-pricing: false // reads the `priority` and `time` labels to set a price
> auto-payouts: false
> ```

we can start small with a param for disabling all features, like:
```
enabled: true
auto-payouts: false
```

Then we could set `enabled: false` for https://github.com/ubiquity/devpool-directory
