### ISSUE TITLE
Expired Bounties Remain Un-assignable

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#403]
It appears that when bounties time out that they are no longer assignable to any hunter. This is disrupting to our operations and must be fixed.

1. I do like the idea of restricting bounty hunters from re-assigning themselves (it is their responsibility to provide regular and timely updates.) 
2. I do not like that the bot refuses to leave timed-out bounties assigned as you can see in my linked example:

              Releasing the bounty back to dev pool because the allocated duration already ended!

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/card-issuance/issues/9

**Comment by devpanther** [comment]
@pavlovcik 

I am going to attach the assignee to the unassignMsg like "**@devpanther Releasing the bounty back to dev pool because the allocated duration already ended!**"

And it's going to use that to make sure the tagged assignee cannot reassign but someone else would have a clean slate

**Comment by pavlovcik** [comment]
Sure but when you do that you should export the unassign message and import it into where you check for it to guarantee it is the same string across both files.
