### ISSUE TITLE
`0` Multiplier Not Working

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#404]
I wanted to give myself a 0 multiplier but it still generated a 12.5 DAI permit. 

---

              ### [ **[ CLAIM 12.5 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI2NzU3NzYwOTc4MDQ0MDY5NTk0Nzk1NjU1Nzg2NTIyODkwNDc0Mzg2NDYyNDQ0NTE5ODcyNDYwNzA3NDY0NDc4ODc1NzE3ODg2MjQ3MyIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHhhMTJhZmNiN2EyYjVmODk3NTczNWFkNDk2YmI2M2RjYzhjNDk0ZGM1NTM1NDExZDY4YWU1YjYxZjRiNTI1NmUzNGViZTA4YmFmYTQzMGNkZjEyMjM1ZGZkOTA1ZTBjNTUxM2U5MzUzN2RmYjQyNTg5NDI1MGQwODRlZGIyNTEyNzFiIn0=)
```0x4007CE20...149a341d```

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/ubq.fi/issues/16#issuecomment-1593546695_

**Comment by pavlovcik** [comment]
I was trying to find who originally implemented the multiplier because this should be considered a hot fix but I couldn't quickly find under the issues. @0xcodercrane do you think you can look into this?

**Comment by pavlovcik** [comment]
I'm assuming that @sweetapplepumpkinpie might have broken this as they were the last to modify the multiplier command?

**Comment by sweetapplepumpkinpie** [comment]
> I'm assuming that @sweetapplepumpkinpie might have broken this as they were the last to modify the multiplier command?

I tested the modified code again and it works.

**Comment by pavlovcik** [comment]
Can you post proof?

**Comment by sweetapplepumpkinpie** [comment]
https://github.com/ubiquity/ubq.fi/issues/16#:~:text=Updated%20the%20multiplier%20for%20%40pavlovcik%20successfully!%20New%20multiplier%3A%200

As you can see here,  the bot message is the one that I fixed to  `Successfully changed the payout multiplier for @${username} to ${bountyMultiplier}. The reason ${
      reason ? `provided is "${reason}"` : "is not provided"
    }.`;

What I mean is, I updated the  `Updated the multiplier for @${username} successfully!\t New multiplier: ${bountyMultiplier}` message to  `Successfully changed the payout multiplier for @${username} to ${bountyMultiplier}. The reason ${
      reason ? `provided is "${reason}"` : "is not provided"
    }.`

**Comment by pavlovcik** [comment]
> https://github.com/ubiquity/ubq.fi/issues/16 

This has nothing to do with your changes because that is the production bot. You need to link an example from your fork.

**Comment by 0xcodercrane** [comment]
> I was trying to find who originally implemented the multiplier because this should be considered a hot fix but I couldn't quickly find under the issues. @0xcodercrane do you think you can look into this?

Let me take it over
