### ISSUE TITLE
All Commands Should be in Beginning of Comment

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#406]
Every command should only be accepted by the bot if they are comments that begin with `/` 

So a possible regular expression could be `^\/.+` with the most important part being `^\/` as it says to select the `/` only if its in the beginning of the line. 

> I think that commands should only be recognized if they are in the beginning of the comment. I have never seen a situation where somebody wanted to execute a command inside of a normal written comment.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/384#issuecomment-1593698356_

**Comment by web4er** [comment]
This appears to have been fixed. Here are some tests working fine https://github.com/web4er/ubiquibot/issues/19
I think this issue can be closed.

**Comment by pavlovcik** [comment]
I'll need to do a deep dive using git blame but your demonstration/tests are fantastic evidence of this being fixed. 

Thanks for the attention to detail and I can give you a reward for the testing and closing this out if I believe it's fixed after my deeper inspection.

**Comment by pavlovcik** [comment]
Duplicate 

- https://github.com/ubiquity/ubiquibot/issues/477

**Comment by web4er** [comment]
This got probably fixed in https://github.com/ubiquity/ubiquibot/commit/cb2335714f35cbd53caa31ff2670593b4a5a5c20?diff=split

**Comment by pavlovcik** [comment]
Just going to credit the full amount because it's a small bounty. Thanks! https://gnosisscan.io/tx/0xc27e788638afc006c189eba86783d7eb0af8d0a63a4a7e64ad4bdf631b3b7952

**Comment by web4er** [comment]
> Just going to credit the full amount because it's a small bounty. Thanks! https://gnosisscan.io/tx/0xc27e788638afc006c189eba86783d7eb0af8d0a63a4a7e64ad4bdf631b3b7952

Thank you very much.
