### ISSUE TITLE
Update Assigned Message

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#407]
When a bounty hunter is assigned the new message should include the total bounty compensation amount. This should recalculate the bounty based on 1. their `multiplier` and 2. the `base-rate`.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/379#issuecomment-1593746208_

## New comment template

<code>

<table>
<tbody>
<tr><td>Deadline</td><td>Thu, 15 Jun 2023 10:47 UTC</td></tr>
<tr><td>Registered Wallet</td><td>0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d</td></tr>
<tr><td>Payment Multiplier</td><td>1.00</td></tr>
<tr><td>Multiplier Reason</td><td>Reason</td></tr>
<tr><td>Total Bounty</td><td>100 USD</td></tr>
</tbody></table>
</code>

<h6>Tips:</h6>
<ul>
<li>Use <code>/wallet 0x4FDE...BA18</code> if you want to update your registered payment wallet address @user.</li>
<li>Be sure to open a draft pull request as soon as possible to communicate updates on your progress.</li>
<li>Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the bounty.</li>
<ul>

**Comment by starlitnightsky** [comment]
well, I have a question about this issue.
First time I don't register wallet address, so then how can I output it on the table.
For now, in assigned message this kind of message is showed.

It looks like you haven't set your wallet address,
please use /wallet 0x4FDE...BA18 to do so.
(It's required to be paid for the bounty)

so I have to register wallet address by /wallet command.
In updated assign message, I have to show wallet address when I assign.
How can I do that?

**Comment by pavlovcik** [comment]
Sorry if my specification isn't clear but @starlitnightsky you must include the "tips" section below the table as part of the comment. @0xcodercrane
