### ISSUE TITLE
Unreliable Followups/Unassignment

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#408]
The bot seems to be inconsistent on who it follows up with and then unassigns when dealing with bounties that are assigned but have no updates happening. This is an important feature that should be functional, or else we will have many bounties being reserved and neglected. 

I have a feeling that this stopped being reliable after implementing the capability for the bot to monitor linked pull requests for updates. But this feeling may be unfounded cause I haven't done the research to confirm it. 

              Thanks @pavlovcik. will complete this asap

_Originally posted by @sweetapplepumpkinpie in https://github.com/ubiquity/ubiquibot/issues/176#issuecomment-1583449657_
            

---

I will compile examples as I find them.

- https://github.com/ubiquity/ubiquity-dollar/issues/516

**Comment by wannacfuture** [comment]
@pavlovcik , could you provide more information in detail?  So, what the bot should do about the bounties with no update?

**Comment by pavlovcik** [comment]
The bot should follow up as it does on some bounties (I am assuming it is only working on bounties with an open pull request.)

The thing is, in the linked example above, the bounty hunter never even started the task. It already has been a full week so they should have already been unassigned by now. 

This bounty requires that you figure out the root cause of the issue, as well as provide a fix.

**Comment by wannacfuture** [comment]
> The thing is, in the linked example above, the bounty hunter never even started the task. It already has been a full week so they should have already been unassigned by now.

The reason of not unassigning is there is a comment of that bounty hunter which is created less than a week before.
It seems the bot identifies it as it has activity.

So, let's clarify.
- We should identify issue with only pull request on it even it has comments of the hunter.
- If there is no opened pr on it and it has passed over followup time, the bot should follow up that issue.

What do you think?

**Comment by wannacfuture** [comment]
@pavlovcik , Can you check my thoughts above?

**Comment by pavlovcik** [comment]
> The reason of not unassigning is there is a comment of that bounty hunter which is created less than a week before.
It seems the bot identifies it as it has activity.

There are two "checkpoints"

1. the follow up, where the bot comments "do you have any updates?" this is in about 4 days.
2. the unassign, where the bot will unassign if there is no reply to that question.

**Comment by wannacfuture** [comment]
> 2. the unassign, where the bot will unassign if there is no reply to that question.

how much time the bot should wait after "do you have any updates" comment to unassign the hunter?
