### ISSUE TITLE
Meta Issue `/assign` Refuse Message

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#409]
The bot should explicitly refuse to assign meta issues. This can be confusing for new users so we should fully explain that have not been assigned to any task, and that they should navigate into the sub issues and assign themselves to those instead. 

> Skipping `/assign` since no time labels are set to calculate the timeline

_Originally posted by @ubiquibot in https://github.com/ubiquity/partnerships/issues/26#issuecomment-1593316451_

**Comment by Draeieg** [comment]
This has been covered afaik by #268

Which is currently tagged "not working" in QA
