### ISSUE TITLE
Link multiplier with organization

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#412]
We've got a test organization for QA testing: https://github.com/ubiquibot

We also have a real organization where the bot is used: https://github.com/ubiquity

If you [set a multiplier](https://github.com/ubiquibot/production/issues/1#issuecomment-1594970863) in a QA organization (or create your own org, add "ubiquibot" and set multiplier in your own org where you are the admin) then [it will also be updated](https://github.com/ubiquity/pay.ubq.fi/issues/75#issuecomment-1594971139) in a "production" organization.

We should link a bounty hunter's multiplier to an organization where the multiplier is set.

**Comment by me505** [comment]
Can you elaborate on where to link the multiplier with organization. 
I would love to work on this!

**Comment by rndquu** [comment]
> Can you elaborate on where to link the multiplier with organization. I would love to work on this!

Username, multiplier and organization should be linked in a DB.

 In other words make sure that:
1. [Here](https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/comment/handlers/multiplier.ts#L71) organization name is also saved to a DB
2. [Here](https://github.com/ubiquity/ubiquibot/blob/development/src/adapters/supabase/helpers/client.ts#L285) multiplier is fetched by username and organization name

P.S. Perhaps using organization id is better than organization name

**Comment by rndquu** [comment]
> @rndquu do you think it makes sense to also have repository specific multipliers? I can't think of realistic use cases for repository specific multipliers (per person) Ubiquity though.

I also don't see use cases for repository specific multipliers so let's keep it simple and tie multipliers to organizations instead of particular repositories.
