### ISSUE TITLE
Rename `/assign` to `/start`, `/unassign` to `/stop`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#419]
The intent for this command is to represent when the bounty hunter is actively working on the task, vs trying to just "reserve" the task.

The bounty hunters should only be working on a single task at a time. They should not be able to be "reserving" tasks and then neglecting to do them. 

Example: https://github.com/ubiquity/ubiquity-dollar/issues/616#issuecomment-1613354667

Renaming the command can provide a hint to the bounty hunter that they must actively work on the task when they use the command.

**Comment by rndquu** [comment]
This issue doesn't solve an initial problem when bounty hunters try to "reserve" the task

In the end it doesn't matter how they "reserve" it, via `assign` or `start`

But this issue does introduce:
- unnecessary refactor which will lead to more bugs
- code inconsistency where "assign" related functionality pertains to the `start` command

We could instead modify the `assign` behaviour. When a bounty hunter self assigns an issue then he **must** open a draft PR within an hour. If he doesn't open a PR within an hour then the bot unassigns the hunter.

**Comment by me505** [comment]
i agree with @rndquu

**Comment by pavlovcik** [comment]
> This issue doesn't solve an initial problem when bounty hunters try to "reserve" the task
> 
> 
> 
> In the end it doesn't matter how they "reserve" it, via `assign` or `start`
> 
> 
> 
> But this issue does introduce:
> 
> - unnecessary refactor which will lead to more bugs
> 
> - code inconsistency where "assign" related functionality pertains to the `start` command
> 
> 
> 
> We could instead modify the `assign` behaviour. When a bounty hunter self assigns an issue then he **must** open a draft PR within an hour. If he doesn't open a PR within an hour then the bot unassigns the hunter.

I still think the only way that tasks should be assigned is when a bounty hunter opens the draft pull request. 

Adding the logic you're proposing is obsolete with my simplified proposal. 

But yes this task is basically just a cosmetic change which is intended to affect user psychology more than anything else. I would consider it low priority compared to the other features and fixes.

**Comment by me505** [comment]
/wallet 0x5387ab162D3Fc48a8c9857517E36cF4B55dE8c1a
0x93d539d914cfd2c24d4f80e698d3f6730085bbe65b12a381c1f914af7f74e7c74e79023efb5d79722b13b437c3476b5ee88c32c1e66a83cb36329518c74b69231c

**Comment by pavlovcik** [comment]
Please review my late comment from the pull request because I believe that a comment from the bot doesn't actually explain how to unassign.

**Comment by 0xcodercrane** [comment]
solved the comment on the PR.
