### ISSUE TITLE
Update /help to explaing the new funtions of the multiplier comman

### ISSUE THREAD

**Issue by Draeieg** [ubiquity/ubiquibot#423]
after #376 you can give the bot a reason for a multiplier, however when calling the /help command no info on this feature or how to properly syntax the command is given 

<img width="647" alt="image" src="https://github.com/ubiquity/ubiquibot/assets/88983138/8ff41305-32d7-4710-b428-5cfdd27c3250">

**Comment by me505** [comment]
@pavlovcik havent i been assigned to four issues by now?

**Comment by pavlovcik** [comment]
> @pavlovcik havent i been assigned to four issues by now?

We have a feature that will allow you to continue to hunt new bounties if our review team is the bottleneck. Basically if the reviews are pending (or approved) then you can continue to work on another bounty while we figure out how to merge it in.
