### ISSUE TITLE
Consolidate DevPool Promotional Message

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#429]
- We should consolidate the promotional comment into the permit generation comments.
- Promotional message should be an `<h6>`

---

Permit generation skipped because assignee is `undefined`.

**Comment by PhantomCracker** [comment]
Hello @pavlovcik ,
Can you tell me which is the  promotional comment?
Do you mean this one? "Permit generation skipped because assignee is undefined."

**Comment by pavlovcik** [comment]
> ###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!

**Comment by PhantomCracker** [comment]
Hello @pavlovcik ,
Can you help with an example where I can see this message? Or what should I do to see this message? 
The fix should be ok, but I want to test it.
Thanks

**Comment by pavlovcik** [comment]
Yes it's the bottom half of the original comment/specification

**Comment by PhantomCracker** [comment]
@pavlovcik I see that this has been fixed here? https://github.com/ubiquibot/production/issues/23
I think it was a duplicate, but in the end it was solved
