### ISSUE TITLE
`value` should be dynamically parsed from the time value using the `ms` library

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#431]
- Parse `value` directly from the time label. 
  - Include the number, and include the unit (e.g. Hours, Days.)
  - Exclude the `<` symbol.
- Remove the `value` associated in the config. 
- Use `ms` library to derive the value at runtime from the time label based on the number and unit. 

> Value should be dynamically parsed from the time value using the `ms` library as we already discussed in the past @0xcodercrane

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1240675183_

**Comment by b4s36t4** [comment]
@pavlovcik is this up for grab?!

**Comment by b4s36t4** [comment]
@pavlovcik `ms` package doesn't have the capability to convert `1 Month` to millseconds? What should I do?!

**Comment by pavlovcik** [comment]
I have a hard time believing that but I can't make the time to verify that other than asking chatgpt

**Comment by b4s36t4** [comment]
<img width="620" alt="Screenshot 2023-07-07 at 2 53 30 AM" src="https://github.com/ubiquity/ubiquibot/assets/59088937/ea16407f-f993-46d3-a7e1-c7720a6d8d7d">

**Comment by b4s36t4** [comment]
Shall I go on and convert that to days and calculate it?

**Comment by b4s36t4** [comment]
@pavlovcik here are the test cases from vercel. even here no mention of `month` parsing. https://github.com/vercel/ms/blob/master/src/index.test.ts

**Comment by pavlovcik** [comment]
@wannacfuture you wanna pick this one up? You can use the linked pull request as reference.

**Comment by wannacfuture** [comment]
> @wannacfuture - Releasing the bounty back to dev pool because the allocated duration already ended! Last activity time: Sat Jun 24 2023 10:04:05 GMT+0000 (Coordinated Universal Time)


Currently the bot checks if there is hunter's comment or pull request(including reviews and comments on it) for last activity time check for an issue.
And when we assign bounty hunter manually there would be no comments or Prs of the hunter so the bot will identify as the allocated duration ended.


Well actually when we assigning bounty hunter manually the bot should add comment like : "@wannacfuture the time range for this issue.... ". And there will be no problem.
It used to do so, but I'm not sure why the bot hasn't added it.
Rfc, @pavlovcik , @rndquu

**Comment by wannacfuture** [comment]
> @wannacfuture The time limit for this bounty is on Thu, 10 Aug 2023 03:30:52 UTC

whoa? is it working now?

**Comment by pavlovcik** [comment]
Maybe it just needs to be reset with a couple reassigns. This seems to be a minor inconvenience but at least it seems consistent with what I've seen on other issues with expired timelines.

**Comment by wannacfuture** [comment]
Hmm, do we really need to use ms library? we can just use constant values for 1 day, month, hour or so, maybe.

what we need to do is just parsing the label. @pavlovcik

**Comment by pavlovcik** [comment]
> And when we assign bounty hunter manually there would be no comments or Prs of the hunter so the bot will identify as the allocated duration ended.

Why not check the time stamp of the assignment to the bounty hunter and include that in the last updates calculation?

**Comment by wannacfuture** [comment]
> Or are you suggesting to make a simple formula to multiply the number with a hardcoded duration for the unit of time? We would need to at least support: minutes, hours, days, weeks, and months probably.

Exactly.

**Comment by pavlovcik** [comment]
Isn't it easier to just use `ms`? Anyways I suppose both give similar results and I haven't done much thinking or research on this matter in a long time. You need to support singular and plural forms as well e.g. `hour` and `hours`

**Comment by wannacfuture** [comment]
hmmm, what do you think about this?
https://www.npmjs.com/package/@standards/duration
@pavlovcik

**Comment by wannacfuture** [comment]
according to @b4s36t4 's opinion, seems `ms` library doesn't work for months and years.

btw, I 'll prefer this.
https://www.npmjs.com/package/timestring

**Comment by pavlovcik** [comment]
> according to @b4s36t4 's opinion, seems `ms` library doesn't work for months and years.
> 
> btw, I 'll prefer this. https://www.npmjs.com/package/timestring

I think its okay, lets standardize times to be measured in smaller resolutions. I think it makes sense to only provide first party support for up to "weeks" because otherwise the partners should break down the tasks into several bounties. Alternatively they can just say `Time: 4 Weeks` etc.

**Comment by wannacfuture** [comment]
> Why do you believe that timestring is superior?

because timestring seems to have more capability to handle random strings.(including typos, spaces and so on)
and also it support months and years.
there will be several issues which can be decalared with `months`.

**Comment by 0xcodercrane** [comment]
If I add more comments about pros/cons of `ms` and `timestring` 

- `timesring` is less known than `ms` which means `ms` library is more robust right?
- In terms of complexity, `timestring` might be more complex to use in scenarios requiring customization, but ms can be advantageous for common use cases

I don't think we will have to use `month` and `year` in the near future, even if we have that case later, we can use smaller ones that `ms` support.

**Comment by wannacfuture** [comment]
gonna work this week.

**Comment by 0xcodercrane** [comment]
Random question for incentive URL design:

As a startup, I feel it would be better to post the detailed incentive items/values in the table as well as the claim URL for better analytics. we can also disable/enable the display format.

@pavlovcik @rndquu

**Comment by pavlovcik** [comment]
I think a debugging output to display exactly how the comment incentive was calculated: 

e.g. 

[ Claim 26.5 WXDAI ]
<details>

<code>
words: 55 @ 0.1
a: 3 @ 5
img: 1 @ 5
h1: 1 @ 1
</code>

</details>
