### ISSUE TITLE
Replace `/assign` with Opening Draft Pull Request

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#444]
I think it makes sense to only allow a bounty hunter to "call dibs" and assign themselves to a task when they open up a draft pull request. Reasoning below:

> > Bounty hunters will spend more time deducting how to self assign an issue via a draft PR compared to the straight /assign command.
>
> We currently have the capability for the bot to respond with the help/tutorial message whenever the user writes their first comment on any new repository. Within this tutorial message we can simply explain that in order to be assigned to the bounty now, they must open a draft pull request and associate it with the issue. 
>
> > most of the issues are assigned via the /assign command.
>
> The reason why I am not a fan of this approach is because I've seen a handful of instances where bounty hunters will reserve a task (disincentivizing anybody else from working on it) and then proceeding to not start on the task at all.
>
> If they have a pull request opened, they at least got started with the task which I anecdotally observed as having a higher completion rate.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/690#issuecomment-1607006170_

---

### 12 July 2023 Update

 I want to modify the specification actually to retain this feature if projects really want it, because it seems that some of us really like it (but I want to try an experiment without for a little while to measure performance differences.) 

- Let's make the default configuration option `assign-command: boolean` disabled for this
- If it is disabled, the help menu must be modified to state that the bot will automatically assign a user to an issue if they open up a draft pull request to that issue.
- If it is disabled, then leave the "open pr auto assign" capability (perhaps we can make a config for that in the future as well)

**Comment by wannacfuture** [comment]
Make sense. But how about this situation: 4 hunters open draft prs? assign whom?
And also, we need to think about this thing -> opening draft pr and doing nothing is same and /assign himself and doing nothing.

**Comment by pavlovcik** [comment]
> Make sense. But how about this situation: 4 hunters open draft prs? assign whom?

The chances of 2 hunters opening draft PRs in the same millisecond in the same repository is extremely unlikely. 

> opening draft pr and doing nothing is same as /assign himself and doing nothing.

> If they have a pull request opened, they at least got started with the task which I anecdotally observed as having a higher completion rate.

**Comment by wannacfuture** [comment]
@pavlovcik , Should we disable /assign command then?
only assign the bounty hunter when he opens a linked draft pull request?

**Comment by pavlovcik** [comment]
Yes let's disable it and see how it goes.

**Comment by wannacfuture** [comment]
Assigning bounty hunter when he opens a pr -> Seems this is already implemented.

https://github.com/ubiquity/ubiquibot/blob/48e006da17c46cc172263fe9a3924cd90a0f3bcb/src/handlers/assign/auto.ts#L7C1-L52C3

What we need to do is just disable /assign command.
What do you think?
@pavlovcik ?

**Comment by pavlovcik** [comment]
> Assigning bounty hunter when he opens a pr -> Seems this is already implemented.
> 
> https://github.com/ubiquity/ubiquibot/blob/48e006da17c46cc172263fe9a3924cd90a0f3bcb/src/handlers/assign/auto.ts#L7C1-L52C3
> 
> What we need to do is just disable /assign command. What do you think? @pavlovcik ?

I was thinking on this more during the weekend. I want to modify the specification actually to retain this feature if projects really want it, because it seems that some of us really like it (but I want to try an experiment without for a little while to measure performance differences.) 

- Let's make the default configuration option `assign-command: boolean` disabled for this
- If it is disabled, it must be removed from the bot help menu for that repository. 
- If it is disabled, then leave the "open pr auto assign" capability (perhaps we can make a config for that in the future as well)

Sounds good @wannacfuture ?

**Comment by wannacfuture** [comment]
Sounds great! @pavlovcik
