### ISSUE TITLE
Hotfix: Close Pull Request When `Unassigned`

### ISSUE THREAD

**Issue by Draeieg** [ubiquity/ubiquibot#448]
#379 is only working if the hunter unassignes himself using '/unassign' command as tested in [Staging](https://github.com/ubiquibot/staging/issues/38)

fix it so the bot closes the linked PR when unassigning the bounty hunter manually

**Comment by pavlovcik** [comment]
> @wannacfuture, You are not allowed to add hotfix

What is this feature? lol 

Do we have permissions set for every type of label? That's pretty funny.
