### ISSUE TITLE
Monospace Assign Table Font

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#467]
> <table>
>   <tr>
>     <td style="border:1px solid"></td>
>     <td style="border:1px solid"></td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Deadline</td>
>     <td style="border:1px solid">Mon, 03 Jul 2023 20:26:35 GMT</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Registered Wallet</td>
>     <td style="border:1px solid">0xb87d1713f2fade89fe9de557a2e37d10f006a5d1</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Payment Multiplier</td>
>     <td style="border:1px solid">2.00</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Multiplier Reason</td>
>     <td style="border:1px solid">testing </td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Total Bounty</td>
>     <td style="border:1px solid">25 USD</td>
>   </tr>
>   </table>

I just realized this was implemented with a mistake. It should all be in a monospace font.  

_Originally posted by @pavlovcik in https://github.com/ubiquibot/staging/issues/41#issuecomment-1621896888_

**Comment by EtherealGlow** [comment]
can i be assigned to this as @AnakinSkywalkeer has closed his pr and is over the deadline?

**Comment by AnakinSkywalkeer** [comment]
> can i be assigned to this as @AnakinSkywalkeer has closed his pr and is over the deadline?
> 
> 

Sure

**Comment by EtherealGlow** [comment]
thank you

**Comment by pavlovcik** [comment]
Oh sorry @aditygrg2 it looks like this was fixed as you can see in your assign comment. This should have been taken down as a bounty!

I can't do git blame from my phone easily but I'm curious who fixed it and didn't claim credit.

**Comment by pavlovcik** [comment]
I realized that you completed it. In the future please be mindful of conventional commits to pass CI. I'll give you credit since it's our fault for not closing this before you started.

**Comment by pavlovcik** [comment]
I can't see the permit generated on my phone. I have bad signal so if that's true another team member please help generate a permit here. @ubiquity/development

**Comment by aditygrg2** [comment]
Sure @pavlovcik Thank you!
