### ISSUE TITLE
Add config param to enable/disable wallet signature

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#468]
Depends on https://github.com/ubiquity/ubiquibot/issues/410

We have a [feature](https://github.com/ubiquity/ubiquibot/issues/410) of registering a wallet with a provided signature to ensure that bounty hunter has a private key (i.e. wallet address is not a CEX address) in order to claim a reward.

We should have the ability to enable/disable the "register wallet with signature" feature.

What should be done:
- Add a new bot's config property for enabling/disabling the "register wallet with verified signature" feature. The property should be `false` by default
- If the `register-wallet-with-verification` property is set to `true` then bounty hunters must be forced to register their wallets only with the provided signature ([example](https://github.com/ubiquity/ubiquibot/issues/410#issuecomment-1614202635))
- If the `register-wallet-with-verification` property is set to `false` then bounty hunters can register without a signature ([example](https://github.com/ubiquity/ubiquibot/issues/315#issuecomment-1577038350))

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/410#issuecomment-1621438825_

**Comment by web4er** [comment]
I am going to work on this. I think this is how the implementation would look. 

- addition of a new property of BotConfig = `{..., wallet: {register-wallet-with-verification: from env or false}}` in `src/bindings/config.ts`
- to change this config, admin can change `.env `option `register-wallet-with-verification = true`
- the BotOption is used in /wallet command processing. It also shows error messages based on this config.
- the BotOption is also used /help command to generate help according to config `register-wallet-with-verification`

Perhaps, I will rename `register-wallet-with-verification` to `REQUIRE_EOA_CONFIRMATION`

**Comment by pavlovcik** [comment]
I think the "register wallet" part is necessary to include for context so that the property name is self explanatory.

**Comment by web4er** [comment]
The price label wasn't applied to this issue. Would you add that? @pavlovcik
