### ISSUE TITLE
"These linked pull requests are closed" should only be commented if any are counted

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#474]
"These linked pull requests are closed" should only be commented if any are counted. I've seen in Draeieg's quality assurance examples it posting a comment like that without closing any. 

https://github.com/ubiquity/ubiquibot/blob/48e006da17c46cc172263fe9a3924cd90a0f3bcb/src/handlers/assign/action.ts#L78-L83

**Comment by wannacfuture** [comment]
@pavlovcik , its already fixed. Seems this issue is not needed.

Could you take a look at this?
[``](https://github.com/ubiquity/ubiquibot/blob/48e006da17c46cc172263fe9a3924cd90a0f3bcb/src/handlers/assign/action.ts#L76C1-L76C27)

Mentioned Draeieg 's QA example was the old one.

**Comment by pavlovcik** [comment]
Oh I see. So then I should never refer to the QA repository for proactively filing issues. Instead I should wait until it's in production. 

If you are sure that this solves the issue, we can credit the bounty hunter for their work and not merge. 

Can you please review their pull request and leave your feedback? Maybe they improved the implementation?
