### ISSUE TITLE
ubiquibot-qa[bot] intermittent hang

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#479]
For when bounty hunters fork the repository, we bundled in a GitHub actions runtime version of the bot, called ubiquibot-qa, that occasionally hangs on execution. 

GitHub actions runs for six hours, and has a max concurrent jobs limitation so after pushing a handful of commits, the bounty hunter is blocked from easily testing due to multiple jobs hanging for six hours. 

Investigate and debug the root cause of the issue for why the bot intermittently hangs.  

>> But now it is not responding to the commands after [web4er#11 (comment)](https://github.com/web4er/ubiquibot/issues/11#issuecomment-1623520409) and it has been 2 hours. @0xcodercrane

> That's wild. What could be causing the insane lag? Some instances seem to be able to run within a minute. Others timeout with the full 6 hours. We could consider setting a timeout on the action to be far shorter than the full 6 hours in order to let the latter instances run without queuing up. 

> @0xcodercrane @rndquu check how long some of these are taking to run: https://github.com/web4er/ubiquibot/actions

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/410#issuecomment-1624273792_

**Comment by whilefoo** [comment]
One thing I noticed when developing is that when the github action is run as a response to an event created by a user it hangs indefinitely but when its a bot event, it normally finishes executing

**Comment by rndquu** [comment]
> One thing I noticed when developing is that when the github action is run as a response to an event created by a user it hangs indefinitely but when its a bot event, it normally finishes executing

What is the "bot event"? I mean the QA bot workflow runs only as a response to an event created by a user and there is no other way to run it, right?

**Comment by whilefoo** [comment]
> What is the "bot event"?

By that I mean when the bot makes a comment, assigns a user, adds label...

**Comment by pavlovcik** [comment]
Thanks for sharing your observation @whilefoo  

If you can implement a solution then you can collect the reward!
