### ISSUE TITLE
Bounty Proposal:

### ISSUE THREAD

**Issue by b4s36t4** [ubiquity/ubiquibot#481]
### Describe the background or context

Filtering the issues which available to pick for bounty hunters.

### Describe the solution

Maybe having a `Available` Label once any user set Pricing Label. Right now we have a label `Unavailable` which will be added if issue is assigned to a bounty hunter. This way a bounty hunter won't be picking this. If we have a label `Available` this could make much sense stating that the issue is up for availability and also help hunters to filter out the issues which only available.

**Comment by devpanther** [comment]
You can just check if the issue has an assignee, easily filterable

**Comment by b4s36t4** [comment]
But there maybe multiple assignees.. Maybe they follow a different approach like One assignee for Issue review, one assignee for solution proposal etc. But having an Available Label could be the meaningful approach, I think.

**Comment by devpanther** [comment]
> But there maybe multiple assignees.. Maybe they follow a different approach like One assignee for Issue review, one assignee for solution proposal etc. But having an Available Label could be the meaningful approach, I think.

No, one assignee per issue.
