### ISSUE TITLE
Query User Information (Wallet Address, Multiplier)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#489]
I have been doing some manual payouts lately and realized that sometimes it's nice to be able to quickly identify a user's `multiplier` and `wallet` address without superuser access to the global bot database!

We should have a new command to view a user's settings. 

`/query @user`

Unless there is a better, more expressive command name than "query" 

---

> I'll need to send some xDAI to both participants because this was my fault for not ensuring that the bounty is valid. 

> https://gnosisscan.io/tx/0x3162608e9e18f71b4b29b0780904b664d160d0d79b0f761569f0d590b5f16044 @me505 
> https://gnosisscan.io/tx/0xbb9e74ab8951f5cc45fb38dd1d56f7e04e3c0ba6db98bfbaf58bfe63043d950a @AnakinSkywalkeer

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/562#issuecomment-1630854865_

**Comment by me505** [comment]
@pavlovcik can i be assigned to this as [this](https://github.com/ubiquity/ubiquibot/pull/528) has been approved

**Comment by pavlovcik** [comment]
https://github.com/ubiquity/ubiquibot/pull/563#issuecomment-1657219400

**Comment by pavlovcik** [comment]
https://github.com/ubiquity/ubiquibot/pull/563#issuecomment-1665058719
