### ISSUE TITLE
Automatic Assign Only on Draft and Normal Pull Request

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#491]
Looks like the bot automatically assigned this person because they closed pull requests opened towards it 
- https://github.com/ubiquity/ubiquibot/issues/13

**Comment by pavlovcik** [comment]
Why wasn't @b4s36t4 assigned or credited for this work?

**Comment by b4s36t4** [comment]
Maybe I already have 3 issues assigned to me?

**Comment by pavlovcik** [comment]
Hmm interesting. @wannacfuture can you verify if this is what happened by looking into the code?

**Comment by pavlovcik** [comment]
@b4s36t4 sorry there is a bug with our config I forgot we need to merge in right away. Please dont claim that yet!

**Comment by wannacfuture** [comment]
> Hmm interesting. @wannacfuture can you verify if this is what happened by looking into the code?

I'm thinking about this. 
![image](https://github.com/ubiquity/ubiquibot/assets/119157793/688ca4f3-693a-4bca-a64f-f7b1f1d71bfa)
on the above image, the issue says the hunter has linked PR.
But I'm not user why it is displayed as "mentioned".
![image](https://github.com/ubiquity/ubiquibot/assets/119157793/2a85ba13-9f49-4231-a6d8-c9792e99a9d7)
