### ISSUE TITLE
Refactor Config: `auto-pay-mode: true`➔`payment-permits-max-price: 1000` / ref

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#493]
I realize that we can substitute a `payment-permits: true` property using only the `payment-permits-max-price` property.

- Reference: https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1259820669

**Comment by EtherealGlow** [comment]
@0xcodercrane can you review this?
Thanks!

**Comment by EtherealGlow** [comment]
.
