### ISSUE TITLE
Refactor Config: `base-multiplier: 1000`➔`price-multiplier: 1` / ref

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#494]
I think It would make sense to refactor the [assistive bounty price calculation] math formula so that the configuration can be a single digit integer or float. The default should be `price-multiplier: 1`
- Reference: https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254082819

**Comment by PhantomCracker** [comment]
@pavlovcik  for this ticket should I wait for the https://github.com/ubiquity/ubiquibot/pull/383 to be merged or should I create a PR that points to that PR?
Thank you.

**Comment by pavlovcik** [comment]
Good question I'm not sure the best way to proceed but I think that pointing to that PR could work!

**Comment by PhantomCracker** [comment]
Here it is the pull request: https://github.com/Venoox/ubiquibot/pull/17

**Comment by me505** [comment]
@0xcodercrane there might be some problem with price calculation

**Comment by me505** [comment]
@pavlovcik theres some issue with payout

**Comment by me505** [comment]
by the looks of it price multiplier is 1.5 so it should have been 18.75 and not 12.5

**Comment by pavlovcik** [comment]
Looking into this.
