### ISSUE TITLE
Refactor Config: Automatically Derive `weight` / ref

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#495]
- Remove the `weight` property in the default config. 
- During runtime, when a bounty is being assistive priced by the bot, the bot should parse the number from the `Priority` label and use it in place of the `weight`
- Any words should be ignored from this parser, except for `Priority: ` of course, in order to understand that it is a priority label.
- Reference: https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228

**Comment by pavlovcik** [comment]
> /assign

We recently changed the command to `/start` @byteballet

**Comment by byteballet** [comment]
> > /assign
> 
> We recently changed the command to `/start` @byteballet

i forgot...

**Comment by byteballet** [comment]
I think there is a mistake in default weight of time-labels.

  "time-labels": [
    {
      "name": "Time: <1 Hour",
      "weight": 0.125,
      "value": 3600
    },
    {
      "name": "Time: <1 Day",
      "weight": 1,
      "value": 86400
    },
    {
      "name": "Time: <1 Week",
      "weight": 2,
      "value": 604800
    },
    {
      "name": "Time: <2 Weeks",
      "weight": 3,
      "value": 1209600
    },
    {
      "name": "Time: <1 Month",
      "weight": 4,
      "value": 2592000
    }
  ]
I believe weight of "Time: <1 Month" must be 5 as "Time: <3 weeks" should be 4.
@pavlovcik rfc

**Comment by pavlovcik** [comment]
I think I updated the time labels to lower values recently. Check out https://GitHub.com/ubiquity/.GitHub/ubiquibot-config.json for the new values. 
I think don't worry too much about those values for now.

**Comment by pavlovcik** [comment]
@wannacfuture any idea why this isnt generating a payment permit?

**Comment by wannacfuture** [comment]
no, it won't identify as meta issue. it checks checkbox

**Comment by pavlovcik** [comment]
lol the bot is totally bricked on this repo apparently.

**Comment by byteballet** [comment]
> 

It seems it's an issue related to database. https://github.com/ubiquity/ubiquibot/issues/574

**Comment by EtherealGlow** [comment]
how 💀

**Comment by byteballet** [comment]
> how 💀

My GH user name was ByteBallet and the wallet is assigned to ByteBallet on db. I changed my name to byteballet and it seems no wallet address was registered to byteballet before https://github.com/ubiquity/ubiquibot/issues/495#issuecomment-1702760081
Of course this is only guess since I can't access the db lol.

**Comment by wannacfuture** [comment]
> > how 💀
> 
> My GH user name was ByteBallet and the wallet is assigned to ByteBallet on db. I changed my name to byteballet and it seems no wallet address was registered to byteballet before [#495 (comment)](https://github.com/ubiquity/ubiquibot/issues/495#issuecomment-1702760081) Of course this is only guess since I can't access the db lol. It must be addressed and all the repos, orgs, or users must be managed by their id not name.

Well actually after you have changed your username, it won't be a problem.
Because there is no wallet address registered for your new name so that when the issue is closed the bot will ask to set your wallet address for your new username.

Does it make sense? @byteballet

**Comment by byteballet** [comment]
Yes, I got the point.
