### ISSUE TITLE
Refactor Config: `mdast` element keys as HTML entities  / ref

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#496]
- Use HTML tag names to unambiguously refer to the elements in a comment from the `comment-incentives` config.
- Reference: https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254113902

**Comment by pavlovcik** [comment]
1. I just reviewed the syntax on them fast readme. Theres still limitations with its implementation, in this context. Perhaps we will need more complex key names to encode all of this information, but how do you propose to refer to element `h2`? https://github.com/syntax-tree/mdast
2. `mdast` is now `remark`. It seems that we are using a deprecated project?

**Comment by rndquu** [comment]
> How do you propose to refer to element h2 in our config using mdast?

We could use the same [type](https://github.com/syntax-tree/mdast#heading) as `mdast` already use:
```
{
  type: 'heading',
  depth: 2,
  price: 100
}
```

> It seems that we should include `remark`?

`remark` is built on top of the [micromark](https://github.com/micromark/micromark) which we already use in the bot's [code](https://github.com/ubiquity/ubiquibot/blob/development/package.json#L54)

So this task is about moving from [mdast types](https://github.com/syntax-tree/mdast#types) to html types, right? In other words the incentive comments feature would work this way:
1. Get html nodes prices from the [config](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254113902)
2. Convert markdown to html
3. Calculate payouts based on the parsed html tags

**Comment by pavlovcik** [comment]
It seems like a hack to try and serialize a JSON object and use it as a key for the config property inside of a `.yml` file. 

It's better to just use the html entity as the key name. e.g. 

```yml
# comment incentives
h2: 1.0
li: 0.5
*: 0.1 # can wildcard be used to represent any word?
```

> * Get html nodes prices from the [config](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254113902)
> * Convert markdown to html
> * Calculate payouts based on the parsed html tags

Seems correct.

**Comment by rndquu** [comment]
The time label should be updated to at least `<1 Day` then

**Comment by whilefoo** [comment]
Github API can return comments in the [HTML form](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28#html-media-type-for-comment-body-properties) so I think it would be better to use that instead of using other tools for conversion?

**Comment by rndquu** [comment]
> Github API can return comments in the [HTML form](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28#html-media-type-for-comment-body-properties) so I think it would be better to use that instead of using other tools for conversion?

yes, it might be better

**Comment by rndquu** [comment]
> Is the scope of this issue also implementing incentive of comments in the PR related to the issue and reactions of the comments?

I don't think so. The scope for this issue is refactoring mdast element names to html tags in the bot's [config](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254113902) and making sure that nothing is broken. @pavlovcik pls confirm
