### ISSUE TITLE
Refactor Config: Simple Renames

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#497]
0. `analytics-mode: true`➔`disable-analytics: true` / [ref](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254075401)
0. `chain-id: 1`➔`evm-network-id: 1` / [ref](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254084562)
0. `max-concurrent-bounties: 2`➔`max-concurrent-assigns: 2` / [ref](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254088651)
0. `incentive-mode: false`➔`comment-incentives: true` / [ref](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254075947)

**Comment by me505** [comment]
@pavlovcik in the config `chain-id` is set to 1?

**Comment by pavlovcik** [comment]
> @pavlovcik why is `chain-id` set to 100 in the config?

Its so that we use Gnosis Chain by default, because Mainnet gas fees are cost prohibitive for small rewards.
