### ISSUE TITLE
Only display multiplier details if not `1.0`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#502]
It isn't useful information to show the bottom three table rows if the multiplier has never been changed. 

Hide the three rows when the user is assigned unless the multiplier details have been modified. 

- If the multiplier is not `1.0` then show the multiplier number, reason, and total. 
- If the multiplier is `1.0` and a reason is set, show all the multiplier details, but don't show the total. 

---

<code>

  <table>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Deadline</td>
    <td>Fri, 14 Jul 2023 09:05:02 GMT</td>
  </tr>
  <tr>
    <td>Registered Wallet</td>
    <td>0xA0B11F474d8ECE1205d38c66d5F2bE8917675d60</td>
  </tr>
  <tr>
    <td>Payment Multiplier</td>
    <td>1.00</td>
  </tr>
  <tr>
    <td>Multiplier Reason</td>
    <td>undefined</td>
  </tr>
  <tr>
    <td>Total Bounty</td>
    <td>450 USD</td>
  </tr>
  </table>
</code><h6>Tips:</h6>
    <ul>
    <li>Use <code>/wallet 0x4FDE...BA18</code> if you want to update your registered payment wallet address @user.</li>
    <li>Be sure to open a draft pull request as soon as possible to communicate updates on your progress.</li>
    <li>Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the bounty.</li>
    <ul>

_Originally posted by @ubiquibot in https://github.com/ubiquity/ubiquibot/issues/500#issuecomment-1633852489_

**Comment by web4er** [comment]
> /unassign

Oops, I was supposed to write this in my QA and not here. let's see what happens.
