### ISSUE TITLE
Create a github action to run the migrations automatically

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/ubiquibot#504]
### Describe the background or context

Whenever we create a new migration, it needs to be applied to the supabase. 
It's currently being done manually but the ideal solution is to run the migration in github action automatically.

### Describe the solution

- [ ] Add a new step in [build.yml](https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/build.yml) called Run migration.
- [ ] Create separate secrets for production/staging(main/development) and use them in the step.

**_NOTE_** You can refer the [README.md](https://github.com/ubiquity/ubiquibot/blob/development/supabase/README.md) how to run the migration

**Comment by pavlovcik** [comment]
I changed it to high because this will allow us to roll out updates faster. Can you verify the time is accurate?

**Comment by 0xcodercrane** [comment]
yeah time is fine to me

**Comment by 0xcodercrane** [comment]
@whilefoo would you let me know how to get an access token? That is different from supabase key right?

**Comment by whilefoo** [comment]
Yes it's different: https://supabase.com/dashboard/account/tokens
