### ISSUE TITLE
All capabilities off by default

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#505]
"TypeScript Approach" to DevPool Offering

TypeScript can be added to a project without enabling all the features. Makes it easier to ease into using it as a beginner. 

We should do the same with UbiquiBot and start with features/incentives disabled, and then let people discover and enable the cool features as they need them.

This is because we currently have a pretty heavy handed approach with how to run organizations which can make it less attractive vs adding the bot for a single "killer feature".

---

I wish that we could ask the user if they want to initialize a repository with the recommended default settings, or start from scratch. Otherwise we should create a "recommended default configuration" `.yml` that we have in our docs for partners to copy and add in.

---

Update: here's [a checklist](https://github.com/ubiquity/ubiquibot/issues/505#issuecomment-1636708093) for the bounty.

**Comment by pavlovcik** [comment]
@rndquu rfc

**Comment by rndquu** [comment]
We already have this default config implemented [here](https://github.com/ubiquity/ubiquibot/pull/383) (not merged yet) and `incentive-mode` is [disabled](https://github.com/ubiquity/ubiquibot/pull/383/files#diff-3dbd906a74e6e90c70b674f19ce3a371e7c77361c9de83dc8fdf9f02750caa8bR34) by default so I don't really understand what should done as a part of this issue in the https://github.com/ubiquity/ubiquibot repo.

We have the [onboarding](https://pay.ubq.fi/onboarding) page where most of the bot's config params are set to default. Perhaps we need to modify it so that partners could choose between the default bot params (as it works right now) and fully custom ones.

**Comment by pavlovcik** [comment]
> We already have this default config implemented https://github.com/ubiquity/ubiquibot/pull/383 (not merged yet) and incentive-mode is [disabled](https://github.com/ubiquity/ubiquibot/pull/383/files#diff-3dbd906a74e6e90c70b674f19ce3a371e7c77361c9de83dc8fdf9f02750caa8bR34) by default so I don't really understand what should done as a part of this issue in the https://github.com/ubiquity/ubiquibot repo.

One example I can think of would be to disable the assistive pricing capability, or the bot editing any labels at all (like when a new repository is initialized, the bot will add all the `Priority` and `Time` labels. These capabilities should also be possible to disable, so that the bot doesn't make any changes to the repository/workspace unless the features are enabled.

**Comment by rndquu** [comment]
So as a part of this issue a bounty hunter should add new bot config params:
1. Whether assistive pricing (automatically adding the `Time` and `Priority` labels to the repository when the repository is initialized) is enabled
2. A separate config param for each of the supported [commands](https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/comment/commands.ts) whether the command is enabled

All of the newly added config params should be enabled by default

We have a similar [issue](https://github.com/ubiquity/ubiquibot/issues/396) for disabling all of the bot's capabilities. I guess this one https://github.com/ubiquity/ubiquibot/issues/396 can be closed on favor of the current issue

**Comment by devpanther** [comment]
@pavlovcik @rndquu all these will be in the ubiquity config yml file right?

**Comment by pavlovcik** [comment]
> @pavlovcik @rndquu all these will be in the ubiquity config yml file right?

Yes bot settings should all be configurable via the `yml` file.

**Comment by devpanther** [comment]
> > @pavlovcik @rndquu all these will be in the ubiquity config yml file right?
> 
> Yes bot settings should all be configurable via the `yml` file.

Okay, got that in the PR
