### ISSUE TITLE
Self config syntax

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#513]
I was giving a live presentation of the bot the other day. I was distracted pitching the concept and in a rush, so I couldn't figure out what the issue was for why I couldn't change my `/multiplier` 

---

Any commands that admins can use to configure other contributor settings, like the multiplier, the syntax we already established makes sense (`/multiplier @pavlovcik 1`). 

However, for self config I think it's intuitive to assume they are referring to themselves unless they include a user handle. This is because some other commands in our system behave with this assumption, of referring to oneself, such as `/assign`

- Enable support for `/multiplier 1` to refer to self.  
- Check all the other similar syntax commands to also include this support.
- These changes should automatically handle this edge case as well, with the unexpected success message:

              Successfully changed the payout multiplier for @ to 0. The reason is not provided.

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquibot/production/issues/25#issuecomment-1635468126_

**Comment by pavlovcik** [comment]
This payout seems messed up for several reasons:

1. Why is the payout on mainnet?
2. The bot added another label afterwards to change the price

@0xcodercrane let's fix

**Comment by me505** [comment]
is the payment ready yet @pavlovcik?

**Comment by pavlovcik** [comment]
Thanks for the reminder let me work on this in a few minutes.
