### ISSUE TITLE
Add empty private key error

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#523]
Right now if the `private-key-encrypted` param in the bot's config is not set then the bot shows this [error](https://github.com/ubiquibot/production/issues/25#issuecomment-1636710420) which is really misleading.

It happens because [here](https://github.com/ubiquity/ubiquibot/blob/development/src/bindings/config.ts#L78) the `autoPayMode` is set to `false` if there is no private key hence the error `Permit generation skipped since autoPayMode is disabled`. The error text should be similar to `Permit generation skipped because wallet private key is not set`.

What should be done:
1. Remove this [check](https://github.com/ubiquity/ubiquibot/blob/development/src/bindings/config.ts#L77)
2. [Here](https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/payout/action.ts) add an additional check for an empty private key which shows an appropriate error message in case the private key is not set.

**Comment by Sadaf-A** [comment]
@rndquu this is my first time contributing here can you please explain how the wallet works?

**Comment by wannacfuture** [comment]
Why haven't price label generated for this issue?

**Comment by rndquu** [comment]
> @rndquu this is my first time contributing here can you please explain how the wallet works?

1. You register your wallet via posting a special comment ([example](https://github.com/ubiquity/ubiquibot/issues/511#issuecomment-1652707259))
2. You complete an issue
3. You get a payout ([example](https://github.com/ubiquity/ubiquibot/issues/546#issuecomment-1663897627)) redeemable only by your registered wallet address on step 1

**Comment by Sadaf-A** [comment]
@pavlovcik I Made the QA but I'm not sure what set of commands I should run or how I can set the private key to be empty can you help me out with that?

**Comment by Sadaf-A** [comment]
@whilefoo I had a question what happens if I haven't set a wallet?

**Comment by pavlovcik** [comment]
> @pavlovcik I Made the QA but I'm not sure what set of commands I should run or how I can set the private key to be empty can you help me out with that?

Not sure but here's my best guess. In your organization make a config like this (its private so just make a config there)  `https://github.com/ubiquity/ubiquibot-config/blob/development/.github/ubiquibot-config.yml`

Add a property called

```yml
private-key-encrypted: ""
```

@rndquu please confirm that's correct.

**Comment by rndquu** [comment]
> @pavlovcik I Made the QA but I'm not sure what set of commands I should run or how I can set the private key to be empty can you help me out with that?

1. Create a new organization wide yml config ([example](https://github.com/rndquu-org/ubiquibot-config/blob/main/.github/ubiquibot-config.yml))
2. Open https://pay.ubq.fi/keygen and generate a new X25519 public/private key pair
3. Encrypt your wallet's private key with the X25519 public key generated on step 2
4. Set the encrypted wallet in the bot's config in the `private-key-encrypted` property
5. Setup X25519 private key in the bot's env variables

This way the bot will be able to generate payment permits. You could also leave the `private-key-encrypted` property empty in case you're building something not connected with payouts.
