### ISSUE TITLE
Make Error Messages Helpful

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#524]
Every error message should explain the syntax of the command and provide an example. 

              Invalid body for allow command

_Originally posted by @ubiquibot-dev[bot] in https://github.com/ubiquibot/staging/issues/61#issuecomment-1637578873_

**Comment by me505** [comment]
why does this have 2 priorities

**Comment by me505** [comment]
@pavlovcik there are 2 priorities normal and high which totals the bounties to 56.25 and 18.75 respectively

**Comment by me505** [comment]
same situation on another one of my issues

**Comment by pavlovcik** [comment]
There is an auto-labeling issue we are sorting out now on the bot sorry about that!

**Comment by me505** [comment]
???
