### ISSUE TITLE
bug: `/unassign` is broken

### ISSUE THREAD

**Issue by web4er** [ubiquity/ubiquibot#533]
After some recent merges, the `/unassign` command appears to have been broken. It prints an error when you comment it. 

> Error: TypeError: (0 , __1.closePullRequestForAnIssue) is not a function

Here is a go-through showing you how it is behaving right now.  https://github.com/web4er/ubiquibot/issues/37

**Comment by Draeieg** [comment]
<img width="650" alt="image" src="https://github.com/ubiquity/ubiquibot/assets/88983138/7b5a863e-bf20-449b-b868-cfbe9897140e">
its working fine in our production and staging enviroments, seems like a local issue

it would be good to investigate anyway just in case

**Comment by web4er** [comment]
I have just tested it with the QA bot. It has the same problem with the unassign. Here, you can see it https://github.com/web4er/ubiquibot/issues/23#issuecomment-1640903443 @Draeieg

**Comment by wannacfuture** [comment]
Please make sure that you have updated the dev branch and also rebased it.

**Comment by web4er** [comment]
> Please make sure that you have updated the dev branch and also rebased it.

Yes. I performed the test yesterday with the latest development branch pushed to my fork's development branch without extra changes. 

Now I have performed the test again with the latest development branch pushed to my fork's development branch without extra changes as there are new merges today. This is happening at commit https://github.com/ubiquity/ubiquibot/commit/d0ed9cf4fdb514c6cefcca9e446c7ae56cbcac4d The bot response is the same with the error. Here https://github.com/web4er/ubiquibot/issues/23#issuecomment-1641763551 you can see responses of both my local bot and UbiquiBot[qa]  However, the UbiquiBot[qa]  workflow is also failing because of some supabase issue.

**Comment by molecula451** [comment]
It's reproducible. This is indeed an issue on the latest branch

![un](https://github.com/ubiquity/ubiquibot/assets/41552663/c01c2486-ce3c-4c2d-8be0-0f05f55d7523)

**Comment by wannacfuture** [comment]
cool, seems `auto-assigning hunter when opening pr` works well.

**Comment by pavlovcik** [comment]
Thanks for filing the issue @web4er! 

https://gnosisscan.io/tx/0x5c43352e48f55167970b7db2e1ab928f21725a76f05e7142ece04b910ad543fe
