### ISSUE TITLE
Save permits to DB

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#546]
Original [comment](https://github.com/ubiquity/pay.ubq.fi/issues/101#issuecomment-1640038112)

We need to save permit URLs(permit URL [example](https://github.com/ubiquity/ubiquibot/issues/537#issuecomment-1640820945)) data to a DB.

What data should be stored:
- organization id
- repository id
- issue id
- network id
- bounty hunter id
- token address
- payout amount
- nonce
- deadline
- bounty hunter address
- wallet's owner address
- signature

**Comment by whilefoo** [comment]
@pavlovcik priority label is missing
