### ISSUE TITLE
Set up supabase policies

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#547]
Depends on https://github.com/ubiquity/ubiquibot/issues/546

We have [plans](https://github.com/ubiquity/pay.ubq.fi/issues/110) for reading permit URLs from supabase DB instead of parsing github comments.

We're going to hardcode supabase API key in the frontend code so we need to restrict access to most of the supabase tables. In other words we should setup [supabase policies](https://supabase.com/docs/guides/auth/row-level-security) in the way so that the hardcoded supabase API key could **only** read from the permit URLs table **without access** to all other tables.

**Comment by pavlovcik** [comment]
Shouldn't this be a one hour task?

**Comment by rndquu** [comment]
> Shouldn't this be a one hour task?

Ideally it should be `<4 hours` task

**Comment by pavlovcik** [comment]
Okay a rough workaround for pricing then.

**Comment by devpanther** [comment]
> Okay a rough workaround for pricing then.

While I'm waiting for my PR's QA, can I get on this @pavlovcik?.. i think I hit max

**Comment by devpanther** [comment]
While I'm waiting for my PR's QA, can I get on this @pavlovcik?.. i think I hit my max

**Comment by seprintour** [comment]
Ready for review

**Comment by aditygrg2** [comment]
/wallet 0xB951653877b7D6c9AB26bf5E7f30708fC76f53E0 0x081e8d678650bbc0a13827affe0ebf6049b186105b6726a5a3bf8e51704f9ba37c397589737b03b39a953ed8f9c436146e650db3d229ee6369b00bd2ed7c4bc81c

**Comment by 0xcodercrane** [comment]
Sorry to jump into the issue lately, but I couldn't agree to expose the API key to the frontend code because of security regardless of the security policy they support.

Ideally we should have that endpoints in ubiquibot itself without exposing any key information.

How is it possible? The ubiquibot is kind of a serverless function. Right now it has been designed to receive all requests but verify before receiving. In the verification step, it checks necessary security params.
For permit URL endpoints, we can bypass the verification step. 

@rndquu

**Comment by pavlovcik** [comment]
> but I couldn't agree to expose the API key to the frontend code because of security regardless of the security policy they support.

Well I didn't do any updated research on this, but last I looked into it, Supabase created "anonymous keys" specifically for this reason. Basically if you have a client web app, and need to access certain data in the database, I suppose its convenient to embed the key directly in the client, making it public.

**Comment by seprintour** [comment]
> Sorry to jump into the issue lately, but I couldn't agree to expose the API key to the frontend code because of security regardless of the security policy they support.

There's a public and secret key, once we setup the RLS.. we do not have any issues with security as that was what it was made for by Supabase

**Comment by rndquu** [comment]
> Sorry to jump into the issue lately, but I couldn't agree to expose the API key to the frontend code because of security regardless of the security policy they support.
> 
> Ideally we should have that endpoints in ubiquibot itself without exposing any key information.
> 
> How is it possible? The ubiquibot is kind of a serverless function. Right now it has been designed to receive all requests but verify before receiving. In the verification step, it checks necessary security params. For permit URL endpoints, we can bypass the verification step.
> 
> @rndquu

From the [docs](https://supabase.com/docs/learn/auth-deep-dive/auth-row-level-security#securing-your-tables):
"""
This raises an interesting question however: "if my anon key is in the client, then can't someone read my javascript and steal my key?", the answer is yes. And this is where Postgres policies come in.

Using Postgres's "Row-Level-Security" policies, we can set rules on what data the anon key is allowed or not allowed to access by default.

We can say for example that the anon key should only be able to read from a particular table, but not write, update, nor delete.
"""

So [supabase's RLS](https://supabase.com/docs/guides/auth/row-level-security) was made specifically to expose API keys. Anyway @whilefoo [says](https://github.com/ubiquity/ubiquibot/pull/578#pullrequestreview-1561639584) that has tested the corresponding [PR](https://github.com/ubiquity/ubiquibot/pull/578). 

Expected behavior:
- anybody **can** read from the `permits` table
- anybody **can not** modify the `permits` table

@whilefoo Does it work this way?

**Comment by whilefoo** [comment]
> Expected behavior:
> 
> * anybody **can** read from the `permits` table
> * anybody **can not** modify the `permits` table

I found this to be true in my testing.

If the RLS is enabled, every action (read, write, modify, delete) is forbidden by default, then you can add policies that allow certain actions.

**Comment by 0xcodercrane** [comment]
ok lets give it a try
