### ISSUE TITLE
Robust Bot Permit Comment Recognition

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#551]
We should parse the permit generation comments using `URLSearchParams` because we may add more URL search parameters to the URL in the future. Also the current approach is strict on the ordering of the parameters which seems brittle.

> Yes, parsing the URL with `URLSearchParams` is a better approach

> This PR solves the original issue + we don't have plans of adding more query params besides `claim` and `network` so I don't think that refactoring to `URLSearchParams` is an urgent issue

>> Besides, isn't it supposed to be `https://pay.ubq.fi/?claim=`

> No, the generated URL is `https://pay.ubq.fi?claim=` so everything is fine

_Originally posted by @rndquu in https://github.com/ubiquity/ubiquibot/pull/508#discussion_r1265066358_

**Comment by rndquu** [comment]
Duplicate https://github.com/ubiquity/ubiquibot/issues/526
