### ISSUE TITLE
Twitter Bot Account

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#56]
Related to ubiquity/devpool#477

Create a Twitter bot to receive the messages from the twitter bot interface to post on twitter on the twitter.com/ubiquitydevpool account

**Comment by ManyRios** [comment]
I can help with this one too

**Comment by sergfeldman** [comment]
> I can help with this one too and many others

@ManyRios Thank you!

@pavlovcik @0xcodercrane do you have any concerns?

**Comment by pavlovcik** [comment]
I'll assign this to you as long as you acknowledge that we can only pay out when testing is successful. So when #55 is done, you need to give us the keys for the Twitter bot you made. Once a tweet is programmatically sent, then we can disperse funds for both bounties.

**Comment by ManyRios** [comment]
> I'll assign this to you as long as you acknowledge that we can only pay out when testing is successful. So when #55 is done, you need to give us the keys for the Twitter bot you made. Once a tweet is programmatically sent, then we can disperse funds for both bounties.
> 
> I think it makes sense for you to take both #55 and this one together. We can let somebody else handle the Telegram bot and adapter tasks at the same time.

Got it.... I'll take both

**Comment by ManyRios** [comment]
I'll be waiting for a feedback regarding this https://github.com/ubiquity/bounty-bot/pull/65

**Comment by ManyRios** [comment]
Here's my wallet address 0x4311d06edbb35a6ae0f41d3942a0707c3f187494

**Comment by ManyRios** [comment]
does it seem to get here? after several attempts to communicate with @pavlovcik. please let me know if I need to delete my pull request

**Comment by pavlovcik** [comment]
Moved to https://github.com/ubiquity/devpool-directory-bounties/issues/1

---

> Related to ubiquity/devpool#477

Interesting that GitHub modifies the comment body to track repository renames @rndquu 

> https://github.com/ubiquity/devpool-directory/issues/477

Was deleted so the reference is destroyed. Perhaps in the future you should consider transferring issues instead of deleting.
