### ISSUE TITLE
Use Github IDs instead of names in DB

### ISSUE THREAD

**Issue by whilefoo** [ubiquity/ubiquibot#574]
Currently user, repository, organization are all stored by their name in the database. User, repo or organization can change their name and I guess this is not that common but I still think it would be better to store IDs that we get from the Github API instead of names. 

---

- [ ] Store and use user ID. 
- [ ] Store and save username. 
- [ ] Ensure that user name is updated every time user ID is accessed, in case a username is updated.

**Comment by pavlovcik** [comment]
I agree that ID makes more sense for this reason.

**Comment by Sadaf-A** [comment]
@pavlovcik Hey, I wanted to pick this up!

**Comment by Sadaf-A** [comment]
@whilefoo could you please elaborate a little and if possible, link the GitHub file also.

**Comment by whilefoo** [comment]
@pavlovcik I'm not sure how we can keep backwards compatibility. For issues and users it doesn't matter that much because we just insert them into DB and never query them, but we query other tables so things won't work because old records won't have IDs. 

I guess one way would be to first add IDs to the database and fill new records with both name and ID but still query by name. Then we create a script that will update all missing IDs and once we have everything we switch to querying by ID.

**Comment by pavlovcik** [comment]
Yeah I think we could even delete the old users to force re-registration. No big deal.

**Comment by Wholesomebruh** [comment]
@pavlovcik , here it is required to a "id" along with other details, right? Any additional changes? Thank You

**Comment by pavlovcik** [comment]
> @pavlovcik , here it is required to a "id" along with other details, right? Any additional changes? Thank You

I think all the relevant context is inside of this conversation but @whilefoo any remarks?

**Comment by pavlovcik** [comment]
My remarks

https://github.com/ubiquity/ubiquibot/issues/623

**Comment by byteballet** [comment]
> I agree that ID makes more sense for this reason. For convenience we should still also keep at least the original username.

Would it be good to store both name and id for repo and user or only id?

**Comment by whilefoo** [comment]
> Would it be good to store both name and id for repo and user or only id?

Yes, I think both is good

**Comment by byteballet** [comment]
> Is it straightforward to update the name if a change is detected?


I don't think it's straightforward but it's absolutely doable. I am not sure if it will be still needed to add id when the name is updated whenever a change is detected.

**Comment by whilefoo** [comment]
> I don't think it's straightforward but it's absolutely doable.

How would you detect name change without storing ID? The only option I see is when the user comments we get his ID and username and then we can check in the database if user with this ID still has the same username otherwise we update it.

**Comment by byteballet** [comment]
> 
> How would you detect name change without storing ID? The only option I see is when the user comments we get his ID and username and then we can check in the database if user with this ID still has the same username otherwise we update it.

What is login in UserSchema?

**Comment by byteballet** [comment]
Waiting for review.
https://github.com/ubiquity/ubiquibot/pull/656

**Comment by byteballet** [comment]
Still waiting for review.

**Comment by byteballet** [comment]
> Still waiting for review.

Want to move to another issue because it's been a while for waiting for review...
/stop
