### ISSUE TITLE
`time-labels` config auto generation

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#584]
The `time-labels` config should be automatically calculated using the `ms` library. Partners shouldn't need to override the time labels and insert into the config. 

```typescript
{
  "time-labels": [
    {
      "name": "Time: <1 Hour",
      "weight": 0.125,
      "value": 3600
    },
    {
      "name": "Time: <1 Day",
      "weight": 1,
      "value": 86400
    },
    {
      "name": "Time: <1 Week",
      "weight": 2,
      "value": 604800
    },
    {
      "name": "Time: <2 Weeks",
      "weight": 3,
      "value": 1209600
    },
    {
      "name": "Time: <1 Month",
      "weight": 4,
      "value": 2592000
    }
  ],
}
```

https://github.com/ubiquity/ubiquibot/pull/558/files#diff-6863b0d0a0dcd10927da34fbf604b6226c24c1b204008d06f10b20da8d85c5d3R5-R31

**Comment by devpanther** [comment]
> Partners shouldn't need to override the time labels and insert into the config.

I think that's the default config you linked to, I think the overrides takes place in the yml file.

Do you mean, it should not be hardcoded there but rather generated on install

**Comment by pavlovcik** [comment]
I think that we shouldn't need to override in any default settings anywhere. Instead, I feel that the bot should just understand `Time` labels and their values based on what `ms` library returns.

**Comment by devpanther** [comment]
> I feel that the bot should just understand `Time` labels and their values based on what `ms` library returns.

So basically labels can be custom (added to issues) and it'd just automatically turn the 1.5 Week for example to ms and calculate the amount

And we should remove time-labels from config

**Comment by pavlovcik** [comment]
I also want to dock time from the larger resolutions for inefficiencies. I have data to back that most people work at most 75% efficiency:

- Hours = No change
- Days = 6 Hours
- Weeks = 30 Hours
- Months = 120 Hours

**Comment by devpanther** [comment]
@pavlovcik Auto-generation of Time labels will be disabled right? Since we no longer have strictly default time labels

**Comment by pavlovcik** [comment]
I just realized that this is the only way for the bot to know what labels to automatically populate @devpanther so this task actually is invalid. 

Why don't you handle this new issue instead? 
- https://github.com/ubiquity/ubiquibot/issues/595
