### ISSUE TITLE
Invalid syntax for query command

### ISSUE THREAD

**Issue by gitcoindev** [ubiquity/ubiquibot#590]
### Describe the background or context

I experimented today with the 'query' command after enabling in my fork always received 

`Invalid syntax for query command` error, see https://github.com/gitcoindev/ubiquibot/pull/3

I was able to run this command only because I analysed the regex in https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/comment/handlers/query.ts

By default GitHub adds an empty space after username after typing @username and this is rejected as the regex does not allow any white space after user name.

### Describe the solution

Proposal to fix this: Update the regex to allow to add an optional empty white space after user name.

**Comment by pavlovcik** [comment]
> By default GitHub adds an empty space after username after typing @username and this is rejected as the regex does not allow any white space after user name.

Interesting observation. 

> Proposal to fix this: Update the regex to allow to add an optional empty white space after user name.

What if we use `String.trim()` instead?

@web4er @whilefoo I remember somebody recently highlighted a space related issue to one of the commands recently. Was this related?

**Comment by gitcoindev** [comment]
@pavlovcik yes string.trim() or `^\/query\s@(\w+)\s?$` should work. The latter solution accepts an optional white space after user name.

**Comment by pavlovcik** [comment]
Why do you want to keep the white space? It seems like useless information to save in the database.

**Comment by gitcoindev** [comment]
the second solution is just the regex, so it would still be able to parse any db entries with an additional white space.

but if old entries can be discarded I would use trim().

**Comment by pavlovcik** [comment]
> but if old entries can be discarded I would use trim().

We would need to be mindful to update all the old entries (or drop them) when this solution is merged in probably?

**Comment by web4er** [comment]
> @web4er I remember somebody recently highlighted a space related issue to one of the commands recently. Was this related?

That white space was probably for a different purpose, but the concern is same. The database should not have something unexpected.
