### ISSUE TITLE
Bounty Proposal: Incentivizing pull request reviewers

### ISSUE THREAD

**Issue by gitcoindev** [ubiquity/ubiquibot#591]
### Describe the background or context

As I am playing with the bot I thought of a possible optional feature - payouts for the reviewer.

If configured for a project, a reviewer could get additional funds when the pull request is merged.

Rationale: PR reviewers spend their time and expertise to guide through the code review, why not to reward them when the PR is successfully merged as well? 

### Describe the solution

If the PR reviewer has wallet address configured, he could receive an additional funding .e.g . 10% on top of the bounty for his efforts after the pull request is merged.

This feature would be optional and disabled by default.

**Comment by pavlovcik** [comment]
Duplicate #311
