### ISSUE TITLE
We should save all of our logs to Supabase.

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#592]
- Every log should associate a comment (or event handler) ID. 
- Using the IDs we should aim to be able to backtrace the exact conversation/context from the GitHub conversation.
- Clean up all the old code related to mezmo as that will be deprecated after this implementation. 
- If there is no GitHub mutation associated with the logging activity (a comment on GitHub) then there is no way to link back a "node id" in which case, the "node id" can be null.

**Comment by pavlovcik** [comment]
@byteballet you seemed interested in taking this on.

**Comment by ByteBallet** [comment]
Yes, @pavlovcik 
But I am on preventing_duplicate issue.
If possible, I would like to work on this issue after preventing_duplicate issue.

**Comment by pavlovcik** [comment]
The best I can suggest is that you are allowed to be assigned to two issues at once (more if you have an open pull request review and the delay is caused by our review team.) 

However, our task management system is first-come-first-serve.

**Comment by ByteBallet** [comment]
This is just off-topic but do you have any full-time employees?

**Comment by pavlovcik** [comment]
Perhaps I'll put 1 day. I feel like this is a half day project.

**Comment by ByteBallet** [comment]
@pavlovcik , I think I have some misunderstanding.

export const updateLastWeeklyTime = async (time: number): Promise<void> => {
 const logger = getLogger();
 const { supabase } = getAdapters();
 const { data, error } = await supabase.from("weekly").update({ last_time: time });
 logger.info(`Updating last time is done, data: ${data}, error: ${error}`);
 return;
};

In this function, what ID should be associated?

**Comment by pavlovcik** [comment]
That is a good question. I am unsure! My best guess is that if there is no GitHub mutation associated with the logging activity, then there is no way to link back a "node id" in which case, the "node id" can be null.

**Comment by devpanther** [comment]
> * Using the IDs we should aim to be able to backtrace the exact conversation/context from the GitHub conversation.

I think we'd need to attach `repo`, `org` and `node id` together or get the organization and repo id along with the node id

That way we can easily backtrace logs to exact comments, if its not a comment.. then it can just be the org id and repo id it repo name and org name

**Comment by pavlovcik** [comment]
Should we run a supabase cron job to drop logs that are over a week old?

This will help save on storage costs and I'm not sure if we will need to review old logs while we are still actively in development. 

@0xcodercrane

**Comment by 0xcodercrane** [comment]
That's a good question actually they will charge us once we reach to the limit. 
we can use `pg_cron` extension that the supabase platform originally supports.
