### ISSUE TITLE
We should have a simple webapp to stream realtime logs from the database

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#593]
- We must read the logs from the Supabase and display them on a simple and public web app. 
  - Create a directory for the logs web app, and deploy to Cloudflare Pages via Github Actions.
- Ideally, the logs should stream realtime with a web socket.

**Comment by whilefoo** [comment]
We can't host static page with netlify functions like ubiquibot, but we can create a directory in this repo for the logs web app and deploy to Cloudflare Pages with Github Actions.

For streaming logs we can use Supabase's [Realtime](https://supabase.com/docs/guides/realtime/postgres-changes) feature, which streams all changes on a particular table, it only needs Supabase JS client library.

**Comment by devpanther** [comment]
#604 is almost done, I'm going to get on this

**Comment by devpanther** [comment]
In progress #649

**Comment by pavlovcik** [comment]
Not sure if this is considered as an error in the database or the viewing app but @devpanther please check

<img width="540" alt="image" src="https://github.com/ubiquity/ubiquibot/assets/4975670/9ca949fc-5993-4e6b-bff5-5d846242f5e6">

**Comment by whilefoo** [comment]
> Not sure if this is considered as an error in the database or the viewing app but @devpanther please check `[object Object]`

This is database error from analytics, it will be fixed by #621

**Comment by pavlovcik** [comment]
@0xcodercrane I can't find access to this on our deployment https://ubiquibot-production.netlify.app/log-app

**Comment by whilefoo** [comment]
> @0xcodercrane I can't find access to this on our deployment https://ubiquibot-production.netlify.app/log-app/index.html

Because [github action](https://github.com/ubiquity/ubiquibot/actions/runs/5987054814/job/16240849745) is failing

**Comment by pavlovcik** [comment]
You think you can handle that one @whilefoo ?

**Comment by whilefoo** [comment]
`CLOUDFLARE_PROJECT_NAME` secret is missing. is the Pages project created on Cloudflare? I need the name for it

**Comment by pavlovcik** [comment]
I see that now. @rndquu set this up in a dynamic way so we shouldnt be doing this. @rndquu do you think you can rectify this?

**Comment by whilefoo** [comment]
I guess we could use [the reusable workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml) because it creates a project if it doesn't exist, but it uses repo name as the project name, but we could change that it can be overridden by an input variable

**Comment by pavlovcik** [comment]
Why didn't we make this a seperate repo and/or git submodule?

**Comment by rndquu** [comment]
Perhaps it is better to move the [log app](https://github.com/ubiquity/ubiquibot/tree/development/log-app) to a separate repo?

Then we could:
1. Refactor this [code](https://github.com/ubiquity/ubiquibot/blob/development/log-app/scripts/constants/index.ts) to read supabase values from cloudflare pages environment variables
2. Add the "cloudflare pages deploy" [workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml) to the log app repo

This way we end up with the log app both for staging and production

@0xcodercrane @whilefoo What do you think?

**Comment by 0xcodercrane** [comment]
I agree

**Comment by whilefoo** [comment]
I agree to move it to another repo.



> 1. Refactor this [code](https://github.com/ubiquity/ubiquibot/blob/development/log-app/scripts/constants/index.ts) to read supabase values from cloudflare pages environment variables

How would you achieve this? It seems Cloudflare only supports [env variables at build time](https://developers.cloudflare.com/pages/platform/build-configuration/) for frameworks, but we don't have a framework so we have to use a [esbuild plugin](https://github.com/rw3iss/esbuild-envfile-plugin)

**Comment by devpanther** [comment]
> we don't have a framework so we have to use a esbuild plugin

Or maybe we can just use the cloudflare env, since it only allows it to be accessed from the workers.

We'd create an handler to retrieve the env and return it on the frontend

**Comment by rndquu** [comment]
> I agree to move it to another repo.
> 
> > 1. Refactor this [code](https://github.com/ubiquity/ubiquibot/blob/development/log-app/scripts/constants/index.ts) to read supabase values from cloudflare pages environment variables
> 
> How would you achieve this? It seems Cloudflare only supports [env variables at build time](https://developers.cloudflare.com/pages/platform/build-configuration/) for frameworks, but we don't have a framework so we have to use a [esbuild plugin](https://github.com/rw3iss/esbuild-envfile-plugin)

Yes, you're right, then we should find some other way to pass env variables to the logs app.

Meanwhile there is an issue for moving the log app to a separate repo https://github.com/ubiquity/ubiquibot/issues/712
