### ISSUE TITLE
Proposal: Disabled Capabilities by Default II 

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#599]
I think we should enable all commands by default. However I would like to hear why this could be a bad idea before turning this into an official task.

>> Skipping `/multiplier` because it is disabled on this repo

> I wonder if it makes sense to enable all of the slash commands by default. This is because partners must go out of their way to use those commands, whereas the other capabilities of the bot are more "automatic"

"automatic" like assistive pricing, adding labels, automatic payments etc.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/595#issuecomment-1673214378_

**Comment by rndquu** [comment]
> I think we should enable all commands by default. However I would like to hear why this could be a bad idea before turning this into an official task.
> 
> > > Skipping `/multiplier` because it is disabled on this repo
> 
> > I wonder if it makes sense to enable all of the slash commands by default. This is because partners must go out of their way to use those commands, whereas the other capabilities of the bot are more "automatic"
> 
> "automatic" like assistive pricing, adding labels, automatic payments etc.
> 
> _Originally posted by @pavlovcik in [#595 (comment)](https://github.com/ubiquity/ubiquibot/issues/595#issuecomment-1673214378)_

I think it's ok to enable all of the features by default

**Comment by pavlovcik** [comment]
To clarify, I am talking about slash commands only. The other features I fear that they might annoy or get in the way for new partners who don't fully understand all of the capabilities. I am not confident with even the slash commands because imagine if new onboarded partners dont want bounty hunters to automatically be able to assign themselves?

**Comment by pavlovcik** [comment]
> Skipping `/start` because it is disabled on this repo

Maybe you can enable all the slash commands on the org defaults?

**Comment by rndquu** [comment]
> > Skipping `/start` because it is disabled on this repo
> 
> Maybe you can enable all the slash commands on the org defaults?
> 
> To clarify, I am talking about slash commands only. The other features I fear that they might annoy or get in the way for new partners who don't fully understand all of the capabilities. I am not confident with even the slash commands because imagine if new onboarded partners dont want bounty hunters to automatically be able to assign themselves?

https://github.com/ubiquity/ubiquibot-config/pull/9
