### ISSUE TITLE
Explicitly state what the permits are for

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#600]
It could be nice to explicitly state what the permits are for, eventually. A task for another day. 

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/545#discussion_r1290233065_

**Comment by whilefoo** [comment]
This will be done by #545 so we can close this

**Comment by pavlovcik** [comment]
I guess technically we should have separate pull requests per solved issue but I understand that we're rushing to get that one closed out already, and I guess the delay is more on the review team's part?
