### ISSUE TITLE
Setup proper row-level security for tables

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/ubiquibot#613]
### Describe the background or context

The staging db has broken due to an incompleted row security setup in https://github.com/ubiquity/ubiquibot/pull/578
an 

### Describe the solution

Need to add more policies for authorization, access control, etc

**Comment by 0xcodercrane** [comment]
done in linked PR.

**Comment by pavlovcik** [comment]
Thanks for setting this up but you should wait for me to set priority
