### ISSUE TITLE
Bug: Creating or modifying wallet address is currently broken and does not have proper error handling

### ISSUE THREAD

**Issue by gitcoindev** [ubiquity/ubiquibot#620]
### Describe the background or context

I spent over three hours trying to verify my PR and get 'QA' and I stumbled against a serious bug.

There are two problems: 

1. Inserting or modifying any database row with type defined as a fixed length char is currently broken and allows only 1 character. I verified this with supabase dashboard. The root cause is https://github.com/PostgREST/postgrest/issues/2861 which was fixed but the fix is not available yet in the workspace.

2. Error handling is supabase adapter is broken and it must be fixed e.g.

https://github.com/ubiquity/ubiquibot/blob/development/src/adapters/supabase/helpers/client.ts#L165
https://github.com/ubiquity/ubiquibot/blob/development/src/adapters/supabase/helpers/client.ts#L170
https://github.com/ubiquity/ubiquibot/blob/development/src/adapters/supabase/helpers/client.ts#L178
https://github.com/ubiquity/ubiquibot/blob/development/src/adapters/supabase/helpers/client.ts#L193

Modifying db entries return data or error, but nothing is done when error happens. The functions happily return with just logger traces and the bot claims that everything went well, see https://github.com/gitcoindev/ubiquibot/issues/6#issuecomment-1678456596 and bot comments below. Only when I locally modified the source to insert "1" as wallet address, it was truly successful.

### Describe the solution

1. Use variable char in DB, even for address and validate variables length where needed:

https://github.com/PostgREST/postgrest/issues/1586#issuecomment-696821113

2. Implement a proper error handling in supabase adapter.

**Comment by whilefoo** [comment]
This a known issue. Solution for `2.` will be resolved by #545

**Comment by gitcoindev** [comment]
Good to hear that @whilefoo

**Comment by whilefoo** [comment]
I will make a PR that solves both issues because I don't know how long #545 will take to merge

**Comment by pavlovcik** [comment]
> I will make a PR that solves both issues because I don't know how long #545 will take to merge

Normally we prefer to have unique pull requests for unique issues. This is for auditing reasons. You should try and do a unique pull request for this issue by cherry picking the changes from your other pull request. It's fairly straightforward to do if you use a tool like gitgraph for vscode once the code is already done.
