### ISSUE TITLE
Database: Should Check For Duplicates

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#623]
Looks like it is case sensitive. We should be doing this in a more robust way. Lets do by GitHub user ID, but also save their latest username (@byteballet changed theirs) for database review convenience.

<img width="963" alt="image" src="https://github.com/ubiquity/ubiquibot/assets/4975670/15b83fda-9fea-4cc1-b495-fbd81d581e67">

**Comment by byteballet** [comment]
> Too many assigned issues, you have reached your max of 2
> https://github.com/ubiquity/ubiquibot/issues/592#issuecomment-1671166723

Is it working?

**Comment by byteballet** [comment]
Users can change their user names on github.
https://github.com/ubiquity/ubiquibot/issues/623#issue-1853386636
This happened because I changed my github user name.

It would be good to manage users on database by user id, not user name.
I think I opened unnecessary issue: https://github.com/ubiquity/ubiquibot/issues/625
Please delete it, @pavlovcik

**Comment by byteballet** [comment]
I think it should be done after https://github.com/ubiquity/ubiquibot/pull/604 is merged...?

**Comment by pavlovcik** [comment]
> I think it should be done after #604 is merged...?

Don't think its dependent on this.

**Comment by byteballet** [comment]
> > I think it should be done after #604 is merged...?
> 
> Don't think its dependent on this.

Oh, just confused.

**Comment by byteballet** [comment]
Isn't it resolved after https://github.com/ubiquity/ubiquibot/pull/618 merged?

**Comment by pavlovcik** [comment]
Duplicate #618

**Comment by pavlovcik** [comment]
@byteballet looks like the bounty hunter gave up on the original issue as a heads up

**Comment by byteballet** [comment]
> @byteballet looks like the bounty hunter gave up on the original issue as a heads up

Of #618 ?
