### ISSUE TITLE
Bot Comment Tweaks

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#632]
1. Error messages should be written as a comment leveraging `diff` and not prefix "Error: " because "Error: " recurses.

```diff
- My error message
```

Markdown source code for reference:

<img width="149" alt="Screenshot 2023-08-18 at 05 33 46" src="https://github.com/ubiquibot/staging/assets/4975670/43950b0d-07ac-4b55-ac32-5c155bd68ba0">

2. Permits valued at 0 should be skipped for commenting out or logged as debt. 

>> Error: Error: new row violates row-level security policy for table "permits"
> 
> Perhaps we should not prefix error messages with "Error: " or else nested errors look like this 
> 
>> ### [ **pavlovcik: [ CLAIM 0 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMCJ9LCJub25jZSI6IjcwMDA5NTc5MTE3MjM0MzA5MTExOTE4NTYwNjI3MjU0MzI2MzAxODYzMjA3NDcyMjkwNjI2NTU3ODA2MTYyMjg2MTc0MjcwODA4OTk2IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg0MDA3Q0UyMDgzYzdGM0UxODA5N2FlQjNBMzliYjhlQzE0OWEzNDFkIiwicmVxdWVzdGVkQW1vdW50IjoiMCJ9LCJvd25lciI6IjB4NzBmYmNGODJmZmE4OTFDNDI2N0I3Nzg0N2MyMTI0M2M1NjZmNzYxNyIsInNpZ25hdHVyZSI6IjB4ZGRkYTYzODIzNjVlMWQ0YTE0ZjhkZjJlMDA1NmJiODgwNjA4ZDhkNmMzOWYyNTMzNTgxMjhjNGE2MjUwYjEzZDEzNGRhYjA2YjA5ZjIwMzdlN2Y4YzJjYjdlMjk1MmE1MzE2ODhkYThiYTM5MmFiZWY1YzA2MjMzZWJiZTMwNjcxYyJ9&network=100)
>> 
> 
> Also 0 WXDAI permits we should not print out. 
> 
>> its payment of 0.0 WXDAI will be deducted from your next bounty.
> 
> Or appear as debt.

_Originally posted by @pavlovcik in https://github.com/ubiquibot/staging/issues/80#issuecomment-1676941586_

**Comment by Keyrxng** [comment]
> ` Deadline Mon, 21 Aug 2023 21:33:52 UTC Registered Wallet 0xAe5D1F192013db889b1e2115A370aB133f359765 `
> ###### Tips:
> * Use `/wallet 0x0000...0000` if you want to update your registered payment wallet address @user.
> * Be sure to open a draft pull request as soon as possible to communicate updates on your progress.
> * Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the bounty.

Can we add to the spec fixing the table comment.

I'll use github markdown so that either the deadline or warning will be bold and we won't have this additional whitespace.

Below are examples, either we always show the deadline alongside the warning or we swap out the deadline for the warning instead

![withdeadline](https://github.com/ubiquity/ubiquibot/assets/106303466/c2315637-288d-4997-bec6-211dbf606562)
![withoutdeadline](https://github.com/ubiquity/ubiquibot/assets/106303466/d550b747-2a85-4411-9b20-4c2ceaef076a)

**Comment by pavlovcik** [comment]
In the future it's better to link the original comments here on GitHub so we can see. It's a bit inconvenient looking at screenshots from my phone. 

The additional space is an artifact of wrapping the table with the `code` element in order to render the text all monospace. This was intentional to display in monospace but the artifact we never found a solution for. Please let the table continue to render in monospace. 

Lastly do not use the headers because apparently the text is center aligned. It should all be left aligned.

**Comment by Keyrxng** [comment]
> Lastly do not use the headers because apparently the text is center aligned. It should all be left aligned.

See the comment below, left alignment is possible with github markdown using ```|:--|:--|```

https://github.com/Keyrxng/UbiquityBotTesting/issues/43#issuecomment-1712852281

Okay so revert the table back to how it was, yeah?

**Comment by pavlovcik** [comment]
That's cool to see!

Unfortunately in my experimentation I could not figure out how to monospace everything inside of the table with markdown. 

The best I could do is individually wrap each sentence in the back ticks, but then it adds a background around just the words and looks bad. 

So instead we now use the html ```html
<code>
```
Element which wraps the entire table and does not cause the backgrounds behind every word. 

If you can solve that monospace problem with pure markdown then please feel free to use markdown.

**Comment by Keyrxng** [comment]
>If you can solve that monospace problem with pure markdown then please feel free to use markdown.

I gave it a shot but no joy with it, managed to strip some whitespace but no hacks work I found.

Tried wrapping the first ``<code>`` as a comment as well as having ``<code><table>`` but it removes the font so yeah it's as good as it'll get I think your right
