### ISSUE TITLE
Automated QA: Unit tests with mocked github events

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#634]
> A lengthy goal would be to also include unit tests with mocked github events 

_Originally posted by @web4er in https://github.com/ubiquity/ubiquibot/issues/626#issuecomment-1681888735_

**Comment by 0xcodercrane** [comment]
kicking off this issue slowly. but anyone can get assigned anytime. I will work on base architecture and examples.

**Comment by 0xcodercrane** [comment]
Here's a quick instruction if you wanna take over the issue on top of the latest progress I've made:

1/ Fork the `feat/unit-test` branch to your local repo cause I am continuously pushing new stuff.
2/ Add *.spec.ts in `test` folder like [address.spec.ts](https://github.com/ubiquity/ubiquibot/blob/feat/unit-test/test/utils/address.spec.ts).
3/ You can add specific files to [exclude list](https://github.com/ubiquity/ubiquibot/blob/feat/unit-test/.nycrc.json#L3) for the coverage. In the ideal case, we shouldn't add anything to the exclude list. we can add index files to the exclude list.
4/ Feel free to ask to @0xcodercrane or any admins if you have any questions/comments/improvements.
