### ISSUE TITLE
Supabase Drop Old Logs

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot#655]
Use built-in supabase CRON job to drop logs that are greater than one week old. 

> That's a good question actually they will charge us once we reach to the limit. 
we can use `pg_cron` extension that the supabase platform originally supports.

_Originally posted by @0xcodercrane in https://github.com/ubiquity/ubiquibot/issues/592#issuecomment-1687583313_

**Comment by byteballet** [comment]
Maybe it is only assignable to the limited members as it seems need work on supabase directly.

**Comment by pavlovcik** [comment]
I'm not sure if that's true. You can work on your own Supabase instance and then submit the script for us to try on ours.
