### ISSUE TITLE
Automatic Stack Traces for `Logger`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#665]
We should refactor the log function so that we dont have redundant prefixes we are passing in. Those should be automatically derived from the stack trace. 

I believe this will require us to use traditional function declarations, not anonymous functions, in order to access the function names for the stack traces. This simplifies debugging.

https://github.com/ubiquity/ubiquibot/pull/657#discussion_r1302373477

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/657#discussion_r1303738709_

**Comment by Sadaf-A** [comment]
Hello @pavlovcik ,

Could you please provide some more context and share the GitHub file links?

Thank you.

**Comment by gitcoindev** [comment]
I had a look at Logger interface type

```
export type Logger = {
  info: (msg: string | object, options?: JSON) => void;
  debug: (msg: string | object, options?: JSON) => void;
  warn: (msg: string | object, options?: JSON) => void;
  error: (msg: string | object, options?: JSON) => void;
};
```

and used options JSON object to introduce a new optional 'logFnName' option.

Now any `log.info`, `log.warning` , `log.error`, `log.debug` function can optionally show caller function name by adding an optional logFnName argument. If specified, the function name is added as a prefix to log message in square brackets, see PR https://github.com/ubiquity/ubiquibot/pull/873 for an example.

**Comment by gitcoindev** [comment]
Update: I see that linter on CI complains about no-prototype-builtins , I will try to workaround that.

**Comment by gitcoindev** [comment]
Problem solved, build is passing now. PR ready for the review.

**Comment by gitcoindev** [comment]
A message for the bot: as discussed during Pr review, the feature will be part of a big refactoring and credit will be given afterwards.

**Comment by gitcoindev** [comment]
Bot: will be credited after merging https://github.com/ubiquity/ubiquibot/pull/644

**Comment by gitcoindev** [comment]
Bot: will be credited after merging https://github.com/ubiquity/ubiquibot/pull/644

**Comment by 0x4007** [comment]
You don't need to worry about the follow ups if they are tedious. Nobody can self assign and take over a task on this repository. 

Just be sure to remind me of all the tasks you are owed for once this is ready again. 

Also I realized that I handled this in my refactor lol but you can still get credit.
