### ISSUE TITLE
Consolation Prize?

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/ubiquibot#669]
# First, why?

Say someone assigns a job to themselves and carries out all of or some of the work, let's say it's an old issue and it's no longer relevant or required and just hasn't been removed/updated yet. With a very busy team and a lot of distance to cover it's possible for these scenarios to arise especially (as the codebase repeats),  as things continue to grow. 

# What happens then?

I propose a consolation prize of sorts, what exactly that would be is definitely beyond my current understanding of things and above my paygrade to decide as well obviously. 

The assignee who committed the work but through no fault of their own has had to stop due to the issue being body-bagged, should receive either a percentage of the allocated rewards or have some form of tracking in place so that if it happens on multiple occasions it can be said 'well that's n hours of work' or 'n% of the spec achieved' so you can claim 20 bucks or something along those lines.

# An alternative Solution

Sign-post any new ```/start``` command with a disclaimer not to begin the work until someone has confirmed that it is still relevant and should be executed. (If this already exists and I missed it then I think it should be made clearer on DevPool onboarding docs etc)

# Disclaimer

I am by no means salty or have a bitter taste in my mouth that this happened to myself, I'm glad it did actually as it has given me my first issue to raise. Looking forward to hearing your thoughts.

**Comment by Keyrxng** [comment]
Is this the correct way to do things @pavlovcik? Just open new issues, hash it out and take it from there or should it be opened as a discussion first?

**Comment by pavlovcik** [comment]
> Is this the correct way to do things @pavlovcik? Just open new issues, hash it out and take it from there or should it be opened as a discussion first?

Yeah we sort of stopped using discussions because they don't get nearly as much traction as issues for engagement.

**Comment by pavlovcik** [comment]
@0xcodercrane looks like the bot is down

**Comment by pavlovcik** [comment]
Or is it refusing to price this issue because it was opened by an external contributor? @wannacfuture @whilefoo any ideas?

**Comment by whilefoo** [comment]
I think one of the latest merges broke the bot. I pulled the latest development branch and it's not working: https://github.com/ubiquity-whilefoo/ubiquibot/issues/52

**Comment by pavlovcik** [comment]
> Update: I'm using it on another repository just fine.

It must be the local config here.

**Comment by whilefoo** [comment]
Oh it's because you are using `Priority: 0 (Normal)`, we changed the priority number from 1 to 5

**Comment by pavlovcik** [comment]
I just changed the labels lets try again.

**Comment by pavlovcik** [comment]
@whilefoo not sure what it could be but its a pretty critical issue if we cant have bounties be priced!

**Comment by whilefoo** [comment]
yeah I'm not sure, after I fixed the labels it seems to be working on my repo: https://github.com/ubiquity-whilefoo/ubiquibot/issues/52

**Comment by pavlovcik** [comment]
The only relevant difference I guess is the issues' content in this repository compared to yours? We need more logs to diagnose.

**Comment by whilefoo** [comment]
> #### Task Creator Reward
> ### [ **Keyrxng: [ CLAIM 126.4 WXDAI ]**](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI2NDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTc1Mjk3MDM4MzYyMTA3OTc3MjIzNDg1NTYyMzc4NzkyNjg2NDM3NDQ4MTM0NDkzNzAyNzkxODQwNDYzMTg0MzQ1NTA0OTE5MTI3MzAiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweEFlNUQxRjE5MjAxM2RiODg5YjFlMjExNUEzNzBhQjEzM2YzNTk3NjUiLCJyZXF1ZXN0ZWRBbW91bnQiOiIxMjY0MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDMwNmE0ZTM5ZWYzN2QyZjY5Mjc4YThkODA4NjlhYjE3ZjA5MmE0OGZiZGE0YTE2OWIyMGE3MmJlYjc0NjI3NTUwOTc4NjJkN2Y4YTUxOTk5ZDE0N2RhYmNiZTM4M2FjMjA0ZWNmNWE2YmU0MTA0ZTVlNjA4OTRkZjhhYTJiYjIxMWMifQ==&network=100)

@pavlovcik this should've been capped to the bounty price, right? Should we invalidate the permit and do manual transaction, or just let it be this time?

**Comment by Keyrxng** [comment]
I have already claimed it but I'm happy for it to be deducted off the next bounty or whatever I'm easy either way cheers

**Comment by pavlovcik** [comment]
> > #### Task Creator Reward
> > ### [ **Keyrxng: [ CLAIM 126.4 WXDAI ]**](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI2NDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTc1Mjk3MDM4MzYyMTA3OTc3MjIzNDg1NTYyMzc4NzkyNjg2NDM3NDQ4MTM0NDkzNzAyNzkxODQwNDYzMTg0MzQ1NTA0OTE5MTI3MzAiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweEFlNUQxRjE5MjAxM2RiODg5YjFlMjExNUEzNzBhQjEzM2YzNTk3NjUiLCJyZXF1ZXN0ZWRBbW91bnQiOiIxMjY0MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDMwNmE0ZTM5ZWYzN2QyZjY5Mjc4YThkODA4NjlhYjE3ZjA5MmE0OGZiZGE0YTE2OWIyMGE3MmJlYjc0NjI3NTUwOTc4NjJkN2Y4YTUxOTk5ZDE0N2RhYmNiZTM4M2FjMjA0ZWNmNWE2YmU0MTA0ZTVlNjA4OTRkZjhhYTJiYjIxMWMifQ==&network=100)
> 
> @pavlovcik this should've been capped to the bounty price, right? Should we invalidate the permit and do manual transaction, or just let it be this time?

I really wish I had more clarity on how exactly these numbers are being calculated. This seems way, way higher than expected. We'll let it be this time. Any ideas how exactly it came to this number from the spec?

**Comment by whilefoo** [comment]
This number seems way too high, maybe we should log the calculation or display it in the comment so we can see what's going on
