### ISSUE TITLE
Log app show history

### ISSUE THREAD

**Issue by whilefoo** [ubiquity/ubiquibot#676]
Currently the log app only streams new logs from the database in real-time, but we also want to see the history of logs. When the page loads it should load around last 30 logs and display them. The newest logs should be at the top and new logs from realtime websocket should be appended at the top. If you scroll down it should load next batch of old logs like infinite scroll

**Comment by pavlovcik** [comment]
Feel free to place a time estimate label when creating a new task and just let me or @0xcodercrane handle the priority

**Comment by 0xcodercrane** [comment]
no comments for priority label

**Comment by gitcoindev** [comment]
PR opened: https://github.com/ubiquity/ubiquibot-logging/pull/7
QA: 

https://github.com/ubiquity/ubiquibot/assets/88761781/aba3b710-9152-463e-a364-3440a9c40c3e

**Comment by gitcoindev** [comment]
I also added fetching most recent 30 logs at startup, so that the table is immediately showing latest logs.
