### ISSUE TITLE
Clear Logging Error for broken `ubiquibot-config.yml`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#680]
The bot does not show any visible errors for when it has an issue loading in a new config. The bot was down for about 14 hours on this repository until we identified the fix. Apparently it was the broken config. 

There were no logs to verify this, we just changed it because the bot was working on other repositories. 

- https://github.com/ubiquity/ubiquibot/pull/677/files

Context: https://t.me/c/1588400061/3250/4436

The business problem to solve is that we need to know as soon as possible if the config is valid.

- [ ] Clearly log error while the bot tries to load the config in the Supabase.
- [ ] We should consider some type of special event that when the config is updated, the bot immediately validates it and lets the user know via a comment directly on the commit. Similar to how we do deploy comments on: https://github.com/ubiquity/ubiquity-dollar/commit/8fa34df8b37903f2e812cfacd2f1ba438faae095#commitcomment-125340301

**Comment by pavlovcik** [comment]
> We should consider some type of special event that when the config is updated, the bot immediately validates it and lets the user know via a pull request comment, or a comment directly on the commit. 

@whilefoo you expressed interest in this. Can you provide input on the second subtask?

> We should consider some type of special event that when the config is updated, the bot immediately validates it and lets the user know via a pull request comment, or a comment directly on the commit.

**Comment by whilefoo** [comment]
The second subtask is doable. We already handle push events on the bot, so we just need to retrieve the content of the config at specific commit hash, parse it and validate it and if it fails it will post a commit comment. This will also work for partners when they change the config.

**Comment by whilefoo** [comment]
> Permit generation skipped because bounty amount after penalty is 0
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

I don't think I have any penalties?

**Comment by pavlovcik** [comment]
> > Permit generation skipped because bounty amount after penalty is 0
> > ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> > ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!
> 
> I don't think I have any penalties?

I guess it would make sense to link back to the re-opened issue that you were penalized for. I'm glad that I saw this because this is the first time I've seen a penalty work. I'm checking the database to get more info here.

**Comment by pavlovcik** [comment]
> Permit generation skipped because bounty amount after penalty is 0
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

https://gnosisscan.io/tx/0x87d8703ab5d690bb549f6813f84bbea3b5966d27b8b7150ebcc269673735b979

**Comment by whilefoo** [comment]
> I guess it would make sense to link back to the re-opened issue that you were penalized for. I'm glad that I saw this because this is the first time I've seen a penalty work. I'm checking the database to get more info here.

I'd guess that is hard to do in current state because penalties seem to add up from different issues and get deducted when new issues are closed so it acts like a debt balance and we can't accurately link back a PR unless we redesign the system

**Comment by pavlovcik** [comment]
> unless we redesign the system

We'll probably need to change the schema to support a new table that has all the debt information. Basically a ledger of credits and debits which links the issue.
