### ISSUE TITLE
Can't regenerate payment

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#685]
We need to come up with an adjustment to this flow because the bot won't let me regenerate the payment permit because the bot will not let me keep the assign. 

I think on the assign event (and any event of specific actions) the bot should be mindful to not undo the user's action. For example, when a new assignee is added like in the referenced example, perhaps the bot should never unassign that assignee on the same issue as a response to the event. 

Or if I add a specific label, perhaps the bot should be mindful to never remove that same added label.  

> @sergfeldman - Releasing the bounty back to dev pool because the allocated duration already ended! 
Last activity time: Thu Jul 20 2023 09:57:04 GMT+0000 (Coordinated Universal Time)

_Originally posted by @ubiquibot in https://github.com/ubiquity/card-issuance/issues/14#issuecomment-1696251912_

**Comment by wannacfuture** [comment]
> I think on the assign event (and any event of specific actions) the bot should be mindful to not undo the user's action. For example, when a new assignee is added like in the referenced example, perhaps the bot should never unassign that assignee on the same issue as a response to the event.

Hmm tbh I don't think assign event is capable of handle that issue. 
My thought looks like this:

- bot checks the last activity time
- we find the bot's command saying like `@hunter The time limit for this bounty is on Tue, 29 Aug 2023 19:26:38 UTC`
- we also consider that comment's createdAt as activity time of @hunter

@pavlovcik  rfc

**Comment by pavlovcik** [comment]
> > I think on the assign event (and any event of specific actions) the bot should be mindful to not undo the user's action. For example, when a new assignee is added like in the referenced example, perhaps the bot should never unassign that assignee on the same issue as a response to the event.
> 
> 
> 
> Hmm tbh I don't think assign event is capable of handling that issue. 
> 
> 
> 
> I just noticed that the bot removes assign right after saying "the time limit for this bounty is ..."
> 
> 
> 
> My thought looks like this:
> 
> 
> 
> - bot checks the last activity time
> 
> - we find the bot's command saying like `@hunter The time limit for this bounty is on Tue, 29 Aug 2023 19:26:38 UTC`
> 
> - we also consider that comment's createdAt as activity time of @hunter
> 
> 
> 
> @pavlovcik  rfc

Is it realistic for the bot to handle all of the logic in a single runtime vs running multiple times? I imagine that we can interpret the original event that invoked the bot across every action the bot takes, which would make my proposal feasible.

**Comment by wannacfuture** [comment]
let me take a look

**Comment by wannacfuture** [comment]
working on it.

**Comment by 0xcodercrane** [comment]
To make @pavlovcik 's proposal feasible, we can exclude the active issue from `checkBountyToUnasssign` which basically iterates all the issues and tries to unassign the hunters. Sounds simple than @wannacfuture 's method lol

**Comment by pavlovcik** [comment]
We should have a generalized solution instead which retains understanding of the original event that invoked the bot. 

For example if we chain together all the handlers and pass in the original event that invoked the chain, the handlers will understand that the human input performed X action (like assign or set price label) and to make sure to not undo that

**Comment by 0xcodercrane** [comment]
You're right. To have a generalized solution is an ideal way to make the bot extensible. We can start it with a simple way right now but finally have an ideal way. maybe you can create a separate issue.

**Comment by wannacfuture** [comment]
I think this can be closed and hotfix for https://github.com/ubiquity/ubiquibot/issues/774 can solve it. @pavlovcik

**Comment by 0xcodercrane** [comment]
agree
