### ISSUE TITLE
Use different nonce for comment incentives

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#686]
### Context

Check this [issue](https://github.com/ubiquity/ubiquity-dollar/issues/780)

There are 2 permits generated:
1. https://github.com/ubiquity/ubiquity-dollar/issues/780#issuecomment-1696422095 (issue solver reward)
2. https://github.com/ubiquity/ubiquity-dollar/issues/780#issuecomment-1696422165 (issue creator reward)

Right now we use `issue.node_id` as a permit nonce so those 2 permits are using the same nonce. It means that only 1 of those permits is claimable.

We should change the logic of how permit nonce is generated so that the permit (bounty reward + comment incentives) could be claimed by different bounty hunters in a single issue. 

Perhaps we could generate nonce smth like `keccak256(issue.node_id . bountyHunter.user_id)`.

### Tasks

1. Consolidate the permits based on contributor (right now there can be multiple posted for a single contributor.)
    - When combined, the caption should list out all of the reasons. e.g. "Issue creator, and assignee rewards: "
2. Use the issue ID and user ID for the nonce. 
    - This enforces that a contributor can only get paid out one time per issue.

**Comment by pavlovcik** [comment]
I think it would be best to:
1. Consolidate the permits based on contributor (right now there can be multiple posted for a single contributor.)
  - When combined, the comment should list out all of the reasons. e.g. "Issue creator, and assignee rewards: "
3. Use the issue and user ID for the nonce. 
  - This implies that a contributor can only get paid out one time per issue, which makes sense to me.

**Comment by rndquu** [comment]
> Also, is it possible to demo with valueless tokens before Friday? We could even use [omni-bridged UBQ governance tokens](https://gnosisscan.io/token/0x2b20faaf99d1f849815d55bed626bde050aa12c4?a=0xefc0e701a824943b469a694ac564aa1eff7ab7dd) on Gnosis. I'll be demoing with small amounts so it should be fine.

There are 2 ways:
1. Create a separate organization and demo with WXDAI (in case of demoing with small amounts)
2. Add a new bot's config param `payout-token`. Then we will create a separate repo in the ubiquity org, setup a special demo repository with a repo wide config setup to accept some valueless token.

> @devpanther I just realized that you picked this up. It's urgent and important so we're going to need to credit whoever delivers a working fix first.

@devpanther Will you make a priority of the current issue?

**Comment by devpanther** [comment]
> @devpanther Will you make a priority of the current issue?

Sure

**Comment by pavlovcik** [comment]
> Then we will create a separate repo in the ubiquity org, setup a special demo repository with a repo wide config setup to accept some valueless token.

Perhaps it can set it up on @ubiquibot org?

**Comment by rndquu** [comment]
> > Then we will create a separate repo in the ubiquity org, setup a special demo repository with a repo wide config setup to accept some valueless token.
> 
> I am planning on demoing using the https://github.com/ubiquity/ubiquibar repo

Then why don't we simply use WXDAI because amounts are small and everything is already set in the ubiquity org?

**Comment by pavlovcik** [comment]
That's what I was going to default to yes

**Comment by rndquu** [comment]
> That's what I was going to default to yes, but then I need to ask people for the money back lol
 
To sum up, we need to:
1. Add a new `payment-token` bot config param (for demo you will use this [repo](https://github.com/ubiquity/ubiquibar) and this [token](https://gnosisscan.io/token/0x2b20faaf99d1f849815d55bed626bde050aa12c4)) 
2. Update pay.ubq.fi to accept the UBQ token

Correct?

**Comment by devpanther** [comment]
> 1. Consolidate the permits based on contributor

I see that `incentivizeComments` and the actual `closedCallback` for Assignee Reward are on different handlers thus it would not be easy to merge assignee rewards and rewards from their comments.

Perhaps assignees shouldn't get incentivized for commenting on their issue? @pavlovcik @rndquu

**Comment by wannacfuture** [comment]
> Perhaps assignees shouldn't get incentivized for commenting on their issue? @pavlovcik @rndquu

I agree with that idea. It doesn't makes sense that the assignee get incentives about the comments himself.

**Comment by rndquu** [comment]
> > 1. Consolidate the permits based on contributor
> 
> I see that `incentivizeComments` and the actual `closedCallback` for Assignee Reward are on different handlers thus it would not be easy to merge assignee rewards and rewards from their comments.
> 
> Perhaps assignees shouldn't get incentivized for commenting on their issue? @pavlovcik @rndquu

Yes, as far as I remember assignees shouldn't get incentives for commenting, but [this](https://github.com/ubiquity/ubiquity-dollar/issues/780) is a different case.

We have 3 parties who get rewards:
1. Issue assignee
2. Issue creator
3. Issue commenters

In [this](https://github.com/ubiquity/ubiquity-dollar/issues/780) particular case issue assignee and issue creator are the same that is why we need to consolidate the reward (issue creator reward + issue solver reward) and generate a permit with a unique nonce (across a single issue) so that other parties (i.e. issue commenters) could also get their rewards.

This "reward consolidation" feature appeared in an effort to find a way to generate unique nonces for commenters. Perhaps we could generate nonces this way:
1. Issue assignee: `keccak256(issue.node_id . bountyHunter.node_id . "ISSUE_ASSIGNEE")`
2. Issue creator: `keccak256(issue.node_id . bountyHunter.node_id . "ISSUE_CREATOR")`
3. Issue commenter: `keccak256(issue.node_id . bountyHunter.node_id . "ISSUE_COMMENTER")`

**Comment by devpanther** [comment]
If we want to consolidate all of the assignee's reward into one

We'd have to move `incentivizeCreatorComment` and `incentivizeComments` (post hooks) into the main action `issueClosedCallback`

That way we can share data amongst functions.

**Comment by wannacfuture** [comment]
> If we want to consolidate all of the assignee's reward into one
> 
> We'd have to move `incentivizeCreatorComment` and `incentivizeComments` (post hooks) into the main action `issueClosedCallback`
> 
> That way we can share data amongst functions.

Can't we just use the returning value of inventivizeCreatorComment and incentivizeComments(also incentivizePullRequestReviews will be added).

**Comment by devpanther** [comment]
> Can't we just use the returning value of inventivizeCreatorComment and incentivizeComments(also incentivizePullRequestReviews will be added).

It does not return, its a processor

```
GithubEvent.ISSUES_CLOSED]: {
    pre: [nullHandler],
    action: [issueClosedCallback],
    post: [incentivizeCreatorComment, incentivizeComments],
}
```

They cannot share data

**Comment by wannacfuture** [comment]
Both `incentivizeCreatorComment`, `incentivizeComments` function adds the comment to the issue, right?

Instead of it, you can make them to return a comments as string and consolidate them and adds that consolidated comment to the issue at last.

**Comment by devpanther** [comment]
> You can call that functions inside issueClosedCallback\nDoes it make sense for you?

Yea, that's exactly the question I was asking..

I don't want to do that without knowing if there's a reason they separated the functions in two, a main callback and post callback

That's the only fix to our problem right now, so I'd just move all of the function to the main handler

**Comment by devpanther** [comment]
@0xcodercrane 

I guess this line was supposed to exclude assignee from comment rewards but assignee is an object.. not a `login` string

```js 
if (user.type == UserType.Bot || user.login == assignee) continue;
```

I'd exclude `assingee.login` from comment rewards now

**Comment by rndquu** [comment]
> > You can call that functions inside issueClosedCallback\nDoes it make sense for you?
> 
> Yea, that's exactly the question I was asking..
> 
> I don't want to do that without knowing if there's a reason they separated the functions in two, a main callback and post callback
> 
> That's the only fix to our problem right now, so I'd just move all of the function to the main handler

So right now there are no any blockers for implementing the "consolidation feature", right?

**Comment by devpanther** [comment]
> > > You can call that functions inside issueClosedCallback\nDoes it make sense for you?
> > 
> > Yea, that's exactly the question I was asking..
> > 
> > I don't want to do that without knowing if there's a reason they separated the functions in two, a main callback and post callback
> > 
> > That's the only fix to our problem right now, so I'd just move all of the function to the main handler
> 
> So right now there are no any blockers for implementing the "consolidation feature", right?

None, I'm testing it out now

**Comment by devpanther** [comment]
@pavlovcik @rndquu Ready for review, QA is attached

I fixed the header: https://github.com/one-two-test/one/issues/6#issuecomment-1699321223

So currently it should be `Task Assignee, and Task Creator Reward`

**Comment by wannacfuture** [comment]
task assignee is same as task creator?

**Comment by devpanther** [comment]
> task assignee is same as task creator?

When the assignee is the task creator, it consolidates the earnings into one and use that header

**Comment by devpanther** [comment]
> #### Task Assignee Reward

Not enough fund to claim @pavlovcik
