### ISSUE TITLE
Add bounty rewards consolidation

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#704]
Check this [issue](https://github.com/rndquu-org/test-repo/issues/21)

When issue is solved then the following participants get rewards:
- issue creator
- issue solver
- issue commenter

When the same person creates an issue and comments in an issue then we need to generate 2 permits for that user (issue creator + issue commenter). We should consolidate such permits in a single one. So when an issue is closed then all permits should be grouped by users.

Thera are 2 exceptions:
1. Issue solver shouldn't get issue commenter rewards
2. Issue creator shouldn't get issue commenter rewards

What should be done:
- combine all generated permits by user
- remove [type](https://github.com/devpanther/bounty-bot/blob/6729f81eadc8504871657bdd432cc0621beef9ad/src/helpers/permit.ts#L60) from permit generation method (it was initially implemented [here](https://github.com/ubiquity/ubiquibot/pull/692) as a kind of a hotfix) and use `keccak256(issue.node_id . bountyHunter.node_id)` for permit nonces
- combined permits should have a caption that states the reason behind the generated permit, ex: "Issue creator and issue solver rewards"

**Comment by rndquu** [comment]
@devpanther Sorry for the inconvenience. The spec has been updated with those 2 edge cases:
```
Thera are 2 exceptions:
1. Issue solver shouldn't get issue commenter rewards
2. Issue creator shouldn't get issue commenter rewards
```

**Comment by Draeieg** [comment]
> @devpanther Sorry for the inconvenience. The spec has been updated with those 2 edge cases:
> 
> ```
> Thera are 2 exceptions:
> 1. Issue solver shouldn't get issue commenter rewards
> 2. Issue creator shouldn't get issue commenter rewards
> ```

@devpanther Sorry for ANOTHER inconvenience lol 

issue solver and creator getting commenter rewards should be a setting we can turn on or off for a given repository, this is to make Non code bounties/tasks like research possible 

idk if this should be within the scope of this bounty of another one @pavlovcik

**Comment by pavlovcik** [comment]
No more scope changes here. 

- We already have https://github.com/ubiquity/ubiquibot/issues/752
