### ISSUE TITLE
Linked Pull Request Not Closed On Expired Task

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#710]
This should be diagnosed and fixed. 

> @wannacfuture - Releasing the bounty back to dev pool because the allocated duration already ended! 
Last activity time: Fri Aug 18 2023 23:07:15 GMT+0000 (Coordinated Universal Time)

_Originally posted by @ubiquibot in https://github.com/ubiquity/ubiquibot/issues/431#issuecomment-1694037026_

**Comment by byteballet** [comment]
Does this mean that the bot should close the pr of the assignee whose deadline is ended?

**Comment by pavlovcik** [comment]
Related #716

**Comment by seprintour** [comment]
I think looping all open PRs on every issue closed is pretty expensive, i see there is a function to directly get linked PR from issue and close

`gitIssueParser`, its not in use currently.. any reason? @pavlovcik @0xcodercrane

**Comment by wannacfuture** [comment]
> I think looping all open PRs on every issue closed is pretty expensive, i see there is a function to directly get linked PR from issue and close
> 
> [`gitIssueParser`](https://github.com/ubiquity/ubiquibot/blob/3eaedcc59d2813aaabb63533ae55477fbfc63ff0/src/helpers/parser.ts#L10), its not in use currently.. any reason? @pavlovcik @0xcodercrane

Currently it is being improved for `incentives for pr reviewers` feature. 'll finish till today evening.

**Comment by seprintour** [comment]
> Do you have any updates @seprintour? If you would like to release the bounty back to the DevPool, please comment `/stop` 
> Last activity time: Mon Sep 11 2023 06:05:40 GMT+0000 (Coordinated Universal Time)

Awaiting review @pavlovcik @whilefoo
