### ISSUE TITLE
Config name format

### ISSUE THREAD

**Issue by whilefoo** [ubiquity/ubiquibot#711]
Yeah you're right, this will be a problem because internal config uses camelCase and yaml config uses kebab-case, so this will cause trouble in the future too. I think it would be best to stick to one format for both configs - camelCase is natural in JS/TS so I think it should be also used in yaml config. I will make a new issue for this but for now modify `getNewContributorConfig` to read from kebab-case and convert to camelCase manually.

_Originally posted by @whilefoo in https://github.com/ubiquity/ubiquibot/pull/689#discussion_r1314242213_

I think we should change yaml name format to camelCase to avoid having to convert it from kebab-case to camelCase when we parse it. This will also allow to have one unified Typescript type.

On this note I'd like to also discuss the separation of the config into two configs. One config would be EnvConfig which parses env variables and another would be the RepoConfig which parses the yaml. Having one merged config was causing issues in #684 because I had to validate the config and if it's invalid I still needed env variables to create Supabase adapter and create logger to log the error.

**Comment by pavlovcik** [comment]
https://chat.openai.com/share/66fd7e0a-8005-47aa-8cea-7fe0508bb560

> Interoperability: If your YAML configurations are solely consumed by your TypeScript code, then using camelCase might make sense. However, if these configurations are also used by other systems where kebab-case is the norm, sticking with kebab-case in the YAML might be more appropriate.

Are there any other systems that use the config? 

> Convention by Language/Usage: While camelCase is conventional in JavaScript and TypeScript, kebab-case is often used in configuration files, URLs, and CSS class names. YAML files often contain configurations that might be interpreted by tools and systems where kebab-case is more conventional.

I agree that I would expect to see kebab-case for yaml config. But I understand that we want to maintain one property name style to make the codebase easier to maintain.

**Comment by pavlovcik** [comment]
I never used this command successfully... we need to fix this or do a new approach.

**Comment by whilefoo** [comment]
> On this note I'd like to also discuss the separation of the config into two configs. One config would be EnvConfig which parses env variables and another would be the RepoConfig which parses the yaml. Having one merged config was causing issues in #684 because I had to validate the config and if it's invalid I still needed env variables to create Supabase adapter and create logger to log the error.

@pavlovcik do you agree separating the configs?

**Comment by Sadaf-A** [comment]
Greetings @whilefoo, I made the changes but I'm getting this error after changing some properties to `camelCase`. I'm not sure if I have permissions required to change this. Could you please have a look?
 
Missing property "runs-on".yaml-schema: GitHub Workflow
GitHub Workflow
Each job must have an id to associate with the job. The key job_id is a string and its value is a map of the job's configuration data. You must replace <job_id> with a string that is unique to the jobs object. The <job_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.

Source: [github-workflow.json](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**Comment by Wholesomebruh** [comment]
@Sadaf-A "runs-on" is part of syntax for GitHub actions. It will be great if you link your PR for assistance in changes to be made.

**Comment by Sadaf-A** [comment]
> @Sadaf-A "runs-on" is part of syntax for GitHub actions. It will be great if you link your PR for assistance in changes to be made.

Hey, I did as requested

**Comment by pavlovcik** [comment]
> > On this note I'd like to also discuss the separation of the config into two configs. One config would be EnvConfig which parses env variables and another would be the RepoConfig which parses the yaml. Having one merged config was causing issues in #684 because I had to validate the config and if it's invalid I still needed env variables to create Supabase adapter and create logger to log the error.
> 
> 
> 
> @pavlovcik do you agree separating the configs?

@ubiquity/software-development rfc

**Comment by rndquu** [comment]
> On this note I'd like to also discuss the separation of the config into two configs

Yes, it makes sense to separate partner configs from the bot's env variables. So basically we need to split this [config](https://github.com/ubiquity/ubiquibot/blob/4b4c8f89909424f1c4ca37ebd16b513dae42816b/src/bindings/config.ts#L45) in 2 parts: partner config and bot env variables.
