### ISSUE TITLE
Move `log-app` to a separate repository

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#712]
There is the frontend [log application](https://github.com/ubiquity/ubiquibot/tree/development/log-app) which displays all of the logs produced by the bot. 

We should move it to a separate repository in order not to: 
- mess log and bot deploy scripts together
- apply a shared cloudflare pages deploy [workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml)

What should be done:
1. Move the [log app](https://github.com/ubiquity/ubiquibot/tree/development/log-app) to a separate repo
2. Remove the log app's related code from the https://github.com/ubiquity/ubiquibot repo
3. Deploy the log app to cloudflare pages using this [workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml)

P.S. When we are done moving the log app to a separate repo we should configure stage and prod [supabase API keys](https://github.com/ubiquity/ubiquibot/blob/development/log-app/scripts/constants/index.ts).

**Comment by pavlovcik** [comment]
@wannacfuture can you take this over?

- https://github.com/ubiquity/ubiquibot/pull/815#issuecomment-1732435340

Another example of this being needed to work. The current app doesn't work at all

**Comment by gitcoindev** [comment]
Hi @wannacfuture @pavlovcik is this bounty available to pick up? I could do the first 2 parts , the third one requires internal access to trigger the action with secrets:

```
CLOUDFLARE_API_TOKEN
CLOUDFLARE_ACCOUNT_ID
UBIQUITY_BOUNTY_BOT_APP_ID
UBIQUITY_BOUNTY_BOT_PRIVATE_KEY
```

**Comment by cuddle-dev** [comment]
> Hi @wannacfuture @pavlovcik is this bounty available to pick up? I could do the first 2 parts , the third one requires internal access to trigger the action with secrets:
> 
> ```
> CLOUDFLARE_API_TOKEN
> CLOUDFLARE_ACCOUNT_ID
> UBIQUITY_BOUNTY_BOT_APP_ID
> UBIQUITY_BOUNTY_BOT_PRIVATE_KEY
> ```

Yes. feel free to pick it up. we have already set them in github secrets. @gitcoindev

**Comment by gitcoindev** [comment]
thank you!

**Comment by gitcoindev** [comment]
I opened the PR to satisfy requirement `1`.

* took original repository https://github.com/ubiquity/ubiquibot-logging created from ts-template by @pavlovcik 
* created a git subtree from log-app directory and created a separate branch out of it using `git subtree split -P log-app/ -b move-log-app` 
* merged with upstream using --allow-unrelated-histories : `git merge --allow-unrelated-histories bot/move-log-app` , this allows to preserve all commits history by @devpanther 

Additionally I enabled the same eslint and prettier settings as in the ubiquibot repository, fixed linter errors, updated package name in package.json and README.md, run prettier over the code and upgraded dependencies to the latest version.

After this PR is accepted and merged, I will try to run the workflow to deploy to cloudflare pages. The last step will be a PR to remove log-app folder from ubiquibot repository.

**Comment by gitcoindev** [comment]
@pavlovcik thank you for approving, I will now open a second PR to remove the code from ubiquibot.

**Comment by gitcoindev** [comment]
To finalize 2) and 3):

Moving deploy workflow to ubiquibot-logging

https://github.com/ubiquity/ubiquibot-logging/pull/3

Removing from https://github.com/ubiquity/ubiquibot

https://github.com/ubiquity/ubiquibot/pull/850

**Comment by gitcoindev** [comment]
Current status: 
1) done, pr merged
2) done, pr merged
3) updated to generic workflow

A new follow-up issue created https://github.com/ubiquity/ubiquibot-logging/issues/4
