### ISSUE TITLE
Multiple tutorial messages

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#715]
Diagnose and fix these multiple tutorial messages. 

Perhaps the issue must be closed as completed before the contributor's comments are taken into account? I'm not sure. 

_Originally posted by @ubiquibot in https://github.com/ubiquity/telegram-ubiquibot/pull/17#issuecomment-1705716566_

**Comment by byteballet** [comment]
This is because verifyFirstCheck function is not correct.
In that function, it checks if count of issues that a specific user commented is one. But I think we also need to count the prs that the user commented.
I want to start this issue but I exceeded maximum limit...
Could anyone assign me?

**Comment by byteballet** [comment]
This is a test
