### ISSUE TITLE
Enable Support for Repository Specific Wallet

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#719]
For testing purposes it could be useful to run the production code but on a different (insolvent) wallet. 

I also think that in large organizations it might be better for budgeting purposes to allow for wallet configuration per repository. 

We already have support for this in the organization config so I imagine that adding the capability for repository config should be pretty straightforward. 

_Originally posted by @ubiquibot in https://github.com/ubiquibot/production/issues/50#issuecomment-1704294859_

**Comment by EtherealGlow** [comment]
@pavlovcik where is it located

**Comment by EtherealGlow** [comment]
found it

**Comment by me505** [comment]
assuming that repo wallet takes precedence
