### ISSUE TITLE
Refactor default bot config from `json` to `ts`

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#725]
Original [comment](https://github.com/ubiquity/ubiquibot/pull/670#discussion_r1306600068)

There is the [default bot config](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json). 

We want to able to add comments to the default bot config. We can't transform the config from `json` to `yml` or `jsonc` because it requires using `fs.readFile()` which causes issues on production netlify build.

What should be done:
- refactor the [default bot config](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json) from `json` to a plain `ts` file

**Comment by whilefoo** [comment]
If we transform it to ts then how will we read it in pay.ubf.fi?

**Comment by rndquu** [comment]
> If we transform it to ts then how will we read it in pay.ubf.fi?

We could add https://github.com/ubiquity/ubiquibot as an npm package to pay.ubf.fi

Perhaps there are better ways

**Comment by Wholesomebruh** [comment]
We can add comment as key value pair in json, if it's so necessary, otherwise on using ts instead of json, tool named jq that works with workflow and repo data will fail. Such as https://github.com/ubiquity/ubiquibot/blob/3eaedcc59d2813aaabb63533ae55477fbfc63ff0/.github/workflows/update-config.yml#L72
There is just 3 such cases. Provided any suggestion you have.

**Comment by Wholesomebruh** [comment]
@rndquu for example
{
_comment1: "This will be the comment"
}
"Update config" refactoring will be included in this issue or there will be seperate issue for that?
Thank you

**Comment by wannacfuture** [comment]
Why incentives for commenters and reviewers don't work? @0xcodercrane  Isn't it deployed to production?

**Comment by 0xcodercrane** [comment]
I think yeah. need to get it to prod.

**Comment by pavlovcik** [comment]
> Why incentives for commenters and reviewers don't work? @0xcodercrane  Isn't it deployed to production yet?

Commenters seems unreliable and inconsistent, and for reviewers: I think only is now merged in.
