### ISSUE TITLE
Penalty Improvement - Traceback

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#767]
## Dependencies

> - `settlementId`s as we currently do not have a table for those. https://github.com/ubiquity/ubiquibot/issues/787

## Overview

Let's name this table `Penalties` to represent instances where a contributor is penalized. This table keeps a record of the exact comment or incident due to which a penalty was applied. 

### Penalties

A ledger of penalties applied to contributors. This table provides a link to the exact comment or reason for the penalty, making the process transparent and traceable.

#### Schema

| Field          | Type         | Description                                                | Example Value                  |
|----------------|--------------|------------------------------------------------------------|--------------------------------|
| `id`           | Integer      | Unique identifier for the penalty log entry.               | 1                              |
| `created`      | DateTime     | Timestamp when the penalty was logged.                     | 2023-09-14T19:20:23.004Z       |
| `updated`      | DateTime     | Timestamp when the penalty log was last updated.           | 2023-09-14T19:20:23.004Z       |
| `userId`       | Integer      | GitHub `id` of the user penalized.                         | 139262667                      |
| `settlementId` | Integer      | Reference to the `Settlements` table.                      | 512                            |
| `orgId`        | Integer      | GitHub `id` of the organization.                           | 76412717                       |
| `repoId`       | Integer      | GitHub `id` of the repository where the issue is located.  | 534616569                      |
| `issueId`      | Integer      | GitHub `id` of the issue related to the penalty.           | 1868425596                     |
| `commentURL`   | String       | URL of the comment or incident leading to the penalty.     | https://github.com/ubiquity/ubiquibot/issues/680#issuecomment-1718491622 |

#### Notes:
- The `commentURL` field allows quick access to the exact comment or reason for the penalty.
- I also made up the `settlementId`s as we currently do not have a table for those. However its spec is here https://github.com/ubiquity/ubiquibot/issues/787
- Ensure foreign key constraints are set up properly to maintain data integrity.
- We should rely on GitHub API's `id` properties instead of `node_id` [Source](https://chat.openai.com/share/f81b31c9-0a13-4d09-b46a-cfe30a01744d).

### Source
- https://github.com/ubiquity/ubiquibot/issues/680#issuecomment-1718488900

**Comment by seprintour** [comment]
>We'll probably need to change the schema to support a new table that has all the debt information. Basically a ledger of credits and debits which also associates the issue with each credit or debit. Example:

Maybe we can have another table called `offset` that is an array of repo that offsets a particular penalty


| created | updated | user | credit | org | repo | task | offset
|--------|--------|--------|--------|--------|--------|--------|--------|
2023-09-14T19:20:23.004Z | 2023-09-14T19:20:23.004Z | whilefoo | -100 | ubiquity | ubiquibot | 680 | 566, 447
2023-09-14T19:20:32.554Z | 2023-09-14T19:20:32.554Z | whilefoo | 150 | ubiquity | ubiquity-dollar | 733 | 234, 444, 560

**Comment by seprintour** [comment]
>We'll probably need to change the schema to support a new table that has all the debt information. Basically a ledger of credits and debits which also associates the issue with each credit or debit. Example:

@pavlovcik  Maybe we can have another table called `offset` that is an array of repo that offsets a particular penalty


| created | updated | user | credit | org | repo | task | offset
|--------|--------|--------|--------|--------|--------|--------|--------|
2023-09-14T19:20:23.004Z | 2023-09-14T19:20:23.004Z | whilefoo | -100 | ubiquity | ubiquibot | 680 | 566, 447
2023-09-14T19:20:32.554Z | 2023-09-14T19:20:32.554Z | whilefoo | 150 | ubiquity | ubiquity-dollar | 733 | 234, 444, 560

**Comment by pavlovcik** [comment]
@seprintour 
- Storing multidimensional data in a SQL database should be avoided
- Also I updated the spec.

**Comment by wannacfuture** [comment]
I think penalty_amount field should be added. @pavlovcik

**Comment by pavlovcik** [comment]
- Rolled into https://github.com/ubiquity/ubiquibot/issues/787
