### ISSUE TITLE
Calculate time with precision (Dynamic Price Calculation vs Lookup Table)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#77]
@0xcodercrane and I included vercel's `ms` library inside of the bot already. We just need to parse the `Time: ` labels using this library to derive the amount of milliseconds each label represents. I think in this future it might make sense to remove the extranous symbols e.g. `<` inside of `Time: <1 Day`

---

### Old Post

Basically if we calculate time with precision we should be able to pick any time interval (1 day, 3 days, 5.5 days etc) and it should be accurate. Right now we only have like four time options, but in the future if we do figure out how to incentivize bounty hunters to gamble on the time estimate of the bounties, we could get accurate time estimates via averages/medians for bounties which will be unlikely to be one of the preset values you have here.

The only way to solve this and to make it work with any time interval is to calculate it with precision- perhaps unix time style.

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/pull/63#discussion_r1068240211_
            
---

GitHub Copilot helped me put this together quickly. I haven't tested it yet but I think its a great starting point to serve as a parser to dynamically calculate the value of a label. This implementation is focusing on `Time: `, but can be extended to parse `Priority: ` easily I believe.

```typescript
const labels = [
	"Priority: 0 (Normal)",
	"Priority: 1 (Medium)",
	"Priority: 2 (High)",
	"Priority: 3 (Urgent)",
	"Time: <1 Hour",
	"Time: <1 Day",
	"Time: <1 Week",
	"Time: <2 Weeks",
];

function parser(label: typeof labels[number]) {
	const timeUnits = [
		{ name: "second", value: 1000 },
		{ name: "minute", value: 60000 },
		{ name: "hour", value: 3600000 },
		{ name: "day", value: 86400000 },
		{ name: "week", value: 604800000 },
		{ name: "month", value: 2629743830 },
		{ name: "year", value: 315569260 },
	];

	const [_, time, unit] = label.split(" ");
	const timeValue = parseInt(time);
	const unitValue = timeUnits.find((u) => u.name === unit)?.value;
	if (unitValue) {
		return timeValue * unitValue;
	}
}

```

### Chat Transcript

@pavlovcik
> ok so price.ts i remember you were asking about calculating this dynamically
> 
> which sounds super dope
> 
> looks like the current implementation does not do that
> 

@0xcodercrane
> it doesn't do that
> 

@pavlovcik
> so we could make a calculateWeight() function
> 

@0xcodercrane
> I didn't get a chance to make it working
> 
> lol
> 

@pavlovcik
> based on name/target i guess
> 
> will need a couple of small custom parsers
> 

@0xcodercrane
> rather than using custom parsers,
> 
> we can use weight property
> 
> Partners will also like it bc
> 

@pavlovcik
> for example, one parser should read the price range e.g. "Price: 400-4000 USD" and determine that its value is > (400+4000)/2=2200
> 
> or parsing and understanding the meaning of day/week/month so that it can give extra weight per every day
> 

@0xcodercrane
> If we make a parser, it will be a bit complex to create override config for patners
> 
> but we can do that if we have detailed spec
> 

@pavlovcik
> that way in the future parnters can dynamically make their own labels. especially useful for us if we do make > betting markets for bounty hunters to guess the time estimate per every bounty
> 
> i see
> 
> well
> 
> i think its definitely surmountable because we have an established format for the label strings
> 
> per type e.g. Profit, Time, Price
> 
> ill make an isuse
> 

@0xcodercrane
> yeah

**Comment by 0xcodercrane** [comment]
I am gonna keep it holding off until @rndquu  completes writing the detailed way to implement.

**Comment by 0xcodercrane** [comment]
> In the Ubiquity Dollar repo we have represented [NotReadyToStart](https://github.com/ubiquity/bounty-bot/labels/NotReadyToStart) as "Backlog" via the Milestone feature. I'm not sure if this is better, but it feels nice to reduce clutter on labels, particularly if the bot is not supposed to deal with them.

This is just a quick label to prevent hunters to spend time on it until we have detailed spec. Whatever is fine if we can let hunters know the status of the bounty.

**Comment by 0xcodercrane** [comment]
Why did you mentioned the dollar PR to bounty bot issue? @rndquu Any relations there?

**Comment by rndquu** [comment]
> Why did you mentioned the dollar PR to bounty bot issue? @rndquu Any relations there?

Check the comment history of https://github.com/ubiquity/ubiquity-dollar/issues/481

There is an issue which is supposed to take significantly less than 1 day to complete but the bot doesn't have a label for such a small issue

**Comment by pavlovcik** [comment]
> quick label to prevent hunters to spend time on it until we have detailed spec.

The assignee should be empty then. @ubiquity-bounties is open to the DevPool. Technically speaking we should probably use @ubiquity-devpool though, I just never made time to officially switch it.

**Comment by pavlovcik** [comment]
I just reviewed the description, I think it has sufficient detail to start. Just replace the numbers you hardcoded to represent the time intervals with the calculated (correct) amount.

**Comment by 0xcodercrane** [comment]
Any time interval should be presented as `label` right? Then we need to create a new label whenever we need or do we need to create all the possible time labels with one command?

**Comment by pavlovcik** [comment]
> Any time interval should be presented as `label` right? Then we need to create a new label whenever we need or do we need to create all the possible time labels with one command?

Don't create all the possible labels, lets push that issue downstream.

For example: 

We suddenly decide that we need half day bounties like what @rndquu's comment mentions:

> Check the comment history of https://github.com/ubiquity/ubiquity-dollar/issues/481

> There is an issue which is supposed to take significantly less than 1 day to complete but the bot doesn't have a label for such a small issue

In this case I can manually create a new label right there that is `Time: <1 Hour`

Bounty bot should be able to parse this and do the "right thing".

**Comment by pavlovcik** [comment]
Rolling this into an updated issue https://github.com/ubiquity/ubiquibot/issues/431
