### ISSUE TITLE
Debugging Comment Incentive Calculations

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#773]
Make it look more presentable but stay in line with the idea of listing everything:

              I think a debugging output to display exactly how the comment incentive was calculated is a great idea: 

e.g. 

[ Claim 26.5 WXDAI ]
<details>
<table>
<thead>
  <tr>
    <th>element</th>
    <th>units</th>
    <th>reward</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>words</td>
    <td>55</td>
    <td>0.1</td>
  </tr>
  <tr>
    <td>a</td>
    <td>3</td>
    <td>5</td>
  </tr>
  <tr>
    <td>img</td>
    <td>1</td>
    <td>5</td>
  </tr>
  <tr>
    <td>h1</td>
    <td>1</td>
    <td>1</td>
  </tr>
</tbody>
</table>
</details>

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/431#issuecomment-1720084587_

**Comment by devpanther** [comment]
Waiting for update on #375

It depends on that design, no reviews yet

**Comment by devpanther** [comment]
@pavlovcik check this out if it works

https://github.com/one-two-test/one/issues/12#issuecomment-1741676553

it is nested in comment incentive table, per user
