### ISSUE TITLE
Task List UI Update

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#788]
I was viewing https://github.com/Seprintour-Test/test/issues/22 and see that GitHub is testing an updated tasklist. Not sure if this will affect the bot's understanding that its a meta-issue, but its worth double checking for this.

![github com_Seprintour-Test_test_issues_22 (1)](https://github.com/ubiquity/ubiquibot/assets/4975670/622deee7-f646-402a-b55e-5c33535b20fc)

Adding HTML source code for reference: [task-list.html.zip](https://github.com/ubiquity/ubiquibot/files/12676568/task-list.html.zip)

**Comment by wannacfuture** [comment]
It will be recognized as a meta issue.

**Comment by pavlovcik** [comment]
> There is a possibility that the tasklist pattern matches with the meta-issue-detect regex.

I included the HTML source code for this reason. Needs to be tested/verified.

**Comment by 0x4007** [comment]
Haven't seen this new beta UI since posting this. We no longer need to accomodate it.
