### ISSUE TITLE
Move shared constants to default config file.

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/ubiquibot#790]
@0xcodercrane shouldn't these all be moved to `ubiquibot-config-default.ts` ? If so, please file a new issue or just handle it. Thanks!

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/748#discussion_r1332052611_

**Comment by molecula451** [comment]
so it's `shared.ts` being deprecated/purged? @0xcodercrane

**Comment by molecula451** [comment]
Should we get rid of https://github.com/ubiquity/ubiquibot/blob/b417336356e2ad7df62aa1fcf04e1ed71f4ea87c/src/configs/shared.ts#L27

as there is an:

https://github.com/ubiquity/ubiquibot/blob/b417336356e2ad7df62aa1fcf04e1ed71f4ea87c/src/configs/ubiquibot-config-default.ts#L4

??

**Comment by molecula451** [comment]
`development` seems broken, can't PR till it's fixed

**Comment by pavlovcik** [comment]
You can certainly pr and rebase when it's fixed.

**Comment by molecula451** [comment]
> You can certainly pr and rebase when it's fixed.

https://github.com/ubiquity/ubiquibot/pull/802

**Comment by pavlovcik** [comment]
> Should we get rid of
> 
> https://github.com/ubiquity/ubiquibot/blob/b417336356e2ad7df62aa1fcf04e1ed71f4ea87c/src/configs/shared.ts#L27
> 
> as there is an:
> 
> https://github.com/ubiquity/ubiquibot/blob/b417336356e2ad7df62aa1fcf04e1ed71f4ea87c/src/configs/ubiquibot-config-default.ts#L4
> 
> ??

Default I feel like it should be on Mainnet. Seems quite opinionated for us to default to a sidechain.

**Comment by molecula451** [comment]
> > Should we get rid of
> > https://github.com/ubiquity/ubiquibot/blob/b417336356e2ad7df62aa1fcf04e1ed71f4ea87c/src/configs/shared.ts#L27
> > 
> > as there is an:
> > https://github.com/ubiquity/ubiquibot/blob/b417336356e2ad7df62aa1fcf04e1ed71f4ea87c/src/configs/ubiquibot-config-default.ts#L4
> > 
> > ??
> 
> Default I feel like it should be on Mainnet. Seems quite opinionated for us to default to a sidechain.

and to your suprise, this constant it's not being used anywhere in the code, no but there is other code that it's being responsible for the rpc

**Comment by molecula451** [comment]
it would be nice to get back commentary rewards @0xcodercrane
