### ISSUE TITLE
Replace @user everywhere

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#793]
@user is supposed to be referencing a specific user usually who invoked the bot. I've seen this in a few places already and it must be fixed. Especially see it all the time on the `/start` table 

> Invalid syntax for query command 
 usage /query @user

_Originally posted by @ubiquibot in https://github.com/ubiquity/ubiquity-dollar/issues/774#issuecomment-1730056879_

**Comment by molecula451** [comment]
/query user (not called @) should still fetch "user"

**Comment by pavlovcik** [comment]
> /query user (not called @) should still fetch "user"

Possibly but this is a separate issue

**Comment by EtherealGlow** [comment]
is the bot sleeping because of my merged pr 💀

**Comment by pavlovcik** [comment]
> /start

Looks like it's broken?

**Comment by molecula451** [comment]
broke hard

**Comment by pavlovcik** [comment]
https://github.com/ubiquity/ubiquibot/commit/4b4c8f89909424f1c4ca37ebd16b513dae42816b

Invalid config according to the logs

**Comment by molecula451** [comment]
but why commented out? did not tried to set to `false` instead?

**Comment by EtherealGlow** [comment]
Mannn

**Comment by Sadaf-A** [comment]
> Mannn

shall I unassign myself if you want to work on it?

**Comment by EtherealGlow** [comment]
Nah you can have this issue

**Comment by pavlovcik** [comment]
There is a bug @Sadaf-A but now you're good to query yourself.

**Comment by Sadaf-A** [comment]
@pavlovcik isn't this how the command is supposed to work?

**Comment by Sadaf-A** [comment]
@pavlovcik can you elaborate a little more on what this issue is supposed to fix?

**Comment by pavlovcik** [comment]
Any instance you see the string literal `"@user"` should never actually write "@user"

**Comment by Sadaf-A** [comment]
> 
> <code>
> <table>
> 
> <tr>
> <td>Deadline</td>
> <td>Sat, 23 Sep 2023 03:15:48 UTC</td>
> </tr>
> <tr>
> <td>Registered Wallet</td>
> <td>0x0BEd00438D57d07E3667b85Fa8EB86Af147C7025</td>
> </tr>
> 
> 
> 
> </table></code><h6>Tips:</h6>
>     <ul>
>     <li>Use <code>/wallet 0x0000...0000</code> if you want to update your registered payment wallet address @user.</li>
>     <li>Be sure to open a draft pull request as soon as possible to communicate updates on your progress.</li>
>     <li>Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the bounty.</li>
>     <ul>

@pavlovcik I see like here the bot writes '@user'
but what should it write instead?
the actual user's tag?

**Comment by pavlovcik** [comment]
Yes

**Comment by molecula451** [comment]
no conversation rewards expected? @pavlovcik

**Comment by EtherealGlow** [comment]
Did you guys up the price mul

**Comment by Sadaf-A** [comment]
@pavlovcik the issue price is 25USD why did I receive 37.5? and even more confusing when I opened it. It was for 18.75 okay I get it. The bot deducted it because of the `parse-permit-url` PR

**Comment by 0x4007** [comment]
> no conversation rewards expected? @pavlovcik 

The bot is pretty broken. Fortunately due to the permit issuance design, in the future when it's stable we should be able to force regen on these old issues to generate the rewards.

**Comment by 0x4007** [comment]
> @pavlovcik the issue price is 25USD why did I receive 37.5? and even more confusing when I opened it. It was for 18.75 okay I get it. The bot deducted it because of the `parse-permit-url` PR

I filed a new issue to fix this. You should be able to see the back reference on this conversation from a few hours ago.
