### ISSUE TITLE
Logs: Error Notifications

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#800]
- Depends on https://github.com/ubiquity/ubiquibot-telegram/issues/37
   - Once the webhook is up, we should dump errors there so that we all receive push notifications in a group chat when the bot fails to run.

**Comment by pavlovcik** [comment]
@seprintour maybe you can take this one

**Comment by seprintour** [comment]
@pavlovcik Am i dumping errors like the logger to supabase implementation?

Wouldn't that be too much data on the group?, or we just send only the `logger.error` messages

**Comment by 0x4007** [comment]
I have no idea. But I am inclined to make available the full info if it is for debugging purposes. Ideally a truncated version in the group chat with a. Link to full information

**Comment by seprintour** [comment]
> I have no idea. But I am inclined to make available the full info if it is for debugging purposes. Ideally a truncated version in the group chat with a. Link to full information 

I think the full error is usually on supabase but it's not public, maybe I'd just dump errors and warns on to the group chat

Would be more useful that way, including a link to the issue the error occurred
