### ISSUE TITLE
Fix `/query`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#804]
> Good find I was just about to post the same. We need to fix that error message for `/query` if access was not initialized, we just should assume everything is false. 

| user_name    | repository                  | priority_access | time_access | price_access | multiplier_access | created_at          | updated_at          |
| ------------ | --------------------------- | --------------- | ----------- | ------------ | ----------------- | ------------------- | ------------------- |
| 0xcodercrane | ubiquibot/production        | true            | false       | false        | false             | 2023-08-31 09:06:47 | 2023-08-31 09:06:47 |
| whilefoo     | ubiquity/ubiquibot          | false           | false       | false        | false             | 2023-09-04 11:26:26 | 2023-09-04 11:26:26 |
| seprintour   | ubiquity/telegram-ubiquibot | false           | true        | false        | false             | 2023-09-09 02:19:02 | 2023-09-09 02:19:02 |
| wannacfuture | ubiquity/ubiquibot          | false           | false       | false        | false             | 2023-09-23 11:53:25 | 2023-09-23 11:53:25 |

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/96#issuecomment-1732295079_

**Comment by pavlovcik** [comment]
@wannacfuture feel free to take this one since you're already looking into this.

**Comment by wannacfuture** [comment]
let me submit a hotfix in mins.

**Comment by wannacfuture** [comment]
@pavlovcik

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0x4da17e1069c5f033290bfbfeba96fe12a49700aa7c5b8cbc13a9022dfe4a4547
