### ISSUE TITLE
Settlements Table Schema

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#808]
## **Settlements**

Represents the overarching record of a financial activity. Each entry can have references to either a credit or a debit.

| Field    | Type         | Description                                    |
|----------|--------------|------------------------------------------------|
| `id`       | int8      | Unique identifier for the settlement.          |
| `created`  | timestamptz     | Timestamp when the settlement was created.     |
| `updated`  | timestamptz     | Timestamp when the settlement was last updated.|
| `user_id`       | int8      | GitHub `id` of the user penalized.                         | 139262667                      |
| `org_id`        | int8      | GitHub `id` of the organization.                           | 76412717                       |
| `repo_id`       | int8      | GitHub `id` of the repository where the issue is located.  | 534616569                      |
| `issue_id`      | int8      | GitHub `id` of the issue related to the penalty.           | 1868425596                     |
| `credit_id` | int8      | Foreign key to the Credits table.              |
| `debit_id`  | int8      | Foreign key to the Debits table.               |

**Comment by seprintour** [comment]
@GaryThisSidee This depends on the Credit and Debit table, you'd have to set up a constraint and make sure it can only have a credit id or a debit id (not both)

> * Set up foreign key constraints for `creditId` and `debitId` in the `Settlements` table.
> * Application logic should prevent a `Settlements` entry from having both a `creditId` and a `debitId`.

from the description: https://github.com/ubiquity/ubiquibot/issues/787#issue-1904968117

Credit and Debit have to merged and then you need to add a function to create a table in `permit`, `credit` and `settlement` tables for every permit generated

**Comment by seprintour** [comment]
So you'd have to wait for #810 and #811, and maybe #819 to be merged in for this to work

**Comment by GaryThisSidee** [comment]
> @GaryThisSidee This depends on the Credit and Debit table, you'd have to set up a constraint and make sure it can only have a credit id or a debit id (not both)
> 
> > * Set up foreign key constraints for `creditId` and `debitId` in the `Settlements` table.
> > * Application logic should prevent a `Settlements` entry from having both a `creditId` and a `debitId`.
> 
> from the description: [#787 (comment)](https://github.com/ubiquity/ubiquibot/issues/787#issue-1904968117)
> 
> Credit and Debit have to merged and then you need to add a function to create a table in `permit`, `credit` and `settlement` tables for every permit generated

ohh i see

**Comment by GaryThisSidee** [comment]
@seprintour  looks like u already working on #811 should i do the #810 ?

**Comment by seprintour** [comment]
> @seprintour  looks like u already working on #811 should i do the #810 ?

Yea, you can start working on it.. It also depends on #811 though..

There's a field for permitId
