### ISSUE TITLE
Debits Table Schema

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#809]
## **Debits**

Represents deductions "penalties" made to assignees when an issue is re-opened.

| Field      | Type     | Description                                           | Example Value               |
|------------|----------|-------------------------------------------------------|-----------------------------|
| `id`       | int8  | Unique identifier for the debit entry.                | 1                         |
| `created`  | timestamptz | Timestamp when the debit was created.                 | 2023-09-15T10:30:45.012Z    |
| `updated`  | timestamptz | Timestamp when the debit was last updated.            | 2023-09-15T10:35:20.100Z    |
| `amount`   | int8  | Amount deducted.                                      | 500                         |

**Comment by pavlovcik** [comment]
For the amount lets do what supports 1e18 format `BigInteger`?

**Comment by seprintour** [comment]
I think the amount for debit and credit should be a float or big integer if we are converting decimal to bigint because permit amount is not always in whole numbers

**Comment by seprintour** [comment]
> For the amount lets do what supports 1e18 format `BigInteger`?

Yea, so on the bot we convert the decimal to 1e18

**Comment by pavlovcik** [comment]
/ask what supabase column datatype is best for 1e18 format numbers? in the context of ethereum tokens and how they represent amounts

**Comment by pavlovcik** [comment]
@Keyrxng lol this is a much smaller issue too

**Comment by seprintour** [comment]
> @Keyrxng lol this is a much smaller issue too

is it counting comments?

**Comment by seprintour** [comment]
> /ask what supabase column datatype is best for 1e18 format numbers? in the context of ethereum tokens and how they represent amounts

https://chat.openai.com/share/b4d90deb-49fd-4c95-982f-dedb1c9c6e33

**Comment by pavlovcik** [comment]
lol I am ahead of you https://chat.openai.com/share/e8f7eb03-807f-44f3-b7fe-3d883dcf08e4

**Comment by seprintour** [comment]
So we're using `bigint`

**Comment by pavlovcik** [comment]
"int8" i'm updating the specs based on this conversation

**Comment by seprintour** [comment]
PR attached

**Comment by seprintour** [comment]
@pavlovcik Review so i can create the new permit table and copy data over.

After all tables have been merged #812 can create a query that'd move over all penalties to Debit, Permit and Settlements if it will be possible.. or we may have to reset penalties

**Comment by pavlovcik** [comment]
> #### Task Assignee Reward
> ### [ **[ CLAIM 112.5 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNzk3NTAwMTk3MDExMDAzMTQyMjc1NzkzNTI1NjAyMTAxMjk4NDg3NjQ1MzExODg4NTMxNzM3MjMwNjAxOTY3MzU2NjI2NTMxODY4MjUiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDM2MjMzMzgwNDZiMTAxZWNFYzc0MURlOUMzNTk0Q0MyMTc2ZjM5RTUiLCJyZXF1ZXN0ZWRBbW91bnQiOiIxMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDI1MDM1NTc5OTA2Njg0MTE3NmUyMmYzMTk1ZTVhNTAwODZlMmY1ZWIxNmM0YTM0YjYwNDg4M2Y5NDM4ZDZmMzQ3NDJjMDhiMjA0YzViMDlhMTI0NmI3NjA3OGQ2NmEzNDAzYzBlYzgwNzZjNjJlMzdmNDNhOGU3MmUzM2Q4YzZkMWIifQ==&network=100)
> `0x362333804...C2176f39E5`
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

This is unexpected @0xcodercrane why is this unreliable

**Comment by Keyrxng** [comment]
> ```diff
> ! Error: This model's maximum context length is 16385 tokens. However, you requested 17152 tokens (768 in the messages, 16384 in the completion). Please reduce the length of the messages or completion.
> ```

> 16384 in the completion

this means the token limit has been set so that the output is equivalent to 16k, max_tokens represents output amount.

So requesting a 16k output including a ``768`` in actual message context, so in total you are requesting ``17152`` which is above the maximum for that model.

**Comment by pavlovcik** [comment]
Yes I changed to 8000
