### ISSUE TITLE
Permits Table Schema

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#811]
## **Permits**

Holds the permit details associated with some credits.

| Field                  | Type     | Description                                      | Example Value                                                                         |
|------------------------|----------|--------------------------------------------------|---------------------------------------------------------------------------------------|
| `id`                   | int8  | Unique identifier for the permit entry.          | 101                                                                                   |
| `created`  | timestamptz | Timestamp when the permit was created.              | 2023-09-15T11:20:23.004Z     |
| `updated`  | timestamptz | Timestamp when the permit was last updated.         | 2023-09-15T11:22:40.050Z     |
| `network`  | smallserial  | Network identifier.                                | 100                          |
| `token`                | CHAR(42)   | Token associated with the permit.                | 0xe92E133E0b41519A2Ce9Dd4D7945Fa863463a97e                                              |
| `amount`     | int8   | Amount associated with the token for the permit. | 150000000000000000000                                                                  | 
| `nonce`                | int8   | Nonce associated with the permit.                | 8802044552...                                                                          |
| `deadline`             | int8   | Deadline associated with the permit.             | 115792089237316195423570985008687907853269984665640564039457584007913129640000        |
| `beneficiary`   | CHAR(42)   | Destination address for the permit's transfer.  | 0x4008FE2190c8F3E18098aeB4A40bb8eC149a342d                                              |
| `owner`    | CHAR(42)   | Owner of the credit.                               | 0xf88da4592C791213e52840d120E7E0B38B818bD2 |
| `signature`| CHAR(132)   | Signature associated with the credit.              | 0xecb65ed54b2ee7a0ffad5aff8314eef684f80dcb78c18b4ea9f588e083a0fa114546d466befa23cb81d040957615b5b1ad08966b64c5778802e5e115cdcd39241b                |

**Comment by seprintour** [comment]
![Screenshot 2023-09-23 at 4 57 02 PM](https://github.com/ubiquity/ubiquibot/assets/51956013/2e5301b0-2031-4ea8-83b0-602d2dc9db0f)

@pavlovcik `deadline` is out of range for type `int8`

**Comment by pavlovcik** [comment]
/ask what data type should we use

**Comment by pavlovcik** [comment]
Oh I just realized something. This is a config error I think.

**Comment by pavlovcik** [comment]
/ask what data type should we use

**Comment by pavlovcik** [comment]
> ![Screenshot 2023-09-23 at 4 57 02 PM](https://github.com/ubiquity/ubiquibot/assets/51956013/2e5301b0-2031-4ea8-83b0-602d2dc9db0f)
> 
> 
> 
> @pavlovcik `deadline` is out of range for type `int8`
> 
> 
> 
> I am trying to move existing data from permit to the new table, so the number is from one of the permit data that is apparently out of range for it

Chatgpt also recommended timestamptz but unsure if that's valid. I have to check in a bit I'm a bit occupied at the moment

**Comment by seprintour** [comment]
This is the deadline `115792089237316195423570985008687907853269984665640564039457584007913129639935`

**Comment by seprintour** [comment]
> Chatgpt also recommended timestamptz but unsure if that's valid. I have to check in a bit I'm a bit occupied at the moment

I'd do the research and make use of what works best

**Comment by seprintour** [comment]
Had to make `deadline`, `nonce` and `amount` numeric, bigint or int8 did not cut it

**Comment by seprintour** [comment]
> Had to make `deadline`, `nonce` and `amount` numeric, bigint or int8 did not cut it

This means i'd have to change the Debit amount to `numeric` too, `int8` supports up to `1e18` but no permit amount is just going to be `1 ETH` or equivalent.

So it goes past 18 and `int8` returns an out of range error

**Comment by seprintour** [comment]
![Screenshot 2023-09-23 at 5 39 39 PM](https://github.com/ubiquity/ubiquibot/assets/51956013/53ab8cab-012c-4378-be04-275e6f8e6daf)

**Comment by pavlovcik** [comment]
Another idea I might add to a new scope, but we can save so much on memory if we have a foreign key to recognized partner wallet address, and recognized token addresses. 

bounty hunter address should be a foreign key also. 

<img width="2672" alt="Screenshot 2023-09-24 at 17 43 47" src="https://github.com/ubiquity/ubiquibot/assets/4975670/8b421740-be0c-46d4-84a2-c223c84bca01">

**Comment by seprintour** [comment]
Still in review

**Comment by seprintour** [comment]
Going to test the new implementations
