### ISSUE TITLE
Database Re-Architecture

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#812]
# Tables

- Every table should start with the following columns: `id`, `created`, `updated` and have foreign keys in the last columns.
- We should completely stop using GitHub user/repo/org names as they have led to issues with renames etc. Instead we should ONLY use GitHub IDs (integers)
- I am referencing the production database, so some tables like `multiplier` might not exist in other databases. If so a comment should be left so that we handle the deletion.

## Access

The columns should be renamed and adhere to the above rules.

```
id, created, updated, user_id, organization_id, repository_id, multiplier, priority, time, price.
```

## Issues

Should be deleted. No idea why this exists in the first place. @0xcodercrane rfc

This seems to be constantly updated so its logic must be disconnected from the bot side. 

## Logs

Will make an exception since they are ephemeral and connected to multiple systems. 

## Multiplier

Delete.

## Penalty

- https://github.com/ubiquity/ubiquibot/issues/809

## Permits

- https://github.com/ubiquity/ubiquibot/issues/811

## Users

Seems nice to have even if we have no immediate plans for the data. We will leave it unchanged.

## Wallets

id, created, updated, user_id, wallet (char42)

**Comment by cuddle-dev** [comment]
> Should be deleted. No idea why this exists in the first place. @0xcodercrane rfc

Originally created it for data analytics of issues. but looks like no need to use it for even weekly reports. agree to delete.
@molecula451

**Comment by rndquu** [comment]
> /start

I don't think the current issue is relevant/available because (as far as I understand) it's going to be solved as a part of https://github.com/ubiquity/ubiquibot/pull/644

**Comment by molecula451** [comment]
i was thinking the same after seeing #644 linked to this issue but i didnt see relevant/related commits at #644

**Comment by molecula451** [comment]
i will finish the PR anyway you guys let me know if something come up with #644

**Comment by molecula451** [comment]
@pavlovcik can you confirm us?

Also can you confirm this?

![multi](https://github.com/ubiquity/ubiquibot/assets/41552663/7a6fd1a6-a085-4e38-8025-2407063064e6)

on "Access" table you are mentioning "multiplier" but you also mention Multiplier to be delete

**Comment by 0x4007** [comment]
I consolidated multiplier details in the access table. Perhaps we should rename the access table but it holds the miscellaneous user information. 

I guess I don't get "activity credit" cause I'm active on a branch off of my linked pull request right now, rebuilding the comment incentives code.

**Comment by molecula451** [comment]
@pavlovcik look what i have for you

https://github.com/ubiquity/ubiquibot/assets/41552663/5347a448-7d92-482c-b106-e7d77c43fc72

the 'wallet' table is ready

@rndquu

**Comment by rndquu** [comment]
> @pavlovcik look what i have for you
> 
>  id.mp4 
> the 'wallet' table is ready
> 
> @rndquu

This is great but I still think that the current issue should be solved after https://github.com/ubiquity/ubiquibot/pull/644 is merged because https://github.com/ubiquity/ubiquibot/issues/812 and https://github.com/ubiquity/ubiquibot/pull/644 are heavily interconnected

**Comment by molecula451** [comment]
I think pavlovcik could rebase what You think rndqnuu? In any case pavlovcik disable bounties on the repo :/

**Comment by molecula451** [comment]
well yes, makes a bit of some sense just in case the bot unassign me and the /start command it's still disabled this is the branch i was working https://github.com/ubiquity/ubiquibot/compare/development...molecula451:ubiquibot:db-testing these are the changes for the table so it's hopefully useful to pavlovick

**Comment by molecula451** [comment]
> well yes, makes a bit of some sense just in case the bot unassign me and it's still not done and the start command is still disabled this is the branch i was working [development...molecula451:ubiquibot:db-testing](https://github.com/ubiquity/ubiquibot/compare/development...molecula451:ubiquibot:db-testing) these are the changes for the table so it's hopefully useful to pavlovick
