### ISSUE TITLE
At this point the bot should add a price label.

### ISSUE THREAD

**Issue by molecula451** [ubiquity/ubiquibot#839]
https://github.com/ubiquity/ubiquibot/blob/e605a0fa2b1e8010192202cfffaa239b5432a27b/README.md?plain=1#L149

The bot hardly add a price label, the `should` should be `it will`

**Comment by 0x4007** [comment]
Whats the significance of this issue?

**Comment by molecula451** [comment]
> Whats the significance of this issue?

the bot it's suppose to add a price label after a "3. Add a priority label, ex: `Priority: 0 (Normal)`"

I seem this in production, but hardly seem the bot doing this (locally). I've had to manually add the prices labels before

**Comment by 0x4007** [comment]
We moved from `Priority: 0 (Normal)` to `Priority: 1 (Normal)` please update your labels. 

0 is no longer recognized as a valid pricing label.

**Comment by molecula451** [comment]
> We moved from `Priority: 0 (Normal)` to `Priority: 1 (Normal)` please update your labels.
> 
> 0 is no longer recognized as a valid pricing label.

it happens with any label, btw i just copied the thing `Priority: 0 (Normal)` from the README, updating it at #838

**Comment by molecula451** [comment]
> We moved from `Priority: 0 (Normal)` to `Priority: 1 (Normal)` please update your labels.
> 
> 0 is no longer recognized as a valid pricing label.

https://github.com/ubiquity/ubiquibot/blob/e605a0fa2b1e8010192202cfffaa239b5432a27b/README.md?plain=1#L148

**Comment by seprintour** [comment]
If its well setup, it should

**Comment by seprintour** [comment]
Just make sure the steps are clear enough, so that one that line the bot should be actively adding price and responding to slash commands

**Comment by molecula451** [comment]
it hardly does it, and it is always well set up. An improve will do better

**Comment by 0x4007** [comment]
Sorry but I didn't see this as an issue. Perhaps your environment variables are not set up correctly?

**Comment by molecula451** [comment]
Yeah. Will close it
