### ISSUE TITLE
Removal of telegram feature

### ISSUE THREAD

**Issue by whilefoo** [ubiquity/ubiquibot#842]
```
[Error: ENOENT: no such file or directory, open '/workspaces/ubiquibot/lib/assets/images/pmg.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/workspaces/ubiquibot/lib/assets/images/pmg.png'
}
error Command failed with exit code 1.
```

_Originally posted by @me505 in https://github.com/ubiquity/ubiquibot/issues/735#issuecomment-1734785730_
            

Telegram feature seems to be causing problems because some files are not copied over to `lib` when transpiled. As @pavlovcik said this is a partial implementation that's not used so we should remove it.

**Comment by molecula451** [comment]
https://github.com/ubiquity/ubiquibot/pull/802#issuecomment-1732534320

**Comment by molecula451** [comment]
lmao not really sure why you are having this issue @whilefoo not really reproducible, perhaps try a clean enviroment like a docker container

**Comment by whilefoo** [comment]
> lmao not really sure why you are having this issue @whilefoo not really reproducible, perhaps try a clean enviroment like a docker container

@me505 also has this problem so it's a real issue

**Comment by molecula451** [comment]
i was able to reproduce this issue

**Comment by molecula451** [comment]
what's the real reason of removing telegram code aside from the issues that currently has? @pavlovcik

**Comment by 0x4007** [comment]
We have a separate codebase for a telegram bot extension. Also the code here is not implemented correctly; it doesn't do anything useful.
