### ISSUE TITLE
Migrate netlify function to background function

### ISSUE THREAD

**Issue by cuddle-dev** [ubiquity/ubiquibot#843]
### Describe the background or context

We're currently encountering a function timeout issue during permit URL generation, leading to no permit URL post for the creator/assignee/reviewer sometimes

### Describe the solution

The execution limit for synchronous functions is 10 seconds but a background function has 15 minutes execution limit.
The cons of background function is we couldn't get the response. For the ubiquibot, we don't need to handle the response from the execution at least for now. Please refer to the [Netlify docs](https://docs.netlify.com/functions/overview/) for more context. 

The background functions feature is supported on the Pro plan which is our current plan.

@pavlovcik rfc

**Comment by 0x4007** [comment]
Can we delegate compute to GitHub Actions? It scales better because it's free and it's for six hours. 

For example we can make a payments microservice. We can blackbox the evm private key potentially by making a special repository that has no code, so contributors should never work on it.

**Comment by 0x4007** [comment]
We already have compute successfully delegating to GitHub Actions for long running processes.
