### ISSUE TITLE
Unit Test Coverage Workflow 

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#853]
There's a pretty big technical debt in the bot's codebase (lack of unit tests, not optimally structured code, etc...). We can't ship new production builds any more without breaking an existing functionality. 

We should setup a unit testing workflow and **stop accepting PRs without unit tests and docs**. This will cut down 80% of bounty hunters but the rest will write structured and maintainable code.

What should be done:
~~1. Setup `jest` in the bot's project
2. Add a single test
3. Add a script that runs unit tests in `package.json`~~
4. Add a workflow that runs unit tests on PRs and pushes to the `development` branch
5. Add a workflow that fails if test coverage has decreased in a PR compared to the `development` branch (as far as I remember we can simply authorize [coveralls](https://coveralls.io/) OAuth app in the bot's repository which brings this functionality out of the box)

@ubiquity/software-development Your input is really appreciated.

**Comment by 0x4007** [comment]
> not optimally structured code,

Handling this at https://github.com/ubiquity/ubiquibot/pull/644 

As for tests, @whilefoo produced some e2e tests already which I merged in and used a few times before redoing all of the code. I'll certainly make sure to get that back up and running before merging my refactor.

**Comment by rndquu** [comment]
@pavlovcik This issue also implied adding 2 workflows: running unit tests and checking test coverage for PRs. You sure we don't need those workflows? I don't think we should close this issue as not planned.

**Comment by gentlementlegen** [comment]
@rndquu I can have a look if you want, since I've been settings tests in the other repos. However, we did not set the blockage on coverage decrease anywhere yet.

**Comment by 0x4007** [comment]
> @rndquu I can have a look if you want, since I've been settings tests in the other repos. However, we did not set the blockage on coverage decrease anywhere yet.

I think that anything related to this codebase, unless it's strictly event handler related, is not a good idea to invest into. 

That's why we actually removed this codebase from the directory. 

As you know we plan to move to using the kernel asap. 

@whilefoo how's it coming along to get it deployed?

**Comment by rndquu** [comment]
> @rndquu I can have a look if you want, since I've been settings tests in the other repos. However, we did not set the blockage on coverage decrease anywhere yet.

Thank for your endeavour

I think this issue should be closed as "not planned" since we're moving to the plugin oriented architecture
