### ISSUE TITLE
Separate Partner and Bot Configs

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#859]
Depends on https://github.com/ubiquity/ubiquibot/pull/644

Check [this](https://github.com/ubiquity/ubiquibot/blob/40d836bdef663654766365f97d68b76dae4fcb6c/src/bindings/config.ts#L43) js config object. It consists of the following param categories:
1. Partner config params (ex: `price.baseMultiplier, assign.bountyHunterMax, etc...`) which are set in the partners' bot yml configs ([example](https://github.com/rndquu-org/test-repo/blob/6613b3bf91462018d1cec1b8f09eb27d072f8fc6/.github/ubiquibot-config.yml))
2. Bot config params (ex: `process.env.SUPABASE_URL, process.env.X25519_PRIVATE_KEY, etc...`) which are taken from env variables and are related solely to the bot's running instance (i.e. not to partner projects)

We should separate [this](https://github.com/ubiquity/ubiquibot/blob/40d836bdef663654766365f97d68b76dae4fcb6c/src/bindings/config.ts#L43) js config object in 2 different js configs (partner params and bot env params) so that they don't intermingle.

What should be done:
1. Separate [this](https://github.com/ubiquity/ubiquibot/blob/40d836bdef663654766365f97d68b76dae4fcb6c/src/bindings/config.ts#L43) config in 2 different js config objects (partner and env configs)
2. Check that all of the config params are used (chances are that some of the params are not used anywhere so they can be removed)
3. Update `README.md` with relevant config param descriptions

**Comment by rndquu** [comment]
@whilefoo This was originally your idea, pls check the description

**Comment by Keyrxng** [comment]
As someone who doesn't have an extremely in depth understanding of all of the internals it would be good to have that clarified better because you mentioned ``process.env.FOLLOW_UP_TIME`` but I thought that was partner specific until I read that.

Whichever config holds the least properties I assume would be bot config so something like:

```ts
module.exports = {
  log: {
    logEnvironment: process.env.LOG_ENVIRONMENT || "production",
    level: (process.env.LOG_LEVEL as LogLevel) || LogLevel.DEBUG,
    retryLimit: Number(process.env.LOG_RETRY) || 0,
  },
  supabase: {
    url: process.env.SUPABASE_URL ?? "",
    key: process.env.SUPABASE_KEY ?? "",
  },
  telegram: {
    token: process.env.TELEGRAM_BOT_TOKEN ?? "",
    delay: process.env.TELEGRAM_BOT_DELAY ? Number(process.env.TELEGRAM_BOT_DELAY) : botDelay,
  },
  logNotification: {
    url: process.env.LOG_WEBHOOK_BOT_URL || "",
    secret: process.env.LOG_WEBHOOK_SECRET || "",
    groupId: Number(process.env.LOG_WEBHOOK_GROUP_ID) || 0,
    topicId: Number(process.env.LOG_WEBHOOK_TOPIC_ID) || 0,
    enabled: true,
  },
};
```

Since the AI features are optional that would be partner specific? or being an AI powered repo manager would that be a bot level config item?

Also we need a uniform way to read the OpenAi API key as ``/ask and /review`` both operate pulling from their specific config types instead of one shared location and ``similarity`` reads from ``process.env.OPENAI_API_KEY``. 

Also the readme states that the api key should be set in ``.env`` but I'm sure I was told to remove reading from ``.env`` from within the configs, I may be mistaken but I'm adding ``process.env.OPENAI_API_KEY`` for testing then removing it for pushing.

**Comment by rndquu** [comment]
@Keyrxng 

> it would be good to have that clarified better because you mentioned process.env.FOLLOW_UP_TIME but I thought that was partner specific

You're right, it is partner specific, my mistake, updated the issue description.

> Whichever config holds the least properties I assume would be bot config

If a config param is read from a yml file ([example](https://github.com/ubiquity/ubiquibot/blob/3ad77e54a0202e442bdc7e2973326e8a7a32b74a/src/bindings/config.ts#L50)) then it is considered to be a partner config. If a config param is read only from an env variable ([example](https://github.com/ubiquity/ubiquibot/blob/3ad77e54a0202e442bdc7e2973326e8a7a32b74a/src/bindings/config.ts#L104)) then it is considered to be the bot's param (i.e. not partner specific param).

> Since the AI features are optional that would be partner specific? or being an AI powered repo manager would that be a bot level config item?

Right now we have only 2 AI related config params ([openAIKey](https://github.com/ubiquity/ubiquibot/blob/3ad77e54a0202e442bdc7e2973326e8a7a32b74a/src/bindings/config.ts#L111) and [openAITokenLimit](https://github.com/ubiquity/ubiquibot/blob/3ad77e54a0202e442bdc7e2973326e8a7a32b74a/src/bindings/config.ts#L112C19-L112C35)) both of which are partner specific.

> Also we need a uniform way to read the OpenAi API key as /ask and /review both operate pulling from their specific config types instead of one shared location and similarity reads from process.env.OPENAI_API_KEY.

I think that partner specific openai API params should be used both for `/ask` and `/review` commands (if this answers your question).

> Also the readme states that the api key should be set in .env but I'm sure I was told to remove reading from .env from within the configs, I may be mistaken but I'm adding process.env.OPENAI_API_KEY for testing then removing it for pushing.

`process.env.OPENAI_API_KEY` is indeed used [here](https://github.com/ubiquity/ubiquibot/blob/3ad77e54a0202e442bdc7e2973326e8a7a32b74a/src/helpers/similarity.ts#L73). I think it should be refactored to use openai API key from a partner config. Using a shared openai API key will bring us to rate limits and paid plans. It is simpler to make partners setup openai themselves.

**Comment by rndquu** [comment]
@Keyrxng There is a [huge refactor](https://github.com/ubiquity/ubiquibot/pull/644) coming so it makes sense to wait for that PR and then solve the current issue
