### ISSUE TITLE
DB backup

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#865]
We should periodically backup the bot's prod DB in case something goes wrong. 

What should be done:
1. Create a **private** github repository for DB backups
2. Create a workflow that will dump (both schema and data) the bot's prod DB once a day ([example](https://supabase.com/docs/guides/cli/github-action/backups#periodic-backups-workflow))
3. Try to recover the DB from a generated dump in order to check that it works

**Comment by 0x4007** [comment]
You can add my script to the yml file and it should work. The only modification required is that we need to `stuff` the database password on the interactive prompt. 

It'll be beneficial to share it here but I'm posting from mobile.

**Comment by rndquu** [comment]
> You can add my script to the yml file and it should work. The only modification required is that we need to `stuff` the database password on the interactive prompt.
> 
> It'll be beneficial to share it here but I'm posting from mobile.

What do you mean by "my script"? Could you share a link?

**Comment by PhantomCracker** [comment]
But @rndquu how can we test if we do not have schema and data? We can do a test with some mockup data maybe? Can you provide something?

**Comment by 0x4007** [comment]
From our conversation a couple of weeks ago

```sh
#!/bin/bash
CURRENT_TIMESTAMP=$(date +%s)

# pg_dump
docker \
    run \
    --rm \
    -it \
    -v \
    ~/Downloads:/backup \
    postgres:15.1 \
    pg_dump \
    -h \
    db.wfzpewmlyiozupulbuur.supabase.co \
    -p \
    5432 \
    -d \
    postgres \
    -U \
    postgres \
    -F \
    c \
    -f \
    /backup/"$CURRENT_TIMESTAMP".backup

# pg_restore
docker \
    run \
    --rm \
    -it \
    -v \
    ~/Downloads:/backup \
    postgres:15.1 \
    pg_restore \
    --no-owner \
    --no-acl \
    -F \
    c \
    -f \
    /backup/"$CURRENT_TIMESTAMP".sql \
    /backup/"$CURRENT_TIMESTAMP".backup

# diff
# diff \
# ~/Downloads/"$BEFORE_TIMESTAMP".sql \
# ~/Downloads/"$CURRENT_TIMESTAMP".sql \
# > \
# ~/Downloads/difference.diff

```

**Comment by rndquu** [comment]
> From our conversation a couple of weeks ago

Using docker container for a single `pg_dump` command seems to be an overkill. I think it is simpler either to `apt install postgresql` (with `pg_dump`) in a github runner either to `supabase db dump --db-url "$supabase_db_url" -f data.sql --data-only --use-copy` (as described [here](https://supabase.com/docs/guides/cli/github-action/backups#periodic-backups-workflow)).

**Comment by rndquu** [comment]
> But @rndquu how can we test if we do not have schema and data? We can do a test with some mockup data maybe? Can you provide something?

You can test on your own supabase remote instance DB

**Comment by PhantomCracker** [comment]
Thank you @rndquu  for all the provided information 👍

**Comment by molecula451** [comment]
![Screenshot from 2023-10-25 13-54-37](https://github.com/ubiquity/ubiquibot/assets/41552663/e3172b9f-046f-4c72-9824-16ac1fc051ad)

**Comment by rndquu** [comment]
@gitcoindev Could you self assign again?

**Comment by rndquu** [comment]
@Keyrxng Could you self assign again?

**Comment by gitcoindev** [comment]
Hi @rndquu the bot confused me here -) this is for @Keyrxng right?

**Comment by rndquu** [comment]
> Hi @rndquu the bot confused me here -) this is for @Keyrxng right?

Yes, sorry for bothering you

**Comment by gitcoindev** [comment]
> > Hi @rndquu the bot confused me here -) this is for @Keyrxng right?
> 
> Yes, sorry for bothering you

No worries, thank you for clarifying this!

**Comment by Keyrxng** [comment]
@rndquu unable to reassign atm mate

**Comment by rndquu** [comment]
Closing this as completed because dumps are created fine https://github.com/ubiquity/ubiquibot-db-backups

**Comment by Keyrxng** [comment]
> Permit generation skipped because bounty amount after penalty is 0
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

wtf? :))

**Comment by rndquu** [comment]
> Permit generation skipped because bounty amount after penalty is 0
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

@pavlovcik I guess we should send the reward manually

**Comment by 0x4007** [comment]
> Permit generation skipped because bounty amount after penalty is 0<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>

Penalty system is not good in this implementation. Curious what issue was reopened that you were paid for.

**Comment by 0x4007** [comment]
I'll need to address this later then. Let me know what address you want me to send to @Keyrxng

**Comment by Keyrxng** [comment]
> Curious what issue was reopened that you were paid for.

It can only have been when you reopened /ask I think

I claimed the faucet permit earlier today without issue in generating it so this is very strange
