### ISSUE TITLE
Refactor logging into a separate NPM module

### ISSUE THREAD

**Issue by gitcoindev** [ubiquity/ubiquibot#899]
As requested and discussed with @pavlovcik .

**Comment by 0x4007** [comment]
How's this coming along?

**Comment by gitcoindev** [comment]
I will try to push a pull request today.

**Comment by gitcoindev** [comment]
Still testing, has to fix one export but looks almost good now.

Related changes needed to switch to NPM logging module  in `refactor/general` branch: https://github.com/pavlovcik/ubiquibot/pull/60

**Comment by gitcoindev** [comment]
Pull request ready for the review.

**Comment by 0x4007** [comment]
> ```diff
> ! action returned an unexpected value
> ```
> ```json
> {
>   "logReturn": null,
>   "handlerType": {
>     "type": "wildcard",
>     "actions": [
>       null
>     ]
>   },
>   "activeHandler": "checkTasksToUnassign",
>   "caller": "renderCatchAll",
>   "revision": "07ce845"
> }
> ```

As you can see we are close to go shipping. Just debugging some small last issues still.

**Comment by gitcoindev** [comment]
> > ```diff
> > ! action returned an unexpected value
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```json
> > {
> >   "logReturn": null,
> >   "handlerType": {
> >     "type": "wildcard",
> >     "actions": [
> >       null
> >     ]
> >   },
> >   "activeHandler": "checkTasksToUnassign",
> >   "caller": "renderCatchAll",
> >   "revision": "07ce845"
> > }
> > ```
> 
> As you can see we are close to go shipping. Just debugging some small last issues still.

I am quite sure we will make it.
