### ISSUE TITLE
Setup RLS and CLS for supabase

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#919]
Right now we're using a pavlovcik's supabase DB instance with disabled [RLS](https://supabase.com/docs/guides/auth/row-level-security)

What should be done:
1. Make sure that [RLS](https://supabase.com/docs/guides/auth/row-level-security) is enabled and the bot acts as expected
2. Enable [CLS](https://supabase.com/docs/guides/auth/column-level-security) and make sure that `permits.transaction` field can only be updated by an authorized user who matches `permits.beneficiary_id` (related [comment](https://github.com/ubiquity/pay.ubq.fi/pull/173#discussion_r1502727455))

**Comment by 0x4007** [comment]
Can you do a time estimate on this?

**Comment by gentlementlegen** [comment]
Important notes:

The column rights features is still in Alpha through the Supabase Dashboard, so to be manipulated with caution. Secondly:
```
Changes to column privileges will not be reflected in migrations when running supabase db diff.
Column privileges are not supported in the current version of the Supabase CLI.
You will need to manually apply these changes to your database.
```
Third, the changes also impact `audit.ubq` project, since it also pulls data from the db (reads only).

**Comment by rndquu** [comment]
> You will need to manually apply these changes to your database.

By "manually" it is meant to set priviliges via supabase's dashboard UI, right?

> Third, the changes also impact audit.ubq project, since it also pulls data from the db (reads only).

As far as I remember https://audit.ubq.fi/ needs access only to the `permits` table so it seems to be ok to allow https://audit.ubq.fi/ read access to the `permits` table.

**Comment by gentlementlegen** [comment]
Yes audit is good with read only permissions on `permits` so that's all good, if you can think of any project that is also linked to the db that we should test please let me know.

Manually means that if we run a `diff` these changes won't be contained in the migration file. So any change done through the UI will be lost when it comes to CLS and migrations, which I mention to avoid mistakes later. Otherwise it works fine so far.

**Comment by gentlementlegen** [comment]
@pavlovcik @rndquu Is the `pavlovcik's supabase DB` also used for the bot in production? Or is there a different instance for this? Also asking because the migrations in this repo are not matching.

**Comment by rndquu** [comment]
> So any change done through the UI will be lost when it comes to CLS and migrations, which I mention to avoid mistakes later.

The best thing we can do in this case is to describe the required RLS/CLS setup in the README file

> Is the pavlovcik's supabase DB also used for the bot in production?

Yes

> Also asking because the migrations in this repo are not matching.

Yes, migrations in the current repo are deprecated. Migrations for the [kernel](https://github.com/ubiquity/ubiquibot-kernel) are not yet created and I'm in doubt if we need ones since all of the kernel plugins will have their own DBs so I'm not sure what exactly we need to store in the kernel's DB.

**Comment by gentlementlegen** [comment]
So the `wfzpewmlyiozupulbuur` Supabase project has been updated as such:
- locations: read-only for public
- permits: read-only for public
- tokens: read-only for public
- users: read-only for public
- wallets: read-only for public

All the other tables have no rules so are accessible only by service key / admin.

The reason why all these table need the read-only is to satisfy `audit` that calls
```TypeScript
    const { data: permits } = await supabase
      .from("permits")
      .select("*, locations(*), users(*, wallets(*)), tokens(*)")
      .in("locations.issue_id", issueIds)
      .not("locations", "is", null);
```
To retrieve permits and their associated data. If we don't allow the read, all the data returned is empty within the permit.

For updates, the column transaction is the only one that can be modified by a user
![image](https://github.com/ubiquity/ubiquibot/assets/9807008/9b2c7b87-039a-49ea-9b27-e58ba24029e5)
