### ISSUE TITLE
Add first time contributor message

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ubiquibot#96]
# Specification

The two business problems to solve are: 

1. a custom message that partners can use to greet new hunters
2. show a list of all of the bot commands that the new hunter can invoke.

We must create new config properties: 
- [ ] `FIRST_TIME_CONTRIBUTOR_GREETING_HEADER`: string;
- [ ] `FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU`: boolean;
- [ ] `FIRST_TIME_CONTRIBUTOR_GREETING_FOOTER`: string;

Post the header first, then the help menu, and lastly the footer in a single "first time contributor greeting" comment.

- [ ] Be sure to also update the README.md with these config properties.

# Example Input

```
FIRST_TIME_CONTRIBUTOR_GREETING_HEADER="Thank you for contributing to UbiquiBot! Please be sure to set your wallet address before completing your first bounty so that the automatic payout upon task completion will work for you."
FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU=true
FIRST_TIME_CONTRIBUTOR_GREETING_FOOTER="###### Also please star this repository and [@ubiquity/devpool-directory](https://github.com/ubiquity/devpool-directory/) to show your support. It helps a lot!"
```

# Example Output

Thank you for contributing to UbiquiBot! Please be sure to set your wallet address before completing your first bounty so that the automatic payout upon task completion will work for you. 

```
- /assign: Assign the origin sender to the issue automatically.
- /unassign: Unassign the origin sender from the issue automatically.
- /help: List all available commands.
- /payout: Disable automatic payment for the issue.
- /multiplier: Set bounty multiplier (for treasury)
- /allow: Set access control. (Admin Only)
- /wallet: <WALLET_ADDRESS | ENS_NAME>: Register the hunter's wallet address. 
  ex1: /wallet 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 
  ex2: /wallet vitalik.eth
```

**Comment by pavlovcik** [comment]
I think we should combine this and https://github.com/ubiquity/ubiquibot/issues/228 into one bounty. The two business problems to solve are 1. a custom message that partners can use to greet new hunters and 2. a list of all of the bot commands that the hunter can invoke.

Perhaps we can make two config properties: 
1. `FIRST_TIME_CONTRIBUTOR_GREETING_MESSAGE`: string;
2. `FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU`: boolean;

We should post the greeting first, and then the help menu, ideally in a single comment.

**Comment by rndquu** [comment]
> I think we should combine this and #228 into one bounty. The two business problems to solve are 1. a custom message that partners can use to greet new hunters and 2. a list of all of the bot commands that the hunter can invoke.
> 
> Perhaps we can make two config properties:
> 
> 1. `FIRST_TIME_CONTRIBUTOR_GREETING_MESSAGE`: string;
> 2. `FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU`: boolean;
> 
> We should post the greeting first, and then the help menu, ideally in a single comment.

Perhaps we can use the tutorial message in the `FIRST_TIME_CONTRIBUTOR_GREETING_MESSAGE` variable?

```
Welcome to the ubiquity-dollar repository. Please comment "/assign" on any issue if you would like to work on it. UbiquiBot will immediately assign you to the issue. Please comment "/wallet" at any time with your wallet address following (e.g. /wallet ubq.eth) to register your payment address for task completion.
```

**Comment by pavlovcik** [comment]
> and tag the author

Why did you add this?

**Comment by rndquu** [comment]
> > and tag the author
> 
> Why did you add this?

There are no any special thoughts under this requirement. At that time some of the bot's commands started with the author tag so it felt to be normal to start greeting with the author's tag.

**Comment by pavlovcik** [comment]
I like the idea of using tags sparingly, because there are different levels for notification filtering, and one of them is tagging. So, at least, for myself, I have only push notifications enabled on my GitHub iOS app with tagging.

**Comment by EtherealGlow** [comment]
@rndquu what if FIRST_TIME_CONTRIBUTOR_GREETING_MESSAGE="" and FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU=false?

**Comment by rndquu** [comment]
> @rndquu what if FIRST_TIME_CONTRIBUTOR_GREETING_MESSAGE="" and FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU=false?

Then it seems reasonable to show nothing

**Comment by EtherealGlow** [comment]
.

**Comment by pavlovcik** [comment]
> .

Will you finish implementing the requested changes?

**Comment by EtherealGlow** [comment]
making the changes today

**Comment by EtherealGlow** [comment]
sorry but i do not have the time to make the changes
i am unassigning from this issue
i will complete if i have some time again 
sorry about that

**Comment by EtherealGlow** [comment]
bot you ded?

**Comment by 0xcodercrane** [comment]
https://github.com/ubiquibot/production/issues/35#issuecomment-1681476255

It worked here. let me take a look anyway

**Comment by pavlovcik** [comment]
> https://github.com/ubiquibot/production/issues/35#issuecomment-1681476255
> 
> 
> 
> It worked here. let me take a look anyway

I don't understand how your comment is related to the problem

**Comment by 0xcodercrane** [comment]
> > [ubiquibot/production#35 (comment)](https://github.com/ubiquibot/production/issues/35#issuecomment-1681476255)
> > It worked here. let me take a look anyway
> 
> I don't understand how your comment is related to the problem

It means bot not ded actually.

**Comment by pavlovcik** [comment]
> > > [ubiquibot/production#35 (comment)](https://github.com/ubiquibot/production/issues/35#issuecomment-1681476255)
> > > It worked here. let me take a look anyway
> > 
> > 
> > I don't understand how your comment is related to the problem
> 
> It means bot not ded actually.

Why did the bot go down? Is it a recurring issue?

**Comment by EtherealGlow** [comment]
Wait my boy, patience

**Comment by EtherealGlow** [comment]
Patience is bitter, but its fruit is sweet

**Comment by EtherealGlow** [comment]
@pavlovcik did something happen with the bounty's, i remember they were higher

**Comment by EtherealGlow** [comment]
@0xcodercrane the bot ain't working

**Comment by pavlovcik** [comment]
Each repo has a different base rate. 

I fixed the bot.

**Comment by pavlovcik** [comment]
I saw the logs at the bottom attempted to generate a payout permit, but it never posted here so there's a new bug @0xcodercrane 

Unfortunately, there was also some type of iOS error dealing with the supabase webapp, and I accidentally deleted the log while trying to copy paste it.

**Comment by EtherealGlow** [comment]
It generated conv rewards?

**Comment by EtherealGlow** [comment]
@pavlovcik issue completion rewards aren't generated

**Comment by EtherealGlow** [comment]
@0xcodercrane

**Comment by EtherealGlow** [comment]
Bruh

**Comment by pavlovcik** [comment]
Looks like the registered wallets were dropped from the database? The query command should work and just say that the wallet is not assigned.

**Comment by EtherealGlow** [comment]
When will I get assignee reward tho 💀

**Comment by pavlovcik** [comment]
I might have to manually send them. Please remind me where else it was not sent!

**Comment by pavlovcik** [comment]
https://gnosisscan.io/tx/0xfff232c2f4cb93e74c403cd71ac76b87df11dabdfa6d4c719e87ca85c79a40ce
